import { hashFarmOsContract, hasExactFarmOsKeys, isCanonicalFarmOsIso, isFarmOsDigest, isFarmOsIdentifier, isFarmOsRecord } from "./farm_os_approved_proposal_contract";
import { FARM_OS_CAPABILITIES, parseFarmOsTypedContextReference, type FarmOsCapabilityId, type FarmOsTypedContextReference } from "./farm_os_crop_planning_workforce_governance";

export const FARM_OS_WORK_PLAN_ASSIGNMENT_SCHEMA_VERSION = "farmos.work-plan-assignment.v1" as const;
export const FARM_OS_WORK_PLAN_DRAFT_SCHEMA_VERSION = "farmos.work-plan-draft.v1" as const;
export const FARM_OS_ASSIGNMENT_CANDIDATE_SCHEMA_VERSION = "farmos.assignment-candidate.v1" as const;
export const FARM_OS_WORK_PLAN_COMMAND_DRAFT_SCHEMA_VERSION = "farmos.work-plan-command-draft.v1" as const;
export const FARM_OS_WORK_PLAN_POLICY_VERSION = "work-plan-assignment-policy.v1" as const;
export const FARM_OS_WORK_PLAN_GENERATABLE_STATUSES = ["draft", "review_ready"] as const;
export const FARM_OS_WORK_PLAN_STATUSES = ["draft", "review_ready", "confirmed", "cancelled", "superseded"] as const;
export const FARM_OS_ASSIGNMENT_CANDIDATE_STATUSES = ["candidate", "review_ready", "rejected", "expired", "superseded"] as const;
export const FARM_OS_WORK_PLAN_COMMAND_TYPES = ["create_work_plan_draft", "assignment_candidate", "confirm_work_plan", "assign_member", "unassign_member", "cancel_work_plan"] as const;
export const FARM_OS_WORK_PLAN_GENERATABLE_COMMAND_TYPES = ["create_work_plan_draft", "assignment_candidate"] as const;
export const FARM_OS_WORK_PLAN_REJECTION_CODES = [
  "proposal_not_approved","proposal_expired","approval_missing","approval_expired","approval_reused","reauthorization_missing","reauthorization_expired",
  "actor_inactive","capability_missing","scope_mismatch","target_unknown","member_unknown","member_inactive","participation_inactive","availability_unknown",
  "member_unavailable","capability_mismatch","time_overlap","duplicate_assignment","workload_exceeded","evidence_stale","stale_expected_version",
  "idempotency_conflict","duplicate_draft","unknown_field","invalid_identifier","invalid_timestamp","draft_invalid","assignment_candidate_invalid",
  "authoritative_command_forbidden","hermes_direct_execution","observer_auto_adoption_forbidden","authority_unavailable","authority_mismatch",
  "audit_correlation_mismatch","production_dependency_forbidden","business_write_attempt_detected","external_side_effect_attempt_detected",
] as const;
export type WorkPlanAssignmentRejectionCode = (typeof FARM_OS_WORK_PLAN_REJECTION_CODES)[number];

export type WorkPlanDraft = {
  schema_version:typeof FARM_OS_WORK_PLAN_DRAFT_SCHEMA_VERSION;work_plan_draft_id:string;source_proposal_id:string;source_approval_id:string;
  target_reference:FarmOsTypedContextReference;title:string;description:string;planned_date:string;planned_start_time:string;estimated_duration_minutes:number;
  priority:"low"|"normal"|"high";status:(typeof FARM_OS_WORK_PLAN_STATUSES)[number];expected_version:number;created_at:string;expires_at:string;
};
export type AssignmentCandidate = {
  schema_version:typeof FARM_OS_ASSIGNMENT_CANDIDATE_SCHEMA_VERSION;assignment_candidate_id:string;work_plan_draft_id:string;member_reference:FarmOsTypedContextReference;
  candidate_reason:string;required_capabilities:readonly FarmOsCapabilityId[];matched_capabilities:readonly FarmOsCapabilityId[];scope:string;
  estimated_duration_minutes:number;availability_status:"available"|"unavailable"|"unknown";conflict_status:"none"|"time_overlap"|"duplicate_assignment"|"workload_exceeded"|"unknown";
  status:(typeof FARM_OS_ASSIGNMENT_CANDIDATE_STATUSES)[number];created_at:string;expires_at:string;
};
export type WorkPlanReauthorizationEvidence = {
  actor_id:string;actor_type:"human";capability:"edit_work_plan"|"assign_staff";scope:string;authenticated_at:string;reauthorized_at:string;expires_at:string;
  policy_version:typeof FARM_OS_WORK_PLAN_POLICY_VERSION;authorization_result:"authorized";
};
export type WorkPlanAssignmentRequest = {
  schema_version:typeof FARM_OS_WORK_PLAN_ASSIGNMENT_SCHEMA_VERSION;request_id:string;operation_kind:"create_work_plan_draft"|"assignment_candidate";
  approved_proposal:{proposal_id:string;status:"approved";expires_at:string};approval_evidence:{approval_id:string;proposal_id:string;decision:"approved";decided_by:string;decided_at:string;expires_at:string};
  work_plan_draft:WorkPlanDraft;assignment_candidate:AssignmentCandidate|null;requested_by:string;requested_at:string;authority_evidence_ref:string;
  reauthorization_evidence:WorkPlanReauthorizationEvidence;expected_version:number;idempotency_key:string;request_fingerprint:string;correlation_id:string;causation_id:string;
  runtime:"farmos_native_runtime"|"hermes";human_edit_revision:number;business_write_requested:false;external_side_effect_requested:false;
};
export type WorkPlanAssignmentAuthority = {
  actor_id:string;actor_active:boolean;capabilities:readonly FarmOsCapabilityId[];scope:string;policy_version:typeof FARM_OS_WORK_PLAN_POLICY_VERSION;
  reauthorized_at:string;expires_at:string;proposal_id:string;proposal_approved:boolean;proposal_expires_at:string;approval_id:string;approved_by:string;approval_expires_at:string;
  target_known:boolean;target_version:number;evidence_observed_at:string;member_id:string|null;member_known:boolean;member_active:boolean;participation_active:boolean;
  draft_snapshot_hash:string;candidate_snapshot_hash:string|null;required_capabilities:readonly FarmOsCapabilityId[];member_capabilities:readonly FarmOsCapabilityId[];member_scope:string|null;availability:"available"|"unavailable"|"unknown";time_overlap:boolean;
  duplicate_assignment:boolean;workload_minutes:number;workload_limit_minutes:number;source:"human_review_ledger"|"authorization_service"|"current_membership_projection"|"current_policy_registry";
};
export interface WorkPlanAssignmentAuthorityPort {
  getAuthority(input:{authority_evidence_ref:string;actor_id:string;proposal_id:string;work_plan_draft_id:string;draft_snapshot_hash:string;candidate_snapshot_hash:string|null;member_id:string|null;target_scope:string;expected_version:number}):Promise<WorkPlanAssignmentAuthority|{state:"not_found"|"unknown"}>;
}
export type WorkPlanCommandDraft = {
  schema_version:typeof FARM_OS_WORK_PLAN_COMMAND_DRAFT_SCHEMA_VERSION;command_id:string;proposal_id:string;approval_id:string;
  command_type:(typeof FARM_OS_WORK_PLAN_COMMAND_TYPES)[number];target_system:"farming_app_server_boundary";target_reference:FarmOsTypedContextReference;
  idempotency_key:string;requested_by:string;approved_by:string;expected_version:number;payload:{work_plan_draft_id:string;assignment_candidate_id:string|null};
  status:"draft";correlation_id:string;created_at:string;expires_at:string;original_command_id:string|null;supersedes_command_id:string|null;
  compensation_for_command_id:string|null;audit_ref:string;
};
export type WorkPlanObserverFinding = {
  finding_kind:"duplicate_assignment_risk"|"stale_availability"|"scope_mismatch"|"capability_mismatch"|"workload_conflict"|"missing_evidence"|"runtime_disagreement";
  work_plan_draft_id:string;assignment_candidate_id:string|null;correlation_id:string;candidate_only:true;automatic_policy_adoption:false;automatic_skill_adoption:false;
};
export type WorkPlanAssignmentAudit = {
  request_id:string;proposal_id:string;approval_id:string;work_plan_draft_id:string;assignment_candidate_id:string|null;request_actor:string;capability:string;scope:string;
  authority_result:"authorized"|"missing"|"mismatch";reauthorization_result:"authorized"|"rejected";idempotency_key_hash:string;request_fingerprint:string;
  result:"draft_ready"|"already_processed"|"outcome_unknown"|"rejected";rejection_code:WorkPlanAssignmentRejectionCode|null;correlation_id:string;causation_id:string;
  processed_at:string;human_edit_revalidated:boolean;authoritative_state_required:boolean;production_execution_performed:false;business_write_performed:false;external_side_effect_performed:false;
};
export type WorkPlanAssignmentOutcome = {result:WorkPlanAssignmentAudit["result"];rejection_code:WorkPlanAssignmentRejectionCode|null;command_draft:WorkPlanCommandDraft|null;audit:WorkPlanAssignmentAudit;findings:readonly WorkPlanObserverFinding[]};

const DRAFT_KEYS=["schema_version","work_plan_draft_id","source_proposal_id","source_approval_id","target_reference","title","description","planned_date","planned_start_time","estimated_duration_minutes","priority","status","expected_version","created_at","expires_at"] as const;
const CANDIDATE_KEYS=["schema_version","assignment_candidate_id","work_plan_draft_id","member_reference","candidate_reason","required_capabilities","matched_capabilities","scope","estimated_duration_minutes","availability_status","conflict_status","status","created_at","expires_at"] as const;
const REQUEST_KEYS=["schema_version","request_id","operation_kind","approved_proposal","approval_evidence","work_plan_draft","assignment_candidate","requested_by","requested_at","authority_evidence_ref","reauthorization_evidence","expected_version","idempotency_key","request_fingerprint","correlation_id","causation_id","runtime","human_edit_revision","business_write_requested","external_side_effect_requested"] as const;
const REAUTH_KEYS=["actor_id","actor_type","capability","scope","authenticated_at","reauthorized_at","expires_at","policy_version","authorization_result"] as const;
const safeText=(v:unknown,min:number,max:number)=>typeof v==="string"&&v.trim().length>=min&&v.length<=max&&!/[\u0000-\u001f\u007f<>]/u.test(v);
const date=(v:unknown)=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/u.test(v)&&Number.isFinite(Date.parse(`${v}T00:00:00.000Z`));
const time=(v:unknown)=>typeof v==="string"&&/^([01]\d|2[0-3]):[0-5]\d$/u.test(v);
const positive=(v:unknown)=>Number.isSafeInteger(v)&&(v as number)>0;
const capabilityList=(v:unknown):v is FarmOsCapabilityId[]=>Array.isArray(v)&&v.length>0&&v.length<=16&&new Set(v).size===v.length&&v.every(x=>FARM_OS_CAPABILITIES.includes(x as FarmOsCapabilityId));
const scopeOf=(ref:FarmOsTypedContextReference)=>`${ref.source_system}:${ref.context_type}:${ref.reference_id}:${ref.reference_version}`;
const referenceFresh=(ref:FarmOsTypedContextReference,now:string)=>ref.freshness_status==="fresh"&&Date.parse(ref.observed_at)<=Date.parse(now)&&Date.parse(now)-Date.parse(ref.observed_at)<=300_000&&Date.parse(ref.scope.valid_from)<=Date.parse(now)&&(ref.scope.valid_until===null||Date.parse(ref.scope.valid_until)>Date.parse(now));

export function parseWorkPlanDraft(value:unknown,{coreGenerated=true}:{coreGenerated?:boolean}={}):WorkPlanDraft|null{
  if(!isFarmOsRecord(value)||!hasExactFarmOsKeys(value,DRAFT_KEYS)||value.schema_version!==FARM_OS_WORK_PLAN_DRAFT_SCHEMA_VERSION||!isFarmOsIdentifier(value.work_plan_draft_id)||!isFarmOsIdentifier(value.source_proposal_id)||!isFarmOsIdentifier(value.source_approval_id)||!parseFarmOsTypedContextReference(value.target_reference)||!safeText(value.title,1,160)||!safeText(value.description,1,2000)||!date(value.planned_date)||!time(value.planned_start_time)||!positive(value.estimated_duration_minutes)||(value.estimated_duration_minutes as number)>1440||!(value.priority==="low"||value.priority==="normal"||value.priority==="high")||!FARM_OS_WORK_PLAN_STATUSES.includes(value.status as never)||!positive(value.expected_version)||!isCanonicalFarmOsIso(value.created_at)||!isCanonicalFarmOsIso(value.expires_at)||Date.parse(value.expires_at as string)<=Date.parse(value.created_at as string))return null;
  if(coreGenerated&&!FARM_OS_WORK_PLAN_GENERATABLE_STATUSES.includes(value.status as never))return null;
  return value as unknown as WorkPlanDraft;
}
export function parseAssignmentCandidate(value:unknown):AssignmentCandidate|null{
  if(!isFarmOsRecord(value)||!hasExactFarmOsKeys(value,CANDIDATE_KEYS))return null;const memberReference=parseFarmOsTypedContextReference(value.member_reference);
  if(value.schema_version!==FARM_OS_ASSIGNMENT_CANDIDATE_SCHEMA_VERSION||!isFarmOsIdentifier(value.assignment_candidate_id)||!isFarmOsIdentifier(value.work_plan_draft_id)||!memberReference||memberReference.context_type!=="workforce_member"||!safeText(value.candidate_reason,3,1000)||!capabilityList(value.required_capabilities)||!capabilityList(value.matched_capabilities)||!safeText(value.scope,3,300)||!positive(value.estimated_duration_minutes)||!["available","unavailable","unknown"].includes(String(value.availability_status))||!["none","time_overlap","duplicate_assignment","workload_exceeded","unknown"].includes(String(value.conflict_status))||!FARM_OS_ASSIGNMENT_CANDIDATE_STATUSES.includes(value.status as never)||!isCanonicalFarmOsIso(value.created_at)||!isCanonicalFarmOsIso(value.expires_at)||Date.parse(value.expires_at as string)<=Date.parse(value.created_at as string))return null;
  return value as unknown as AssignmentCandidate;
}
export const computeWorkPlanRequestFingerprint=(request:Omit<WorkPlanAssignmentRequest,"request_fingerprint">)=>hashFarmOsContract({operation_kind:request.operation_kind,proposal_id:request.approved_proposal.proposal_id,approval_id:request.approval_evidence.approval_id,work_plan_draft:request.work_plan_draft,assignment_candidate:request.assignment_candidate,requested_by:request.requested_by,requested_at:request.requested_at,expected_version:request.expected_version,correlation_id:request.correlation_id,causation_id:request.causation_id,human_edit_revision:request.human_edit_revision});
export const computeWorkPlanDraftSnapshotHash=(draft:WorkPlanDraft)=>hashFarmOsContract(draft);
export const computeAssignmentCandidateSnapshotHash=(candidate:AssignmentCandidate)=>hashFarmOsContract(candidate);

type Stored={fingerprint:string;outcome:WorkPlanAssignmentOutcome};
export class InMemoryWorkPlanAssignmentStore {
  private readonly keys=new Map<string,Stored>();private readonly proposals=new Set<string>();private readonly approvals=new Set<string>();private readonly assignments=new Set<string>();
  readonly counters={reservation_count:0,command_draft_count:0,production_execution_count:0,business_write_count:0,external_side_effect_count:0};readonly audit:WorkPlanAssignmentAudit[]=[];
  reserve(input:{key:string;fingerprint:string;proposal:string;approval:string;assignment:string|null}){this.counters.reservation_count++;const existing=this.keys.get(input.key);if(existing)return existing.fingerprint===input.fingerprint?"replay":"conflict";if(this.proposals.has(input.proposal))return"duplicate_draft";if(this.approvals.has(input.approval))return"approval_reused";if(input.assignment&&this.assignments.has(input.assignment))return"duplicate_assignment";return"new";}
  commit(input:{key:string;fingerprint:string;proposal:string;approval:string;assignment:string|null;outcome:WorkPlanAssignmentOutcome}){this.keys.set(input.key,{fingerprint:input.fingerprint,outcome:structuredClone(input.outcome)});this.proposals.add(input.proposal);this.approvals.add(input.approval);if(input.assignment)this.assignments.add(input.assignment);this.counters.command_draft_count++;this.audit.push(structuredClone(input.outcome.audit));}
  replay(key:string){const value=this.keys.get(key);return value?structuredClone(value.outcome):null;}record(audit:WorkPlanAssignmentAudit){this.audit.push(structuredClone(audit));}
}

const timeout=<T>(promise:Promise<T>)=>new Promise<T>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("authority_timeout")),100);promise.then(v=>{clearTimeout(timer);resolve(v)},e=>{clearTimeout(timer);reject(e)})});
export const createWorkPlanObserverFinding=(kind:WorkPlanObserverFinding["finding_kind"],draft:WorkPlanDraft,candidate:AssignmentCandidate|null,correlation:string):WorkPlanObserverFinding=>({finding_kind:kind,work_plan_draft_id:draft.work_plan_draft_id,assignment_candidate_id:candidate?.assignment_candidate_id??null,correlation_id:correlation,candidate_only:true,automatic_policy_adoption:false,automatic_skill_adoption:false});
const finding=createWorkPlanObserverFinding;

export async function simulateWorkPlanAssignmentApply(input:{request:unknown;authority_port:WorkPlanAssignmentAuthorityPort;store:InMemoryWorkPlanAssignmentStore;now:string}):Promise<WorkPlanAssignmentOutcome>{
  const raw=isFarmOsRecord(input.request)?input.request:{};const draft=parseWorkPlanDraft(raw.work_plan_draft);const candidate=raw.assignment_candidate===null?null:parseAssignmentCandidate(raw.assignment_candidate);
  const requestId=typeof raw.request_id==="string"?raw.request_id:"request_rejected",proposalId=isFarmOsRecord(raw.approved_proposal)&&typeof raw.approved_proposal.proposal_id==="string"?raw.approved_proposal.proposal_id:"proposal_rejected",approvalId=isFarmOsRecord(raw.approval_evidence)&&typeof raw.approval_evidence.approval_id==="string"?raw.approval_evidence.approval_id:"approval_rejected";
  const correlation=typeof raw.correlation_id==="string"?raw.correlation_id:"correlation_rejected",causation=typeof raw.causation_id==="string"?raw.causation_id:"causation_rejected",actor=typeof raw.requested_by==="string"?raw.requested_by:"";
  const baseAudit=(result:WorkPlanAssignmentAudit["result"],code:WorkPlanAssignmentRejectionCode|null,authority:WorkPlanAssignmentAudit["authority_result"]="missing",authoritative=false):WorkPlanAssignmentAudit=>({request_id:requestId,proposal_id:proposalId,approval_id:approvalId,work_plan_draft_id:draft?.work_plan_draft_id??"",assignment_candidate_id:candidate?.assignment_candidate_id??null,request_actor:actor,capability:isFarmOsRecord(raw.reauthorization_evidence)&&typeof raw.reauthorization_evidence.capability==="string"?raw.reauthorization_evidence.capability:"",scope:isFarmOsRecord(raw.reauthorization_evidence)&&typeof raw.reauthorization_evidence.scope==="string"?raw.reauthorization_evidence.scope:"",authority_result:authority,reauthorization_result:authority==="authorized"?"authorized":"rejected",idempotency_key_hash:hashFarmOsContract({idempotency_key:raw.idempotency_key??""}),request_fingerprint:typeof raw.request_fingerprint==="string"?raw.request_fingerprint:hashFarmOsContract({invalid:true}),result,rejection_code:code,correlation_id:correlation,causation_id:causation,processed_at:input.now,human_edit_revalidated:typeof raw.human_edit_revision==="number"&&raw.human_edit_revision>0,authoritative_state_required:authoritative,production_execution_performed:false,business_write_performed:false,external_side_effect_performed:false});
  const finish=(result:WorkPlanAssignmentAudit["result"],code:WorkPlanAssignmentRejectionCode|null,command:WorkPlanCommandDraft|null,authority:WorkPlanAssignmentAudit["authority_result"]="missing",findings:WorkPlanObserverFinding[]=[],authoritative=false)=>{const outcome={result,rejection_code:code,command_draft:command,audit:baseAudit(result,code,authority,authoritative),findings} satisfies WorkPlanAssignmentOutcome;input.store.record(outcome.audit);return outcome};
  if(!isFarmOsRecord(raw)||!hasExactFarmOsKeys(raw,REQUEST_KEYS))return finish("rejected","unknown_field",null);
  if(raw.schema_version!==FARM_OS_WORK_PLAN_ASSIGNMENT_SCHEMA_VERSION||!isFarmOsIdentifier(raw.request_id)||!isFarmOsIdentifier(raw.requested_by)||!isFarmOsIdentifier(raw.authority_evidence_ref)||!isFarmOsIdentifier(raw.idempotency_key)||!isFarmOsDigest(raw.request_fingerprint)||!isFarmOsIdentifier(raw.correlation_id)||!isFarmOsIdentifier(raw.causation_id))return finish("rejected","invalid_identifier",null);
  if(!isCanonicalFarmOsIso(raw.requested_at)||!isCanonicalFarmOsIso(input.now)||Date.parse(raw.requested_at as string)>Date.parse(input.now))return finish("rejected","invalid_timestamp",null);
  if(!(raw.operation_kind==="create_work_plan_draft"||raw.operation_kind==="assignment_candidate"))return finish("rejected","authoritative_command_forbidden",null);
  if(!draft)return finish("rejected","draft_invalid",null);if(raw.operation_kind==="assignment_candidate"&&!candidate)return finish("rejected","assignment_candidate_invalid",null);if(raw.operation_kind==="create_work_plan_draft"&&raw.assignment_candidate!==null)return finish("rejected","assignment_candidate_invalid",null);
  if(Date.parse(draft.expires_at)<=Date.parse(input.now)||(candidate&&Date.parse(candidate.expires_at)<=Date.parse(input.now))||!referenceFresh(draft.target_reference,input.now)||(candidate&&!referenceFresh(candidate.member_reference,input.now)))return finish("rejected","evidence_stale",null);
  if(draft.target_reference.required_capability!=="edit_work_plan"||(candidate&&candidate.member_reference.required_capability!=="assign_staff"))return finish("rejected","capability_mismatch",null);
  if(candidate&&!(candidate.status==="candidate"||candidate.status==="review_ready"))return finish("rejected","assignment_candidate_invalid",null);
  if(candidate&&candidate.estimated_duration_minutes!==draft.estimated_duration_minutes)return finish("rejected","assignment_candidate_invalid",null);
  if(!isFarmOsRecord(raw.approved_proposal)||!hasExactFarmOsKeys(raw.approved_proposal,["proposal_id","status","expires_at"])||raw.approved_proposal.status!=="approved")return finish("rejected","proposal_not_approved",null);
  if(raw.approved_proposal.proposal_id!==draft.source_proposal_id||!isCanonicalFarmOsIso(raw.approved_proposal.expires_at)||Date.parse(raw.approved_proposal.expires_at as string)<=Date.parse(input.now))return finish("rejected","proposal_expired",null);
  if(!isFarmOsRecord(raw.approval_evidence)||!hasExactFarmOsKeys(raw.approval_evidence,["approval_id","proposal_id","decision","decided_by","decided_at","expires_at"]))return finish("rejected","approval_missing",null);
  if(raw.approval_evidence.decision!=="approved"||raw.approval_evidence.approval_id!==draft.source_approval_id||raw.approval_evidence.proposal_id!==draft.source_proposal_id||!isCanonicalFarmOsIso(raw.approval_evidence.decided_at)||!isCanonicalFarmOsIso(raw.approval_evidence.expires_at)||Date.parse(raw.approval_evidence.decided_at as string)>Date.parse(raw.requested_at as string)||Date.parse(raw.approval_evidence.decided_at as string)>Date.parse(input.now)||Date.parse(raw.approval_evidence.expires_at as string)<=Date.parse(input.now))return finish("rejected","approval_expired",null);
  if(raw.runtime!=="farmos_native_runtime")return finish("rejected","hermes_direct_execution",null);if(raw.business_write_requested!==false)return finish("rejected","business_write_attempt_detected",null);if(raw.external_side_effect_requested!==false)return finish("rejected","external_side_effect_attempt_detected",null);
  if(!isFarmOsRecord(raw.reauthorization_evidence)||!hasExactFarmOsKeys(raw.reauthorization_evidence,REAUTH_KEYS)||raw.reauthorization_evidence.actor_type!=="human")return finish("rejected","reauthorization_missing",null);
  const r=raw as unknown as WorkPlanAssignmentRequest,required=r.operation_kind==="create_work_plan_draft"?"edit_work_plan":"assign_staff",memberId=candidate?.member_reference.reference_id??null;
  const fingerprint=computeWorkPlanRequestFingerprint(({...r,request_fingerprint:undefined} as unknown) as Omit<WorkPlanAssignmentRequest,"request_fingerprint">);if(fingerprint!==r.request_fingerprint)return finish("rejected","idempotency_conflict",null);
  const draftHash=computeWorkPlanDraftSnapshotHash(draft),candidateHash=candidate?computeAssignmentCandidateSnapshotHash(candidate):null;
  let authority:WorkPlanAssignmentAuthority|{state:"not_found"|"unknown"};try{authority=await timeout(input.authority_port.getAuthority({authority_evidence_ref:r.authority_evidence_ref,actor_id:r.requested_by,proposal_id:r.approved_proposal.proposal_id,work_plan_draft_id:draft.work_plan_draft_id,draft_snapshot_hash:draftHash,candidate_snapshot_hash:candidateHash,member_id:memberId,target_scope:scopeOf(draft.target_reference),expected_version:r.expected_version}));}catch{return finish("outcome_unknown","authority_unavailable",null,"missing",[finding("missing_evidence",draft,candidate,correlation)],true)}
  if("state" in authority)return finish("rejected","authority_unavailable",null,"missing",[finding("missing_evidence",draft,candidate,correlation)]);
  if(!authority.actor_active)return finish("rejected","actor_inactive",null,"mismatch");if(!authority.capabilities.includes(required))return finish("rejected","capability_missing",null,"mismatch",[finding("capability_mismatch",draft,candidate,correlation)]);
  if(authority.draft_snapshot_hash!==draftHash||authority.candidate_snapshot_hash!==candidateHash)return finish("rejected","authority_mismatch",null,"mismatch");
  const expectedScope=scopeOf(draft.target_reference);if(authority.scope!==expectedScope||r.reauthorization_evidence.scope!==expectedScope)return finish("rejected","scope_mismatch",null,"mismatch",[finding("scope_mismatch",draft,candidate,correlation)]);
  if(authority.policy_version!==FARM_OS_WORK_PLAN_POLICY_VERSION||r.reauthorization_evidence.policy_version!==authority.policy_version||r.reauthorization_evidence.actor_id!==authority.actor_id||r.reauthorization_evidence.capability!==required||r.reauthorization_evidence.authorization_result!=="authorized"||r.reauthorization_evidence.reauthorized_at!==authority.reauthorized_at||r.reauthorization_evidence.expires_at!==authority.expires_at)return finish("rejected","authority_mismatch",null,"mismatch");
  if(![r.reauthorization_evidence.authenticated_at,r.reauthorization_evidence.reauthorized_at,r.reauthorization_evidence.expires_at,authority.evidence_observed_at,authority.proposal_expires_at,authority.approval_expires_at].every(isCanonicalFarmOsIso)||Date.parse(r.reauthorization_evidence.authenticated_at)>Date.parse(r.reauthorization_evidence.reauthorized_at)||Date.parse(r.reauthorization_evidence.reauthorized_at)>Date.parse(r.requested_at)||Date.parse(r.reauthorization_evidence.expires_at)<=Date.parse(input.now)||Date.parse(authority.proposal_expires_at)<=Date.parse(input.now)||Date.parse(authority.approval_expires_at)<=Date.parse(input.now)||Date.parse(authority.evidence_observed_at)>Date.parse(input.now)||Date.parse(input.now)-Date.parse(authority.evidence_observed_at)>300_000)return finish("rejected","reauthorization_expired",null,"mismatch",[finding("stale_availability",draft,candidate,correlation)]);
  if(!authority.proposal_approved||authority.proposal_id!==draft.source_proposal_id||authority.proposal_expires_at!==r.approved_proposal.expires_at)return finish("rejected","proposal_not_approved",null,"mismatch");if(authority.approval_id!==draft.source_approval_id||authority.approved_by!==r.approval_evidence.decided_by||authority.approval_expires_at!==r.approval_evidence.expires_at)return finish("rejected","authority_mismatch",null,"mismatch");
  if(!authority.target_known)return finish("rejected","target_unknown",null,"mismatch");if(r.expected_version!==draft.expected_version||authority.target_version!==r.expected_version)return finish("rejected","stale_expected_version",null,"mismatch");
  if(candidate){if(candidate.work_plan_draft_id!==draft.work_plan_draft_id)return finish("rejected","assignment_candidate_invalid",null,"mismatch");if(!authority.member_known||authority.member_id!==memberId)return finish("rejected","member_unknown",null,"mismatch");if(!authority.member_active)return finish("rejected","member_inactive",null,"mismatch");if(!authority.participation_active)return finish("rejected","participation_inactive",null,"mismatch");if(authority.availability==="unknown"||candidate.availability_status==="unknown")return finish("rejected","availability_unknown",null,"mismatch",[finding("missing_evidence",draft,candidate,correlation)]);if(authority.availability==="unavailable"||candidate.availability_status==="unavailable")return finish("rejected","member_unavailable",null,"mismatch");if(candidate.conflict_status==="unknown")return finish("rejected","evidence_stale",null,"mismatch",[finding("missing_evidence",draft,candidate,correlation)]);if(authority.member_scope!==candidate.scope||candidate.scope!==expectedScope)return finish("rejected","scope_mismatch",null,"mismatch",[finding("scope_mismatch",draft,candidate,correlation)]);if(hashFarmOsContract([...authority.required_capabilities].sort())!==hashFarmOsContract([...candidate.required_capabilities].sort())||!candidate.required_capabilities.every(c=>authority.member_capabilities.includes(c))||!candidate.required_capabilities.every(c=>candidate.matched_capabilities.includes(c)))return finish("rejected","capability_mismatch",null,"mismatch",[finding("capability_mismatch",draft,candidate,correlation)]);if(authority.time_overlap||candidate.conflict_status==="time_overlap")return finish("rejected","time_overlap",null,"mismatch",[finding("duplicate_assignment_risk",draft,candidate,correlation)]);if(authority.duplicate_assignment||candidate.conflict_status==="duplicate_assignment")return finish("rejected","duplicate_assignment",null,"mismatch",[finding("duplicate_assignment_risk",draft,candidate,correlation)]);if(authority.workload_minutes+candidate.estimated_duration_minutes>authority.workload_limit_minutes||candidate.conflict_status==="workload_exceeded")return finish("rejected","workload_exceeded",null,"mismatch",[finding("workload_conflict",draft,candidate,correlation)]);}
  const reservation=input.store.reserve({key:r.idempotency_key,fingerprint,proposal:r.approved_proposal.proposal_id,approval:r.approval_evidence.approval_id,assignment:memberId?`${draft.work_plan_draft_id}:${memberId}`:null});
  if(reservation==="conflict")return finish("rejected","idempotency_conflict",null,"authorized");if(reservation==="duplicate_draft")return finish("rejected","duplicate_draft",null,"authorized");if(reservation==="approval_reused")return finish("rejected","approval_reused",null,"authorized");if(reservation==="duplicate_assignment")return finish("rejected","duplicate_assignment",null,"authorized");
  if(reservation==="replay"){const replay=input.store.replay(r.idempotency_key)!;const replayed={...replay,result:"already_processed" as const,audit:{...replay.audit,result:"already_processed" as const,processed_at:input.now}};input.store.record(replayed.audit);return replayed}
  const command:WorkPlanCommandDraft={schema_version:FARM_OS_WORK_PLAN_COMMAND_DRAFT_SCHEMA_VERSION,command_id:`command_${hashFarmOsContract({request_id:r.request_id}).slice(7,31)}`,proposal_id:draft.source_proposal_id,approval_id:draft.source_approval_id,command_type:r.operation_kind,target_system:"farming_app_server_boundary",target_reference:draft.target_reference,idempotency_key:r.idempotency_key,requested_by:r.requested_by,approved_by:r.approval_evidence.decided_by,expected_version:r.expected_version,payload:{work_plan_draft_id:draft.work_plan_draft_id,assignment_candidate_id:candidate?.assignment_candidate_id??null},status:"draft",correlation_id:r.correlation_id,created_at:input.now,expires_at:draft.expires_at,original_command_id:null,supersedes_command_id:null,compensation_for_command_id:null,audit_ref:`audit_${hashFarmOsContract({request_id:r.request_id,correlation:r.correlation_id}).slice(7,31)}`};
  const outcome={result:"draft_ready",rejection_code:null,command_draft:command,audit:baseAudit("draft_ready",null,"authorized"),findings:[]} satisfies WorkPlanAssignmentOutcome;input.store.commit({key:r.idempotency_key,fingerprint,proposal:r.approved_proposal.proposal_id,approval:r.approval_evidence.approval_id,assignment:memberId?`${draft.work_plan_draft_id}:${memberId}`:null,outcome});return outcome;
}

export function parseWorkPlanCommandDraft(value:unknown):WorkPlanCommandDraft|null{
  if(!isFarmOsRecord(value)||!hasExactFarmOsKeys(value,["schema_version","command_id","proposal_id","approval_id","command_type","target_system","target_reference","idempotency_key","requested_by","approved_by","expected_version","payload","status","correlation_id","created_at","expires_at","original_command_id","supersedes_command_id","compensation_for_command_id","audit_ref"])||value.schema_version!==FARM_OS_WORK_PLAN_COMMAND_DRAFT_SCHEMA_VERSION||!FARM_OS_WORK_PLAN_GENERATABLE_COMMAND_TYPES.includes(value.command_type as never)||value.target_system!=="farming_app_server_boundary"||value.status!=="draft"||!parseFarmOsTypedContextReference(value.target_reference)||![value.command_id,value.proposal_id,value.approval_id,value.idempotency_key,value.requested_by,value.approved_by,value.correlation_id,value.audit_ref].every(isFarmOsIdentifier)||!positive(value.expected_version)||!isCanonicalFarmOsIso(value.created_at)||!isCanonicalFarmOsIso(value.expires_at)||Date.parse(value.expires_at as string)<=Date.parse(value.created_at as string)||!isFarmOsRecord(value.payload)||!hasExactFarmOsKeys(value.payload,["work_plan_draft_id","assignment_candidate_id"])||!isFarmOsIdentifier(value.payload.work_plan_draft_id)||!(value.payload.assignment_candidate_id===null||isFarmOsIdentifier(value.payload.assignment_candidate_id))||![value.original_command_id,value.supersedes_command_id,value.compensation_for_command_id].every(item=>item===null||isFarmOsIdentifier(item)))return null;
  return value as unknown as WorkPlanCommandDraft;
}
