import { parseFarmOsApprovedCommand,type FarmOsApprovedCommand } from "./farm_os_approved_command_contract";
import { hasExactFarmOsKeys,isCanonicalFarmOsIso,isFarmOsDigest,isFarmOsIdentifier,isFarmOsRecord,parseFarmOsDuplicateAwareJson } from "./farm_os_approved_proposal_contract";
import { resolveFarmOsCommandClass } from "./farm_os_command_registry";
import { resolveFarmOsExecutionAdapter } from "./farm_os_execution_adapter_registry";
import { executeFarmOsFakeAdapter,type FarmOsFakeAdapterMode,type FarmOsFakeAdapterRequest,type FarmOsFakeAdapterResult } from "./farm_os_fake_execution_adapter";
import { FARM_OS_COMMAND_TRANSITION_TABLE,transitionFarmOsCommand,type FarmOsCommandStateRecord } from "./farm_os_execution_gateway_state_machine";
import { FARM_OS_EXECUTION_GATEWAY_REQUEST_SCHEMA_VERSION,FARM_OS_EXECUTION_GATEWAY_RESULT_SCHEMA_VERSION,FARM_OS_EXECUTION_GATEWAY_VERSION,type FarmOsExecutionGatewayRequest,type FarmOsExecutionGatewayResult } from "./farm_os_execution_gateway_contract";

export const FARM_OS_GATEWAY_REQUEST_MAX_AGE_MS=5*60*1000;
export const FARM_OS_COMMAND_MAX_AGE_MS=5*60*1000;
export const FARM_OS_GATEWAY_REJECTION_CODES=["GATEWAY_REQUEST_SCHEMA_INVALID","GATEWAY_REQUEST_EXPIRED","COMMAND_EXPIRED","APPROVED_COMMAND_INVALID","COMMAND_CLASS_UNKNOWN","COMMAND_TARGET_NOT_ALLOWED","COMMAND_HASH_MISMATCH","PROPOSAL_HASH_MISMATCH","TRACE_INVALID","CORRELATION_MISMATCH","REAUTHENTICATION_EXPIRED","REAUTHENTICATION_INVALID","EXPECTED_STATE_MISMATCH","STATE_VERSION_MISMATCH","INVALID_STATE_TRANSITION","ADAPTER_NOT_FOUND","ADAPTER_NOT_ALLOWED","ADAPTER_SCHEMA_INVALID","DUPLICATE_GATEWAY_REQUEST","DUPLICATE_COMMAND_EXECUTION","FAKE_ADAPTER_FAILURE","COMPENSATION_REQUIRED","BUSINESS_WRITE_FORBIDDEN","EXTERNAL_EXECUTION_FORBIDDEN","UNKNOWN_FIELD","DUPLICATE_FIELD"] as const;
export type FarmOsGatewayRejectionCode=(typeof FARM_OS_GATEWAY_REJECTION_CODES)[number];
export type FarmOsGatewayValidationResult={valid:true;request:FarmOsExecutionGatewayRequest;blocked_reason:null}|{valid:false;request:null;blocked_reason:FarmOsGatewayRejectionCode};
export type FarmOsGatewayMemory={gateway_request_ids:Set<string>;command_ids:Set<string>;command_hashes:Set<string>;approval_ids:Set<string>;adapter_request_ids:Set<string>};
export const createFarmOsGatewayMemory=():FarmOsGatewayMemory=>({gateway_request_ids:new Set(),command_ids:new Set(),command_hashes:new Set(),approval_ids:new Set(),adapter_request_ids:new Set()});
const REQUEST_KEYS=["schema_version","gateway_request_id","approved_command","requested_at","request_actor","correlation_id","expected_command_hash","expected_proposal_hash","expected_command_state","gateway_version"] as const;
const mapCommandError=(reason:string):FarmOsGatewayRejectionCode=>reason==="PROPOSAL_HASH_INVALID"?"PROPOSAL_HASH_MISMATCH":reason.startsWith("REAUTHENTICATION")||reason.startsWith("FINAL_CONFIRMATION")?(reason==="REAUTHENTICATION_EVIDENCE_INVALID"?"REAUTHENTICATION_EXPIRED":"REAUTHENTICATION_INVALID"):"APPROVED_COMMAND_INVALID";
export function parseFarmOsExecutionGatewayRequest(value:unknown):FarmOsGatewayValidationResult{
  if(!isFarmOsRecord(value))return{valid:false,request:null,blocked_reason:"GATEWAY_REQUEST_SCHEMA_INVALID"};
  if(!hasExactFarmOsKeys(value,REQUEST_KEYS))return{valid:false,request:null,blocked_reason:"UNKNOWN_FIELD"};
  if(value.schema_version!==FARM_OS_EXECUTION_GATEWAY_REQUEST_SCHEMA_VERSION||value.gateway_version!==FARM_OS_EXECUTION_GATEWAY_VERSION||value.request_actor!=="execution_gateway"||!isFarmOsIdentifier(value.gateway_request_id)||!isCanonicalFarmOsIso(value.requested_at)||!isFarmOsIdentifier(value.correlation_id)||!isFarmOsDigest(value.expected_command_hash)||!isFarmOsDigest(value.expected_proposal_hash))return{valid:false,request:null,blocked_reason:"GATEWAY_REQUEST_SCHEMA_INVALID"};
  if(value.expected_command_state!=="requested")return{valid:false,request:null,blocked_reason:"EXPECTED_STATE_MISMATCH"};
  const command=parseFarmOsApprovedCommand(value.approved_command);if(!command.valid)return{valid:false,request:null,blocked_reason:mapCommandError(command.blocked_reason)};
  const requested=Date.parse(value.requested_at as string),built=Date.parse(command.value.audit.built_at),evaluated=Date.now();if(evaluated<built||evaluated-built>FARM_OS_COMMAND_MAX_AGE_MS)return{valid:false,request:null,blocked_reason:"COMMAND_EXPIRED"};if(requested<built||requested>evaluated||evaluated-requested>FARM_OS_GATEWAY_REQUEST_MAX_AGE_MS)return{valid:false,request:null,blocked_reason:"GATEWAY_REQUEST_EXPIRED"};
  if(command.value.idempotency.command_hash!==value.expected_command_hash)return{valid:false,request:null,blocked_reason:"COMMAND_HASH_MISMATCH"};
  if(command.value.proposal_reference.proposal_hash!==value.expected_proposal_hash)return{valid:false,request:null,blocked_reason:"PROPOSAL_HASH_MISMATCH"};
  if(command.value.trace.correlation_id!==value.correlation_id)return{valid:false,request:null,blocked_reason:"CORRELATION_MISMATCH"};
  if(!resolveFarmOsCommandClass(command.value.command_class))return{valid:false,request:null,blocked_reason:"COMMAND_CLASS_UNKNOWN"};
  return{valid:true,request:value as unknown as FarmOsExecutionGatewayRequest,blocked_reason:null};
}
export function parseFarmOsExecutionGatewayRequestJson(text:unknown):FarmOsGatewayValidationResult{
  const raw=parseFarmOsDuplicateAwareJson(text);if(!raw.valid)return{valid:false,request:null,blocked_reason:raw.blocked_reason==="DUPLICATE_FIELD"?"DUPLICATE_FIELD":"GATEWAY_REQUEST_SCHEMA_INVALID"};return parseFarmOsExecutionGatewayRequest(raw.value);
}
const traceFor=(request:FarmOsExecutionGatewayRequest,adapterRequestId:string|null,adapterResult:FarmOsFakeAdapterResult|null)=>({proposal_id:request.approved_command.proposal_reference.proposal_id,approval_id:request.approved_command.proposal_reference.approval_id,command_id:request.approved_command.command_id,gateway_request_id:request.gateway_request_id,adapter_request_id:adapterRequestId,adapter_result_id:adapterResult?.adapter_result_id??null,request_id:request.approved_command.trace.request_id,correlation_id:request.correlation_id,source_event_hash:request.approved_command.trace.source_event_hash,proposal_hash:request.approved_command.proposal_reference.proposal_hash,command_hash:request.approved_command.idempotency.command_hash});
const blockedResult=(request:unknown,reason:FarmOsGatewayRejectionCode,now:string):FarmOsExecutionGatewayResult=>{const parsed=parseFarmOsExecutionGatewayRequest(request),candidate=parsed.valid?parsed.request:null;return{schema_version:FARM_OS_EXECUTION_GATEWAY_RESULT_SCHEMA_VERSION,gateway_request_id:candidate?.gateway_request_id??"gateway_request_blocked",command_id:candidate?.approved_command.command_id??"command_blocked",result:"blocked",error:reason,gateway_version:FARM_OS_EXECUTION_GATEWAY_VERSION,state_records:[],adapter_result:null,audit:{recorded_at:now,execution_is_business_fact:false},trace:candidate?traceFor(candidate,null,null):{proposal_id:"proposal_blocked",approval_id:"approval_blocked",command_id:"command_blocked",gateway_request_id:"gateway_request_blocked",adapter_request_id:null,adapter_result_id:null,request_id:"request_blocked",correlation_id:"correlation_blocked",source_event_hash:`sha256:${"0".repeat(64)}`,proposal_hash:`sha256:${"0".repeat(64)}`,command_hash:`sha256:${"0".repeat(64)}`}};};
const next=(record:FarmOsCommandStateRecord,to:Parameters<typeof transitionFarmOsCommand>[0]["to"],event:Parameters<typeof transitionFarmOsCommand>[0]["event"],command:FarmOsApprovedCommand,now:string,adapterResultReference:string|null=null)=>transitionFarmOsCommand({record,to,event,expected_state_version:record.state_version,command_class:command.command_class,risk_level:command.risk_level,transitioned_at:now,adapter_result_reference:adapterResultReference});
export function executeFarmOsExecutionGateway(input:{request:unknown;memory:FarmOsGatewayMemory;fake_mode:FarmOsFakeAdapterMode}):FarmOsExecutionGatewayResult{
  const now=new Date().toISOString();const validation=parseFarmOsExecutionGatewayRequest(input.request);if(!validation.valid)return blockedResult(input.request,validation.blocked_reason,now);const request=validation.request,command=request.approved_command;
  if(input.memory.gateway_request_ids.has(request.gateway_request_id))return blockedResult(request,"DUPLICATE_GATEWAY_REQUEST",now);
  if(input.memory.command_ids.has(command.command_id)||input.memory.command_hashes.has(command.idempotency.command_hash)||input.memory.approval_ids.has(command.proposal_reference.approval_id))return blockedResult(request,"DUPLICATE_COMMAND_EXECUTION",now);
  const payloadSchema=command.execution_payload.schema_version;const adapter=resolveFarmOsExecutionAdapter({command_class:command.command_class,execution_target:command.execution_target,payload_schema:payloadSchema,risk_level:command.risk_level});if(!adapter)return blockedResult(request,"ADAPTER_NOT_ALLOWED",now);
  if(!adapter.fake_only||adapter.business_write_allowed)return blockedResult(request,"BUSINESS_WRITE_FORBIDDEN",now);if(adapter.external_execution_allowed)return blockedResult(request,"EXTERNAL_EXECUTION_FORBIDDEN",now);
  const adapterRequestId=`adapter_request_${command.command_id.slice(8)}`;if(input.memory.adapter_request_ids.has(adapterRequestId))return blockedResult(request,"DUPLICATE_COMMAND_EXECUTION",now);
  input.memory.gateway_request_ids.add(request.gateway_request_id);input.memory.command_ids.add(command.command_id);input.memory.command_hashes.add(command.idempotency.command_hash);input.memory.approval_ids.add(command.proposal_reference.approval_id);input.memory.adapter_request_ids.add(adapterRequestId);
  const records:FarmOsCommandStateRecord[]=[];let record:FarmOsCommandStateRecord={command_id:command.command_id,gateway_request_id:request.gateway_request_id,state:"requested",state_version:1,previous_state:null,transition_event:null,transitioned_at:request.requested_at,gateway_version:FARM_OS_EXECUTION_GATEWAY_VERSION,adapter_id:null,adapter_result_reference:null,trace:{proposal_id:command.proposal_reference.proposal_id,approval_id:command.proposal_reference.approval_id,request_id:command.trace.request_id,correlation_id:command.trace.correlation_id,source_event_hash:command.trace.source_event_hash,proposal_hash:command.proposal_reference.proposal_hash,command_hash:command.idempotency.command_hash},audit:{transition_recorded:true,business_write_performed:false}};records.push(record);
  for(const [to,event] of [["approved","request_validated"],["executing","execution_started"]] as const){const transitioned=next(record,to,event,command,now);if(!transitioned.valid)return blockedResult(request,transitioned.blocked_reason,now);record=transitioned.record;records.push(record);}
  const adapterRequest:FarmOsFakeAdapterRequest={schema_version:"farmos.fake.adapter.request.v1",adapter_request_id:adapterRequestId,gateway_request_id:request.gateway_request_id,command_id:command.command_id,proposal_id:command.proposal_reference.proposal_id,command_class:command.command_class,command_hash:command.idempotency.command_hash,execution_target:command.execution_target,execution_payload:command.execution_payload,trace:{proposal_id:command.proposal_reference.proposal_id,approval_id:command.proposal_reference.approval_id,command_id:command.command_id,gateway_request_id:request.gateway_request_id,request_id:command.trace.request_id,correlation_id:command.trace.correlation_id,source_event_hash:command.trace.source_event_hash,proposal_hash:command.proposal_reference.proposal_hash,command_hash:command.idempotency.command_hash},requested_at:now};
  const adapterResult=executeFarmOsFakeAdapter(adapterRequest,input.fake_mode,now);if(!adapterResult)return blockedResult(request,"ADAPTER_SCHEMA_INVALID",now);
  const outcome=adapterResult.result==="success"?next(record,"succeeded","adapter_succeeded",command,now,adapterResult.adapter_result_id):next(record,"failed","adapter_failed",command,now,adapterResult.adapter_result_id);if(!outcome.valid)return blockedResult(request,outcome.blocked_reason,now);record=outcome.record;records.push(record);
  if(adapterResult.result==="compensation_required"){const compensation=next(record,"compensation_required","compensation_requested",command,now,adapterResult.adapter_result_id);if(!compensation.valid)return blockedResult(request,compensation.blocked_reason,now);record=compensation.record;records.push(record);}
  return{schema_version:FARM_OS_EXECUTION_GATEWAY_RESULT_SCHEMA_VERSION,gateway_request_id:request.gateway_request_id,command_id:command.command_id,result:adapterResult.result==="success"?"succeeded":adapterResult.result==="failure"?"failed":"compensation_required",error:adapterResult.error,gateway_version:FARM_OS_EXECUTION_GATEWAY_VERSION,state_records:records,adapter_result:adapterResult,audit:{recorded_at:now,execution_is_business_fact:false},trace:traceFor(request,adapterRequestId,adapterResult)};
}
export const FARM_OS_GATEWAY_TRANSITION_COUNT=FARM_OS_COMMAND_TRANSITION_TABLE.length;
