import { hashFarmOsContract,hasExactFarmOsKeys,isCanonicalFarmOsIso,isFarmOsDigest,isFarmOsIdentifier,isFarmOsRecord,parseFarmOsDuplicateAwareJson } from "./farm_os_approved_proposal_contract";
import type { FarmOsApprovedCommand } from "./farm_os_approved_command_contract";
import type { FarmOsExecutionGatewayRequest,FarmOsExecutionGatewayResult } from "./farm_os_execution_gateway_contract";
import { parseFarmOsExecutionGatewayResult } from "./farm_os_execution_gateway_result_validator";
import type { FarmOsCommandClass,FarmOsCommandTarget } from "./farm_os_command_registry";

export const FARM_OS_EXECUTION_RESERVATION_SCHEMA_VERSION="farmos.execution.reservation.v1" as const;
export const FARM_OS_EXECUTION_RESERVATION_REQUEST_SCHEMA_VERSION="farmos.execution.reservation.request.v1" as const;
export const FARM_OS_RESERVATION_LEASE_DURATION_MS=60_000 as const;
export const FARM_OS_RESERVATION_STATES=["reserved","claimed","executing","completed","failed","expired","released"] as const;
export type FarmOsExecutionReservationState=(typeof FARM_OS_RESERVATION_STATES)[number];
export type FarmOsCommandIdentity={command_id:string;command_hash:string;proposal_id:string;proposal_hash:string;approval_id:string;idempotency_key:string;execution_target:FarmOsCommandTarget;command_class:FarmOsCommandClass;command_version:1};
export type FarmOsReservationTrace={proposal_id:string;approval_id:string;command_id:string;gateway_request_id:string;request_id:string;correlation_id:string;source_event_hash:string;proposal_hash:string;command_hash:string};
export type FarmOsExecutionReservationRequest={schema_version:typeof FARM_OS_EXECUTION_RESERVATION_REQUEST_SCHEMA_VERSION;gateway_request_id:string;command_identity:FarmOsCommandIdentity;expected_version:0;correlation_id:string;requested_at:string;trace:FarmOsReservationTrace};
export type FarmOsExecutionReservation={schema_version:typeof FARM_OS_EXECUTION_RESERVATION_SCHEMA_VERSION;reservation_id:string;gateway_request_id:string;command_id:string;command_hash:string;proposal_id:string;proposal_hash:string;approval_id:string;idempotency_key:string;expected_version:0;correlation_id:string;execution_target:FarmOsCommandTarget;command_class:FarmOsCommandClass;command_version:1;reservation_state:FarmOsExecutionReservationState;reservation_version:number;owner_token:string;claimed_at:string|null;expires_at:string;lease_expires_at:string;lease_duration_ms:typeof FARM_OS_RESERVATION_LEASE_DURATION_MS;completed_at:string|null;final_result:FarmOsExecutionGatewayResult|null;failure_code:string|null;created_at:string;updated_at:string;trace:FarmOsReservationTrace;audit:{server_owned_owner_token:true;business_write_performed:false;external_execution_performed:false;proposal_apply_performed:false}};
export type FarmOsReservationParseResult<T>={valid:true;value:T;blocked_reason:null}|{valid:false;value:null;blocked_reason:"RESERVATION_SCHEMA_INVALID"|"UNKNOWN_FIELD"|"DUPLICATE_FIELD"};

const IDENTITY_KEYS=["command_id","command_hash","proposal_id","proposal_hash","approval_id","idempotency_key","execution_target","command_class","command_version"] as const;
const REQUEST_KEYS=["schema_version","gateway_request_id","command_identity","expected_version","correlation_id","requested_at","trace"] as const;
const TRACE_KEYS=["proposal_id","approval_id","command_id","gateway_request_id","request_id","correlation_id","source_event_hash","proposal_hash","command_hash"] as const;
const RESERVATION_KEYS=["schema_version","reservation_id","gateway_request_id","command_id","command_hash","proposal_id","proposal_hash","approval_id","idempotency_key","expected_version","correlation_id","execution_target","command_class","command_version","reservation_state","reservation_version","owner_token","claimed_at","expires_at","lease_expires_at","lease_duration_ms","completed_at","final_result","failure_code","created_at","updated_at","trace","audit"] as const;
const traceValid=(value:unknown):value is FarmOsReservationTrace=>isFarmOsRecord(value)&&hasExactFarmOsKeys(value,TRACE_KEYS)&&[value.proposal_id,value.approval_id,value.command_id,value.gateway_request_id,value.request_id,value.correlation_id].every(isFarmOsIdentifier)&&[value.source_event_hash,value.proposal_hash,value.command_hash].every(isFarmOsDigest);
const storedResultValid=(value:unknown,reservation:Record<string,unknown>)=>{const parsed=parseFarmOsExecutionGatewayResult(value);return parsed!==null&&parsed.command_id===reservation.command_id&&parsed.gateway_request_id===reservation.gateway_request_id&&parsed.trace.proposal_id===reservation.proposal_id&&parsed.trace.approval_id===reservation.approval_id&&parsed.trace.correlation_id===reservation.correlation_id&&parsed.trace.proposal_hash===reservation.proposal_hash&&parsed.trace.command_hash===reservation.command_hash&&(reservation.reservation_state==="completed"?parsed.result==="succeeded":parsed.result==="failed"||parsed.result==="compensation_required");};
export function parseFarmOsExecutionReservationRequest(value:unknown):FarmOsReservationParseResult<FarmOsExecutionReservationRequest>{
  if(!isFarmOsRecord(value))return{valid:false,value:null,blocked_reason:"RESERVATION_SCHEMA_INVALID"};
  if(!hasExactFarmOsKeys(value,REQUEST_KEYS))return{valid:false,value:null,blocked_reason:"UNKNOWN_FIELD"};
  if(value.schema_version!==FARM_OS_EXECUTION_RESERVATION_REQUEST_SCHEMA_VERSION||!isFarmOsIdentifier(value.gateway_request_id)||value.expected_version!==0||!isFarmOsIdentifier(value.correlation_id)||!isCanonicalFarmOsIso(value.requested_at)||!isFarmOsRecord(value.command_identity)||!hasExactFarmOsKeys(value.command_identity,IDENTITY_KEYS)||!traceValid(value.trace))return{valid:false,value:null,blocked_reason:"RESERVATION_SCHEMA_INVALID"};
  const identity=value.command_identity;
  if(![identity.command_id,identity.proposal_id,identity.approval_id,identity.idempotency_key].every(isFarmOsIdentifier)||![identity.command_hash,identity.proposal_hash].every(isFarmOsDigest)||identity.command_version!==1||!(identity.command_class==="approved_internal_command"||identity.command_class==="approved_external_command")||!(identity.execution_target==="farmos_internal_contract"||identity.execution_target==="approved_external_contract"))return{valid:false,value:null,blocked_reason:"RESERVATION_SCHEMA_INVALID"};
  if(value.gateway_request_id!==value.trace.gateway_request_id||value.correlation_id!==value.trace.correlation_id||identity.command_id!==value.trace.command_id||identity.command_hash!==value.trace.command_hash||identity.proposal_id!==value.trace.proposal_id||identity.proposal_hash!==value.trace.proposal_hash||identity.approval_id!==value.trace.approval_id)return{valid:false,value:null,blocked_reason:"RESERVATION_SCHEMA_INVALID"};
  return{valid:true,value:value as unknown as FarmOsExecutionReservationRequest,blocked_reason:null};
}
export function parseFarmOsExecutionReservationRequestJson(text:unknown):FarmOsReservationParseResult<FarmOsExecutionReservationRequest>{const raw=parseFarmOsDuplicateAwareJson(text);if(!raw.valid)return{valid:false,value:null,blocked_reason:raw.blocked_reason==="DUPLICATE_FIELD"?"DUPLICATE_FIELD":"RESERVATION_SCHEMA_INVALID"};return parseFarmOsExecutionReservationRequest(raw.value);}
export function parseFarmOsExecutionReservation(value:unknown):FarmOsReservationParseResult<FarmOsExecutionReservation>{
  if(!isFarmOsRecord(value)||!hasExactFarmOsKeys(value,RESERVATION_KEYS))return{valid:false,value:null,blocked_reason:isFarmOsRecord(value)?"UNKNOWN_FIELD":"RESERVATION_SCHEMA_INVALID"};
  if(value.schema_version!==FARM_OS_EXECUTION_RESERVATION_SCHEMA_VERSION||![value.reservation_id,value.gateway_request_id,value.command_id,value.proposal_id,value.approval_id,value.idempotency_key,value.correlation_id,value.owner_token].every(isFarmOsIdentifier)||![value.command_hash,value.proposal_hash].every(isFarmOsDigest)||value.expected_version!==0||value.command_version!==1||!(value.command_class==="approved_internal_command"||value.command_class==="approved_external_command")||!(value.execution_target==="farmos_internal_contract"||value.execution_target==="approved_external_contract")||!FARM_OS_RESERVATION_STATES.includes(value.reservation_state as never)||!Number.isSafeInteger(value.reservation_version)||(value.reservation_version as number)<1||value.lease_duration_ms!==FARM_OS_RESERVATION_LEASE_DURATION_MS)return{valid:false,value:null,blocked_reason:"RESERVATION_SCHEMA_INVALID"};
  if((value.claimed_at!==null&&!isCanonicalFarmOsIso(value.claimed_at))||!isCanonicalFarmOsIso(value.expires_at)||!isCanonicalFarmOsIso(value.lease_expires_at)||(value.completed_at!==null&&!isCanonicalFarmOsIso(value.completed_at))||!isCanonicalFarmOsIso(value.created_at)||!isCanonicalFarmOsIso(value.updated_at)||Date.parse(value.updated_at as string)<Date.parse(value.created_at as string)||!traceValid(value.trace))return{valid:false,value:null,blocked_reason:"RESERVATION_SCHEMA_INVALID"};
  if(value.gateway_request_id!==value.trace.gateway_request_id||value.correlation_id!==value.trace.correlation_id||value.command_id!==value.trace.command_id||value.command_hash!==value.trace.command_hash||value.proposal_id!==value.trace.proposal_id||value.proposal_hash!==value.trace.proposal_hash||value.approval_id!==value.trace.approval_id)return{valid:false,value:null,blocked_reason:"RESERVATION_SCHEMA_INVALID"};
  if(!isFarmOsRecord(value.audit)||!hasExactFarmOsKeys(value.audit,["server_owned_owner_token","business_write_performed","external_execution_performed","proposal_apply_performed"])||value.audit.server_owned_owner_token!==true||value.audit.business_write_performed!==false||value.audit.external_execution_performed!==false||value.audit.proposal_apply_performed!==false||!(value.failure_code===null||typeof value.failure_code==="string"))return{valid:false,value:null,blocked_reason:"RESERVATION_SCHEMA_INVALID"};
  if((value.reservation_state==="completed"||value.reservation_state==="failed")&&(value.completed_at===null||!storedResultValid(value.final_result,value))||!(value.reservation_state==="completed"||value.reservation_state==="failed")&&value.final_result!==null)return{valid:false,value:null,blocked_reason:"RESERVATION_SCHEMA_INVALID"};
  return{valid:true,value:value as unknown as FarmOsExecutionReservation,blocked_reason:null};
}
export const computeFarmOsExecutionIdempotencyKey=(command:FarmOsApprovedCommand)=>`idempotency_${hashFarmOsContract({command_id:command.command_id,command_hash:command.idempotency.command_hash,proposal_id:command.proposal_reference.proposal_id,proposal_hash:command.proposal_reference.proposal_hash,approval_id:command.proposal_reference.approval_id,execution_target:command.execution_target,command_class:command.command_class,command_version:command.command_version}).slice(7,39)}`;
export function createFarmOsExecutionReservationRequest(gateway:FarmOsExecutionGatewayRequest):FarmOsExecutionReservationRequest{const command=gateway.approved_command;return{schema_version:FARM_OS_EXECUTION_RESERVATION_REQUEST_SCHEMA_VERSION,gateway_request_id:gateway.gateway_request_id,command_identity:{command_id:command.command_id,command_hash:command.idempotency.command_hash,proposal_id:command.proposal_reference.proposal_id,proposal_hash:command.proposal_reference.proposal_hash,approval_id:command.proposal_reference.approval_id,idempotency_key:computeFarmOsExecutionIdempotencyKey(command),execution_target:command.execution_target,command_class:command.command_class,command_version:command.command_version},expected_version:0,correlation_id:gateway.correlation_id,requested_at:gateway.requested_at,trace:{proposal_id:command.proposal_reference.proposal_id,approval_id:command.proposal_reference.approval_id,command_id:command.command_id,gateway_request_id:gateway.gateway_request_id,request_id:command.trace.request_id,correlation_id:gateway.correlation_id,source_event_hash:command.trace.source_event_hash,proposal_hash:command.proposal_reference.proposal_hash,command_hash:command.idempotency.command_hash}};}
