import { resolveFarmOsCommandClass,type FarmOsCommandClass } from "./farm_os_command_registry";
import type { FarmOsRiskLevel } from "./farm_os_risk_taxonomy";
import { hasExactFarmOsKeys,isCanonicalFarmOsIso,isFarmOsDigest,isFarmOsIdentifier,isFarmOsRecord } from "./farm_os_approved_proposal_contract";
export const FARM_OS_COMMAND_STATES=["requested","approved","executing","succeeded","failed","compensation_required","compensated"] as const;
export type FarmOsCommandState=(typeof FARM_OS_COMMAND_STATES)[number];
export const FARM_OS_COMMAND_TRANSITION_EVENTS=["request_validated","execution_started","adapter_succeeded","adapter_failed","compensation_requested","compensation_completed"] as const;
export type FarmOsCommandTransitionEvent=(typeof FARM_OS_COMMAND_TRANSITION_EVENTS)[number];
export type FarmOsCommandTransition={from:FarmOsCommandState;to:FarmOsCommandState;allowed_event:FarmOsCommandTransitionEvent;required_command_classes:readonly FarmOsCommandClass[];required_risk_levels:readonly Extract<FarmOsRiskLevel,"l2_internal_apply"|"l3_external_execution">[];audit_required:true;adapter_call_allowed:boolean;business_write_allowed:false};
const classes=["approved_internal_command","approved_external_command"] as const,risks=["l2_internal_apply","l3_external_execution"] as const;
export const FARM_OS_COMMAND_TRANSITION_TABLE:readonly FarmOsCommandTransition[]=[
  {from:"requested",to:"approved",allowed_event:"request_validated",required_command_classes:classes,required_risk_levels:risks,audit_required:true,adapter_call_allowed:false,business_write_allowed:false},
  {from:"approved",to:"executing",allowed_event:"execution_started",required_command_classes:classes,required_risk_levels:risks,audit_required:true,adapter_call_allowed:true,business_write_allowed:false},
  {from:"executing",to:"succeeded",allowed_event:"adapter_succeeded",required_command_classes:classes,required_risk_levels:risks,audit_required:true,adapter_call_allowed:true,business_write_allowed:false},
  {from:"executing",to:"failed",allowed_event:"adapter_failed",required_command_classes:classes,required_risk_levels:risks,audit_required:true,adapter_call_allowed:true,business_write_allowed:false},
  {from:"failed",to:"compensation_required",allowed_event:"compensation_requested",required_command_classes:classes,required_risk_levels:risks,audit_required:true,adapter_call_allowed:false,business_write_allowed:false},
  {from:"compensation_required",to:"compensated",allowed_event:"compensation_completed",required_command_classes:classes,required_risk_levels:risks,audit_required:true,adapter_call_allowed:false,business_write_allowed:false},
] as const;
export type FarmOsCommandStateRecord={command_id:string;gateway_request_id:string;state:FarmOsCommandState;state_version:number;previous_state:FarmOsCommandState|null;transition_event:FarmOsCommandTransitionEvent|null;transitioned_at:string;gateway_version:"farmos-execution-gateway-day133.v1";adapter_id:"fake_execution_adapter"|null;adapter_result_reference:string|null;trace:{proposal_id:string;approval_id:string;request_id:string;correlation_id:string;source_event_hash:string;proposal_hash:string;command_hash:string};audit:{transition_recorded:true;business_write_performed:false}};
export type FarmOsTransitionResult={valid:true;record:FarmOsCommandStateRecord;blocked_reason:null}|{valid:false;record:null;blocked_reason:"INVALID_STATE_TRANSITION"|"STATE_VERSION_MISMATCH"};
const RECORD_KEYS=["command_id","gateway_request_id","state","state_version","previous_state","transition_event","transitioned_at","gateway_version","adapter_id","adapter_result_reference","trace","audit"] as const;
const TRACE_KEYS=["proposal_id","approval_id","request_id","correlation_id","source_event_hash","proposal_hash","command_hash"] as const;
const recordValid=(value:unknown):value is FarmOsCommandStateRecord=>{
  if(!isFarmOsRecord(value)||!hasExactFarmOsKeys(value,RECORD_KEYS)||!isFarmOsIdentifier(value.command_id)||!isFarmOsIdentifier(value.gateway_request_id)||!FARM_OS_COMMAND_STATES.includes(value.state as FarmOsCommandState)||!Number.isSafeInteger(value.state_version)||(value.state_version as number)<1||!isCanonicalFarmOsIso(value.transitioned_at)||value.gateway_version!=="farmos-execution-gateway-day133.v1")return false;
  if(value.previous_state!==null&&!FARM_OS_COMMAND_STATES.includes(value.previous_state as FarmOsCommandState)||value.transition_event!==null&&!FARM_OS_COMMAND_TRANSITION_EVENTS.includes(value.transition_event as FarmOsCommandTransitionEvent)||value.adapter_id!==null&&value.adapter_id!=="fake_execution_adapter"||value.adapter_result_reference!==null&&!isFarmOsIdentifier(value.adapter_result_reference))return false;
  if(!isFarmOsRecord(value.trace)||!hasExactFarmOsKeys(value.trace,TRACE_KEYS)||!isFarmOsIdentifier(value.trace.proposal_id)||!isFarmOsIdentifier(value.trace.approval_id)||!isFarmOsIdentifier(value.trace.request_id)||!isFarmOsIdentifier(value.trace.correlation_id)||!isFarmOsDigest(value.trace.source_event_hash)||!isFarmOsDigest(value.trace.proposal_hash)||!isFarmOsDigest(value.trace.command_hash))return false;
  return isFarmOsRecord(value.audit)&&hasExactFarmOsKeys(value.audit,["transition_recorded","business_write_performed"])&&value.audit.transition_recorded===true&&value.audit.business_write_performed===false;
};
export function transitionFarmOsCommand(input:{record:FarmOsCommandStateRecord;to:FarmOsCommandState;event:FarmOsCommandTransitionEvent;expected_state_version:number;command_class:FarmOsCommandClass;risk_level:Extract<FarmOsRiskLevel,"l2_internal_apply"|"l3_external_execution">;transitioned_at:string;adapter_result_reference?:string|null}):FarmOsTransitionResult{
  if(!recordValid(input.record)||!Number.isSafeInteger(input.expected_state_version)||(input.expected_state_version as number)<1)return{valid:false,record:null,blocked_reason:"INVALID_STATE_TRANSITION"};
  if(input.record.state_version!==input.expected_state_version)return{valid:false,record:null,blocked_reason:"STATE_VERSION_MISMATCH"};
  const registry=resolveFarmOsCommandClass(input.command_class);if(!registry||registry.required_risk_level!==input.risk_level)return{valid:false,record:null,blocked_reason:"INVALID_STATE_TRANSITION"};
  const trace=input.record.trace;if(!isCanonicalFarmOsIso(input.transitioned_at)||Date.parse(input.transitioned_at)<Date.parse(input.record.transitioned_at)||!isFarmOsIdentifier(trace.proposal_id)||!isFarmOsIdentifier(trace.approval_id)||!isFarmOsIdentifier(trace.request_id)||!isFarmOsIdentifier(trace.correlation_id)||!isFarmOsDigest(trace.source_event_hash)||!isFarmOsDigest(trace.proposal_hash)||!isFarmOsDigest(trace.command_hash))return{valid:false,record:null,blocked_reason:"INVALID_STATE_TRANSITION"};
  const rule=FARM_OS_COMMAND_TRANSITION_TABLE.find((entry)=>entry.from===input.record.state&&entry.to===input.to&&entry.allowed_event===input.event);
  if(!rule||!rule.required_command_classes.includes(input.command_class)||!rule.required_risk_levels.includes(input.risk_level))return{valid:false,record:null,blocked_reason:"INVALID_STATE_TRANSITION"};
  return{valid:true,blocked_reason:null,record:{...input.record,state:input.to,state_version:input.record.state_version+1,previous_state:input.record.state,transition_event:input.event,transitioned_at:input.transitioned_at,adapter_id:rule.adapter_call_allowed?"fake_execution_adapter":input.record.adapter_id,adapter_result_reference:input.adapter_result_reference??input.record.adapter_result_reference,audit:{transition_recorded:true,business_write_performed:false}}};
}
