import { hashFarmOsContract,isCanonicalFarmOsIso } from "./farm_os_approved_proposal_contract";
import { FARM_OS_EXECUTION_RESERVATION_SCHEMA_VERSION,FARM_OS_RESERVATION_LEASE_DURATION_MS,parseFarmOsExecutionReservationRequest,type FarmOsExecutionReservation,type FarmOsExecutionReservationRequest } from "./farm_os_execution_reservation_contract";
import { canTransitionFarmOsReservation } from "./farm_os_execution_reservation_state_machine";
import type { FarmOsExecutionReservationPort,FarmOsReservationLookup,FarmOsReservationPortResult,FarmOsReservationRejectionCode } from "./farm_os_execution_reservation_port";
import type { FarmOsExecutionGatewayResult } from "./farm_os_execution_gateway_contract";
import { parseFarmOsExecutionGatewayResult } from "./farm_os_execution_gateway_result_validator";

export type FarmOsReservationRepositoryCounters={reservation_request_count:number;reservation_candidate_count:number;max_concurrent_reservation_candidates:number;reservation_created_count:number;reservation_existing_count:number;reservation_claim_attempt_count:number;reservation_claim_success_count:number;reservation_claim_conflict_count:number;reservation_finalize_count:number;reservation_expired_count:number;reservation_released_count:number};
const clone=<T>(value:T):T=>structuredClone(value);
const rejected=(reason:FarmOsReservationRejectionCode,record:FarmOsExecutionReservation|null=null):FarmOsReservationPortResult=>({status:"rejected",record:record?clone(record):null,reason});
const identityEqual=(record:FarmOsExecutionReservation,request:FarmOsExecutionReservationRequest)=>record.command_id===request.command_identity.command_id&&record.command_hash===request.command_identity.command_hash&&record.proposal_id===request.command_identity.proposal_id&&record.proposal_hash===request.command_identity.proposal_hash&&record.approval_id===request.command_identity.approval_id&&record.idempotency_key===request.command_identity.idempotency_key&&record.execution_target===request.command_identity.execution_target&&record.command_class===request.command_identity.command_class&&record.command_version===request.command_identity.command_version;

export class FarmOsInMemoryExecutionReservationRepository implements FarmOsExecutionReservationPort{
  readonly counters:FarmOsReservationRepositoryCounters={reservation_request_count:0,reservation_candidate_count:0,max_concurrent_reservation_candidates:0,reservation_created_count:0,reservation_existing_count:0,reservation_claim_attempt_count:0,reservation_claim_success_count:0,reservation_claim_conflict_count:0,reservation_finalize_count:0,reservation_expired_count:0,reservation_released_count:0};
  private activeReservationCandidates=0;
  private readonly records=new Map<string,FarmOsExecutionReservation>();
  private readonly indexes={gateway_request_id:new Map<string,string>(),command_id:new Map<string,string>(),command_hash:new Map<string,string>(),approval_id:new Map<string,string>(),idempotency_key:new Map<string,string>()};
  private by(index:keyof typeof this.indexes,value:string){const id=this.indexes[index].get(value);return id?this.records.get(id)??null:null;}
  async lookup(input:FarmOsReservationLookup){const entries=Object.entries(input).filter(([,value])=>typeof value==="string") as [keyof FarmOsReservationLookup,string][];if(entries.length!==1)return null;const [key,value]=entries[0];if(key==="reservation_id")return clone(this.records.get(value)??null);if(!(key in this.indexes))return null;return clone(this.by(key as keyof typeof this.indexes,value));}
  async tryReserve(input:{request:FarmOsExecutionReservationRequest;now:string}):Promise<FarmOsReservationPortResult>{
    this.counters.reservation_request_count+=1;this.counters.reservation_candidate_count+=1;this.activeReservationCandidates+=1;this.counters.max_concurrent_reservation_candidates=Math.max(this.counters.max_concurrent_reservation_candidates,this.activeReservationCandidates);await Promise.resolve();try{const parsed=parseFarmOsExecutionReservationRequest(input.request);if(!parsed.valid||!isCanonicalFarmOsIso(input.now)||Date.parse(input.now)<Date.parse(input.request.requested_at))return rejected("RESERVATION_SCHEMA_INVALID");const request=parsed.value;
    const probes:[[keyof typeof this.indexes,string],[keyof typeof this.indexes,string],[keyof typeof this.indexes,string],[keyof typeof this.indexes,string],[keyof typeof this.indexes,string]]=[["gateway_request_id",request.gateway_request_id],["command_id",request.command_identity.command_id],["command_hash",request.command_identity.command_hash],["approval_id",request.command_identity.approval_id],["idempotency_key",request.command_identity.idempotency_key]];
    for(const [index,value] of probes){const existing=this.by(index,value);if(!existing)continue;if(identityEqual(existing,request)&&existing.gateway_request_id===request.gateway_request_id){this.counters.reservation_existing_count+=1;return{status:"existing",record:clone(existing),reason:"RESERVATION_ALREADY_EXISTS"};}const reason:FarmOsReservationRejectionCode=index==="gateway_request_id"?"DUPLICATE_GATEWAY_REQUEST":index==="approval_id"?"APPROVAL_REUSE_DETECTED":index==="idempotency_key"?"DUPLICATE_IDEMPOTENCY_KEY":"COMMAND_IDENTITY_MISMATCH";return rejected(reason,existing);}
    const material={gateway_request_id:request.gateway_request_id,...request.command_identity},reservation_id=`reservation_${hashFarmOsContract(material).slice(7,39)}`,owner_token=`owner_${hashFarmOsContract({material,scope:"gateway_internal_owner"}).slice(7,39)}`,expires_at=new Date(Date.parse(input.now)+FARM_OS_RESERVATION_LEASE_DURATION_MS).toISOString();
    const record:FarmOsExecutionReservation={schema_version:FARM_OS_EXECUTION_RESERVATION_SCHEMA_VERSION,reservation_id,gateway_request_id:request.gateway_request_id,command_id:request.command_identity.command_id,command_hash:request.command_identity.command_hash,proposal_id:request.command_identity.proposal_id,proposal_hash:request.command_identity.proposal_hash,approval_id:request.command_identity.approval_id,idempotency_key:request.command_identity.idempotency_key,expected_version:0,correlation_id:request.correlation_id,execution_target:request.command_identity.execution_target,command_class:request.command_identity.command_class,command_version:request.command_identity.command_version,reservation_state:"reserved",reservation_version:1,owner_token,claimed_at:null,expires_at,lease_expires_at:expires_at,lease_duration_ms:FARM_OS_RESERVATION_LEASE_DURATION_MS,completed_at:null,final_result:null,failure_code:null,created_at:input.now,updated_at:input.now,trace:request.trace,audit:{server_owned_owner_token:true,business_write_performed:false,external_execution_performed:false,proposal_apply_performed:false}};
    if(this.records.has(reservation_id))return rejected("ATOMIC_RESERVATION_CONFLICT",this.records.get(reservation_id)??null);this.records.set(reservation_id,record);for(const [index,value] of probes)this.indexes[index].set(value,reservation_id);this.counters.reservation_created_count+=1;return{status:"created",record:clone(record),reason:null};}finally{this.activeReservationCandidates-=1;}
  }
  private transition(input:{reservation_id:string;expected_reservation_version:number;owner_token:string|null;now:string;to:FarmOsExecutionReservation["reservation_state"];event:"claim"|"start_execution"|"expire"|"release"}){const current=this.records.get(input.reservation_id);if(!current)return rejected("RESERVATION_NOT_FOUND");const decision=canTransitionFarmOsReservation({record:current,to:input.to,event:input.event,expected_reservation_version:input.expected_reservation_version,owner_token:input.owner_token,now:input.now});if(!decision.allowed)return rejected(decision.reason,current);if((input.event==="claim"||input.event==="start_execution")&&Date.parse(input.now)>Date.parse(current.lease_expires_at))return rejected("RESERVATION_EXPIRED",current);if(input.event==="expire"&&Date.parse(input.now)<=Date.parse(current.lease_expires_at))return rejected("RESERVATION_SCHEMA_INVALID",current);const recoveryOwner=input.event==="expire"?`owner_recovery_${hashFarmOsContract({reservation_id:current.reservation_id,reservation_version:current.reservation_version+1,expired_at:input.now}).slice(7,39)}`:current.owner_token;const updated:FarmOsExecutionReservation={...current,reservation_state:input.to,reservation_version:current.reservation_version+1,owner_token:recoveryOwner,claimed_at:input.event==="claim"?input.now:current.claimed_at,lease_expires_at:input.event==="claim"?new Date(Date.parse(input.now)+current.lease_duration_ms).toISOString():current.lease_expires_at,updated_at:input.now};this.records.set(updated.reservation_id,updated);return{status:input.to,record:clone(updated),reason:null} as FarmOsReservationPortResult;}
  async tryClaim(input:{reservation_id:string;expected_reservation_version:number;owner_token:string;now:string}){this.counters.reservation_claim_attempt_count+=1;const result=this.transition({...input,to:"claimed",event:"claim"});if(result.status==="claimed")this.counters.reservation_claim_success_count+=1;else this.counters.reservation_claim_conflict_count+=1;return result;}
  async tryStart(input:{reservation_id:string;expected_reservation_version:number;owner_token:string;now:string}){return this.transition({...input,to:"executing",event:"start_execution"});}
  async tryFinalize(input:{reservation_id:string;expected_reservation_version:number;owner_token:string;result:FarmOsExecutionGatewayResult;now:string}):Promise<FarmOsReservationPortResult>{this.counters.reservation_finalize_count+=1;const current=this.records.get(input.reservation_id);if(!current)return rejected("RESERVATION_NOT_FOUND");if(current.reservation_state==="completed")return rejected("RESERVATION_ALREADY_COMPLETED",current);if(current.reservation_state!=="executing"||current.reservation_version!==input.expected_reservation_version)return rejected("RESERVATION_VERSION_MISMATCH",current);if(current.owner_token!==input.owner_token)return rejected("RESERVATION_OWNER_MISMATCH",current);if(!isCanonicalFarmOsIso(input.now)||Date.parse(input.now)>Date.parse(current.lease_expires_at))return rejected("RESERVATION_EXPIRED",current);if(parseFarmOsExecutionGatewayResult(input.result)===null||Date.parse(input.now)<Date.parse(current.updated_at)||input.result.command_id!==current.command_id||input.result.gateway_request_id!==current.gateway_request_id||input.result.trace.command_hash!==current.command_hash||input.result.trace.proposal_hash!==current.proposal_hash||input.result.trace.approval_id!==current.approval_id)return rejected("RESERVATION_FINALIZATION_FAILED",current);const completed=input.result.result==="succeeded",state:Extract<FarmOsExecutionReservation["reservation_state"],"completed"|"failed">=completed?"completed":"failed",updated:FarmOsExecutionReservation={...current,reservation_state:state,reservation_version:current.reservation_version+1,completed_at:input.now,final_result:clone(input.result),failure_code:completed?null:input.result.error??"FAKE_ADAPTER_FAILURE",updated_at:input.now};this.records.set(updated.reservation_id,updated);return{status:state,record:clone(updated),reason:null};}
  async tryExpire(input:{reservation_id:string;expected_reservation_version:number;now:string}){const result=this.transition({...input,owner_token:null,to:"expired",event:"expire"});if(result.status==="expired")this.counters.reservation_expired_count+=1;return result;}
  async tryRelease(input:{reservation_id:string;expected_reservation_version:number;owner_token:string;now:string}){const result=this.transition({...input,to:"released",event:"release"});if(result.status==="released")this.counters.reservation_released_count+=1;return result;}
  snapshot(){return[...this.records.values()].map(clone);}
}
