import { hashFarmOsContract,hasExactFarmOsKeys,isCanonicalFarmOsIso,isFarmOsDigest,isFarmOsIdentifier,isFarmOsRecord } from "./farm_os_approved_proposal_contract";
import { resolveFarmOsExecutionAdapter } from "./farm_os_execution_adapter_registry";
import type { FarmOsCommandClass,FarmOsCommandPayload,FarmOsCommandTarget } from "./farm_os_command_registry";
export const FARM_OS_FAKE_ADAPTER_MODES=["fake_success","fake_failure","fake_compensation_required"] as const;
export type FarmOsFakeAdapterMode=(typeof FARM_OS_FAKE_ADAPTER_MODES)[number];
export type FarmOsFakeAdapterTrace={proposal_id:string;approval_id:string;command_id:string;gateway_request_id:string;request_id:string;correlation_id:string;source_event_hash:string;proposal_hash:string;command_hash:string};
export type FarmOsFakeAdapterRequest={schema_version:"farmos.fake.adapter.request.v1";adapter_request_id:string;gateway_request_id:string;command_id:string;proposal_id:string;command_class:FarmOsCommandClass;command_hash:string;execution_target:FarmOsCommandTarget;execution_payload:FarmOsCommandPayload;trace:FarmOsFakeAdapterTrace;requested_at:string};
export type FarmOsFakeAdapterResult={schema_version:"farmos.fake.adapter.result.v1";adapter_result_id:string;adapter_id:"fake_execution_adapter";result:"success"|"failure"|"compensation_required";error:"FAKE_ADAPTER_FAILURE"|"COMPENSATION_REQUIRED"|null;started_at:string;completed_at:string;business_write_performed:false;external_execution_performed:false;trace:FarmOsFakeAdapterRequest["trace"]};
const KEYS=["schema_version","adapter_request_id","gateway_request_id","command_id","proposal_id","command_class","command_hash","execution_target","execution_payload","trace","requested_at"] as const;
const TRACE_KEYS=["proposal_id","approval_id","command_id","gateway_request_id","request_id","correlation_id","source_event_hash","proposal_hash","command_hash"] as const;
export function executeFarmOsFakeAdapter(request:unknown,mode:FarmOsFakeAdapterMode,completedAt:string):FarmOsFakeAdapterResult|null{
  if(!isFarmOsRecord(request)||!hasExactFarmOsKeys(request,KEYS)||request.schema_version!=="farmos.fake.adapter.request.v1"||!isFarmOsIdentifier(request.adapter_request_id)||!isFarmOsIdentifier(request.gateway_request_id)||!isFarmOsIdentifier(request.command_id)||!isFarmOsIdentifier(request.proposal_id)||!isFarmOsDigest(request.command_hash)||!isCanonicalFarmOsIso(request.requested_at)||!isCanonicalFarmOsIso(completedAt)||!FARM_OS_FAKE_ADAPTER_MODES.includes(mode))return null;
  if(!isFarmOsRecord(request.execution_payload)||!hasExactFarmOsKeys(request.execution_payload,["schema_version","operation","proposal_id"])||!isFarmOsRecord(request.trace)||!hasExactFarmOsKeys(request.trace,TRACE_KEYS)||!isFarmOsIdentifier(request.trace.proposal_id)||!isFarmOsIdentifier(request.trace.approval_id)||!isFarmOsIdentifier(request.trace.command_id)||!isFarmOsIdentifier(request.trace.gateway_request_id)||!isFarmOsIdentifier(request.trace.request_id)||!isFarmOsIdentifier(request.trace.correlation_id)||!isFarmOsDigest(request.trace.source_event_hash)||!isFarmOsDigest(request.trace.proposal_hash)||!isFarmOsDigest(request.trace.command_hash)||request.trace.proposal_id!==request.proposal_id||request.trace.command_id!==request.command_id||request.trace.gateway_request_id!==request.gateway_request_id||request.trace.command_hash!==request.command_hash||Date.parse(completedAt)<Date.parse(request.requested_at as string))return null;
  const payloadMatches=request.execution_payload.proposal_id===request.proposal_id&&(request.command_class==="approved_internal_command"?request.execution_payload.schema_version==="farmos.command.payload.work_log_follow_up.v1"&&request.execution_payload.operation==="prepare_work_log_follow_up":request.command_class==="approved_external_command"&&request.execution_payload.schema_version==="farmos.command.payload.external_reservation.v1"&&request.execution_payload.operation==="reserve_external_execution_contract");if(!payloadMatches)return null;
  const entry=resolveFarmOsExecutionAdapter({command_class:request.command_class,execution_target:request.execution_target,payload_schema:request.execution_payload.schema_version,risk_level:request.command_class==="approved_internal_command"?"l2_internal_apply":"l3_external_execution"});if(!entry)return null;
  const result=mode==="fake_success"?"success":mode==="fake_failure"?"failure":"compensation_required";
  return{schema_version:"farmos.fake.adapter.result.v1",adapter_result_id:`adapter_result_${hashFarmOsContract({adapter_request_id:request.adapter_request_id,mode}).slice(7,39)}`,adapter_id:entry.adapter_id,result,error:result==="success"?null:result==="failure"?"FAKE_ADAPTER_FAILURE":"COMPENSATION_REQUIRED",started_at:request.requested_at as string,completed_at:completedAt,business_write_performed:false,external_execution_performed:false,trace:request.trace as FarmOsFakeAdapterRequest["trace"]};
}
