import { isCanonicalFarmOsIso } from "./farm_os_approved_proposal_contract";
import { parseFarmOsExecutionReservation,type FarmOsExecutionReservation,type FarmOsExecutionReservationState } from "./farm_os_execution_reservation_contract";
export const FARM_OS_RESERVATION_EVENTS=["reserve","claim","start_execution","complete","fail","expire","release"] as const;
export type FarmOsReservationEvent=(typeof FARM_OS_RESERVATION_EVENTS)[number];
export type FarmOsReservationTransition={from:"unreserved"|FarmOsExecutionReservationState;to:FarmOsExecutionReservationState;event:FarmOsReservationEvent;required_version:"compare_and_set";owner_required:boolean;command_identity_required:true;audit_required:true;business_write_allowed:false;external_execution_allowed:false};
export const FARM_OS_RESERVATION_TRANSITION_TABLE:readonly FarmOsReservationTransition[]=[
  {from:"unreserved",to:"reserved",event:"reserve",required_version:"compare_and_set",owner_required:false,command_identity_required:true,audit_required:true,business_write_allowed:false,external_execution_allowed:false},
  {from:"reserved",to:"claimed",event:"claim",required_version:"compare_and_set",owner_required:true,command_identity_required:true,audit_required:true,business_write_allowed:false,external_execution_allowed:false},
  {from:"claimed",to:"executing",event:"start_execution",required_version:"compare_and_set",owner_required:true,command_identity_required:true,audit_required:true,business_write_allowed:false,external_execution_allowed:false},
  {from:"executing",to:"completed",event:"complete",required_version:"compare_and_set",owner_required:true,command_identity_required:true,audit_required:true,business_write_allowed:false,external_execution_allowed:false},
  {from:"executing",to:"failed",event:"fail",required_version:"compare_and_set",owner_required:true,command_identity_required:true,audit_required:true,business_write_allowed:false,external_execution_allowed:false},
  {from:"reserved",to:"expired",event:"expire",required_version:"compare_and_set",owner_required:false,command_identity_required:true,audit_required:true,business_write_allowed:false,external_execution_allowed:false},
  {from:"claimed",to:"expired",event:"expire",required_version:"compare_and_set",owner_required:false,command_identity_required:true,audit_required:true,business_write_allowed:false,external_execution_allowed:false},
  {from:"executing",to:"expired",event:"expire",required_version:"compare_and_set",owner_required:false,command_identity_required:true,audit_required:true,business_write_allowed:false,external_execution_allowed:false},
  {from:"failed",to:"released",event:"release",required_version:"compare_and_set",owner_required:true,command_identity_required:true,audit_required:true,business_write_allowed:false,external_execution_allowed:false},
  {from:"expired",to:"released",event:"release",required_version:"compare_and_set",owner_required:true,command_identity_required:true,audit_required:true,business_write_allowed:false,external_execution_allowed:false},
] as const;
export function canTransitionFarmOsReservation(input:{record:FarmOsExecutionReservation;to:FarmOsExecutionReservationState;event:FarmOsReservationEvent;expected_reservation_version:number;owner_token:string|null;now:string}){if(!parseFarmOsExecutionReservation(input.record).valid)return{allowed:false as const,reason:"RESERVATION_SCHEMA_INVALID" as const};if(!Number.isSafeInteger(input.expected_reservation_version)||input.expected_reservation_version<1||input.record.reservation_version!==input.expected_reservation_version)return{allowed:false as const,reason:"RESERVATION_VERSION_MISMATCH" as const};if(!isCanonicalFarmOsIso(input.now)||Date.parse(input.now)<Date.parse(input.record.updated_at))return{allowed:false as const,reason:"RESERVATION_SCHEMA_INVALID" as const};const rule=FARM_OS_RESERVATION_TRANSITION_TABLE.find((entry)=>entry.from===input.record.reservation_state&&entry.to===input.to&&entry.event===input.event);if(!rule)return{allowed:false as const,reason:"INVALID_RESERVATION_TRANSITION" as const};if(rule.owner_required&&input.owner_token!==input.record.owner_token)return{allowed:false as const,reason:"RESERVATION_OWNER_MISMATCH" as const};return{allowed:true as const,rule};}
