import { hashFarmOsContract, hasExactFarmOsKeys, isCanonicalFarmOsIso, isFarmOsDigest, isFarmOsIdentifier, isFarmOsRecord } from "./farm_os_approved_proposal_contract";
import { parseConfirmationTaskDraft, type ConfirmationTaskDraft } from "./farm_os_confirmation_task_apply_contract";
import { parseFarmOsLowRiskSafeReference, type FarmOsLowRiskSafeReference } from "./farm_os_low_risk_candidate_contract";

export const FARM_OS_CONFIRMATION_TASK_PERSISTENCE_SCHEMA_VERSION = "farmos.confirmation-task-persistence.v1" as const;
export const FARM_OS_CONFIRMATION_TASK_CANCELLATION_SCHEMA_VERSION = "farmos.confirmation-task-cancellation.v1" as const;
export const FARM_OS_CONFIRMATION_TASK_RECORD_SCHEMA_VERSION = "farmos.confirmation-task-record.v1" as const;
export const FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION = "confirmation-task-persistence-policy.v1" as const;
export const FARM_OS_CONFIRMATION_TASK_REJECTION_CODES = ["task_draft_missing","task_draft_invalid","task_draft_not_draft","task_draft_expired","task_draft_hash_mismatch","candidate_link_mismatch","approval_link_mismatch","approval_reuse_rejected","authority_missing","authority_mismatch","reauthorization_missing","reauthorization_expired","actor_inactive","capability_not_allowed","scope_mismatch","policy_version_stale","dry_run_required","idempotency_conflict","duplicate_persistence_rejected","duplicate_cancellation_rejected","task_not_found","task_not_open","task_already_cancelled","task_status_not_cancellable","version_conflict","cancellation_reason_invalid","audit_correlation_mismatch","business_write_attempt_detected","external_side_effect_attempt_detected","unknown_field"] as const;
export type ConfirmationTaskPersistenceRejectionCode = (typeof FARM_OS_CONFIRMATION_TASK_REJECTION_CODES)[number];
export type ConfirmationTaskOperationResult = "dry_run_ready" | "already_processed" | "rejected";

export const FARM_OS_CONFIRMATION_TASK_PERSISTENCE_REGISTRY = {
  persistence: { operation_kind:"confirmation_task_persist",source_schema:"farmos.confirmation-task-draft.v1",target_schema:FARM_OS_CONFIRMATION_TASK_RECORD_SCHEMA_VERSION,required_capability:"persist_confirmation_task",approval_required:true,reauthorization_required:true,authority_port_required:true,idempotency_required:true,optimistic_concurrency_required:true,dry_run_only:true,business_write_allowed:false,external_side_effect_allowed:false,rollback_mode:"discard_reference_record" },
  cancellation: { operation_kind:"confirmation_task_cancel",source_schema:FARM_OS_CONFIRMATION_TASK_RECORD_SCHEMA_VERSION,target_schema:FARM_OS_CONFIRMATION_TASK_RECORD_SCHEMA_VERSION,required_capability:"cancel_confirmation_task",approval_required:false,reauthorization_required:true,authority_port_required:true,idempotency_required:true,optimistic_concurrency_required:true,dry_run_only:true,business_write_allowed:false,external_side_effect_allowed:false,rollback_mode:"retain_open_state" },
} as const;

export type ConfirmationTaskPersistenceAuthority = {
  actor_id:string; actor_active:true; capability:"persist_confirmation_task"; scope:string; policy_version:typeof FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION;
  reauthorized_at:string; expires_at:string; approval_id:string; candidate_id:string; task_draft_id:string; source:"human_review_ledger"|"authorization_service"|"current_membership_projection"|"current_policy_registry";
};
export type ConfirmationTaskPersistenceRuntimeContext={actor_active:true;target_scope:string;current_policy_version:typeof FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION};
export type ConfirmationTaskPersistenceReauthorizationEvidence={actor_id:string;actor_type:"human";capability:"persist_confirmation_task"|"cancel_confirmation_task";scope:string;actor_status:"active";authenticated_at:string;reauthorized_at:string;expires_at:string;policy_version:typeof FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION;authorization_result:"authorized";temporary_exception_present:false};
export type ConfirmationTaskCancellationAuthority = {
  actor_id:string; actor_active:true; capability:"cancel_confirmation_task"; scope:string; policy_version:typeof FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION;
  reauthorized_at:string; expires_at:string; task_id:string;approval_id:string;candidate_id:string;task_draft_id:string; source:"authorization_service"|"current_membership_projection"|"current_policy_registry";
};
export interface ConfirmationTaskPersistenceAuthorityPort {
  getPersistenceAuthority(input:{authority_evidence_ref:string;task_draft_id:string;actor_id:string}):Promise<ConfirmationTaskPersistenceAuthority|{state:"not_found"|"unknown"}>;
  getCancellationAuthority(input:{authority_evidence_ref:string;task_id:string;actor_id:string}):Promise<ConfirmationTaskCancellationAuthority|{state:"not_found"|"unknown"}>;
}
export type ConfirmationTaskPersistenceRequest = {
  schema_version:typeof FARM_OS_CONFIRMATION_TASK_PERSISTENCE_SCHEMA_VERSION;persistence_request_id:string;task_draft:ConfirmationTaskDraft;task_draft_snapshot_hash:string;
  source_candidate_id:string;source_approval_id:string;requested_by:string;requested_at:string;runtime_context:ConfirmationTaskPersistenceRuntimeContext;
  reauthorization_evidence:ConfirmationTaskPersistenceReauthorizationEvidence;authority_evidence_ref:string;idempotency_key:string;request_fingerprint:string;
  correlation_id:string;causation_id:string;agent_run_id:string;dry_run:true;
};
export type ConfirmationTaskCancellationRequest = {
  schema_version:typeof FARM_OS_CONFIRMATION_TASK_CANCELLATION_SCHEMA_VERSION;cancellation_request_id:string;task_id:string;expected_task_version:number;reason:string;
  requested_by:string;requested_at:string;runtime_context:ConfirmationTaskPersistenceRuntimeContext;reauthorization_evidence:ConfirmationTaskPersistenceReauthorizationEvidence;
  authority_evidence_ref:string;idempotency_key:string;correlation_id:string;causation_id:string;dry_run:true;
};
export type ConfirmationTaskRecord = {
  schema_version:typeof FARM_OS_CONFIRMATION_TASK_RECORD_SCHEMA_VERSION;task_id:string;source_task_draft_id:string;source_candidate_id:string;source_approval_id:string;
  task_type:"human_confirmation";question:string;reason:string;confirmation_type:ConfirmationTaskDraft["confirmation_type"];target_reference:FarmOsLowRiskSafeReference;
  requested_by_date:string;blocking_hint:boolean;status:"open"|"cancelled";created_by_actor:string;created_at:string;updated_at:string;version:number;
  cancellation_state:"not_cancelled"|"cancelled";audit_ref:string;
};
export type ConfirmationTaskOperationEnvelope = {
  schema_version:typeof FARM_OS_CONFIRMATION_TASK_PERSISTENCE_SCHEMA_VERSION|typeof FARM_OS_CONFIRMATION_TASK_CANCELLATION_SCHEMA_VERSION;
  request_id:string;operation_kind:"confirmation_task_persist"|"confirmation_task_cancel";result:ConfirmationTaskOperationResult;rejection_code:ConfirmationTaskPersistenceRejectionCode|null;
  task_ref:string|null;idempotency_status:"created"|"replayed"|"rejected";dry_run:true;correlation_id:string;processed_at:string;
  business_write_performed:false;external_side_effect_performed:false;
};
export type ConfirmationTaskOperationAudit = {
  request_id:string;operation_kind:"confirmation_task_persist"|"confirmation_task_cancel";task_draft_id:string|null;task_draft_snapshot_hash:string|null;task_id:string|null;
  expected_task_version:number|null;observed_task_version:number|null;candidate_id:string|null;approval_id:string|null;request_actor:string;capability:string;scope:string;
  authority_result:"authorized"|"missing"|"mismatch";reauthorization_result:"authorized"|"rejected";idempotency_key_hash:string;request_fingerprint:string;
  operation_result:ConfirmationTaskOperationResult;rejection_code:ConfirmationTaskPersistenceRejectionCode|null;task_ref:string|null;dry_run:true;correlation_id:string;causation_id:string;
  processed_at:string;business_write_attempted:boolean;business_write_performed:false;external_side_effect_attempted:boolean;external_side_effect_performed:false;physical_delete_count:0;
};
export type ConfirmationTaskOperationOutcome = {result:ConfirmationTaskOperationEnvelope;audit:ConfirmationTaskOperationAudit;record:ConfirmationTaskRecord|null;evolution:{record_kind:"confirmation_task_persistence_quality";automatic_policy_adoption:false;automatic_skill_adoption:false;automatic_capability_expansion:false;automatic_risk_downgrade:false;automatic_production_enablement:false;automatic_ui_enablement:false}};

const PERSIST_KEYS=["schema_version","persistence_request_id","task_draft","task_draft_snapshot_hash","source_candidate_id","source_approval_id","requested_by","requested_at","runtime_context","reauthorization_evidence","authority_evidence_ref","idempotency_key","request_fingerprint","correlation_id","causation_id","agent_run_id","dry_run"] as const;
const CANCEL_KEYS=["schema_version","cancellation_request_id","task_id","expected_task_version","reason","requested_by","requested_at","runtime_context","reauthorization_evidence","authority_evidence_ref","idempotency_key","correlation_id","causation_id","dry_run"] as const;
const RUNTIME_KEYS=["actor_active","target_scope","current_policy_version"] as const,REAUTH_KEYS=["actor_id","actor_type","capability","scope","actor_status","authenticated_at","reauthorized_at","expires_at","policy_version","authorization_result","temporary_exception_present"] as const;
const safeReason=(v:unknown)=>typeof v==="string"&&v.length>=3&&v.length<=500&&!/[\u0000-\u001f\u007f<>]/u.test(v);
const scopeOf=(ref:FarmOsLowRiskSafeReference)=>`${ref.source_system}:${ref.reference_type}:${ref.reference_id}:${ref.reference_version}`;
export const computeConfirmationTaskDraftSnapshotHash=(draft:ConfirmationTaskDraft)=>hashFarmOsContract({schema_version:draft.schema_version,task_draft_id:draft.task_draft_id,source_candidate_id:draft.source_candidate_id,task_type:draft.task_type,question:draft.question,reason:draft.reason,confirmation_type:draft.confirmation_type,target_reference:draft.target_reference,requested_by_date:draft.requested_by_date,blocking_hint:draft.blocking_hint,status:draft.status,created_from_approval_id:draft.created_from_approval_id,created_by_actor:draft.created_by_actor,created_at:draft.created_at,expires_at:draft.expires_at});
export const computeConfirmationTaskPersistenceFingerprint=(r:Omit<ConfirmationTaskPersistenceRequest,"request_fingerprint">)=>hashFarmOsContract({operation_kind:"confirmation_task_persist",task_draft_id:r.task_draft.task_draft_id,task_draft_snapshot_hash:r.task_draft_snapshot_hash,source_approval_id:r.source_approval_id,actor_id:r.requested_by,target_scope:scopeOf(r.task_draft.target_reference),runtime_context:r.runtime_context,reauthorization_evidence:r.reauthorization_evidence,correlation_id:r.correlation_id,causation_id:r.causation_id,agent_run_id:r.agent_run_id,requested_at:r.requested_at,dry_run:r.dry_run});
export const computeConfirmationTaskCancellationFingerprint=(r:ConfirmationTaskCancellationRequest,scope:string)=>hashFarmOsContract({operation_kind:"confirmation_task_cancel",task_id:r.task_id,expected_task_version:r.expected_task_version,actor_id:r.requested_by,target_scope:scope,runtime_context:r.runtime_context,reauthorization_evidence:r.reauthorization_evidence,correlation_id:r.correlation_id,causation_id:r.causation_id,requested_at:r.requested_at,dry_run:r.dry_run});

type Stored={fingerprint:string;result:ConfirmationTaskOperationEnvelope;audit:ConfirmationTaskOperationAudit};
export class InMemoryConfirmationTaskReferenceRepository {
  private readonly tasks=new Map<string,ConfirmationTaskRecord>();private readonly byDraft=new Map<string,string>();private readonly byApproval=new Map<string,string>();
  private readonly persistKeys=new Map<string,Stored>();private readonly cancelKeys=new Map<string,Stored>();private readonly cancelledTask=new Set<string>();
  readonly counters={persistence_reservation_count:0,cancellation_reservation_count:0,reference_task_save_count:0,reference_cancel_count:0,physical_delete_count:0,business_write_count:0,external_side_effect_count:0};
  private readonly auditLog:ConfirmationTaskOperationAudit[]=[];appendAudit(audit:ConfirmationTaskOperationAudit){this.auditLog.push(structuredClone(audit));}readAudit(){return structuredClone(this.auditLog);}
  reservePersistence(key:string,fingerprint:string,draftId:string,approvalId:string){this.counters.persistence_reservation_count++;const e=this.persistKeys.get(key);if(e)return e.fingerprint===fingerprint?"replay":"conflict";if(this.byDraft.has(draftId))return"duplicate";if(this.byApproval.has(approvalId))return"approval_reuse";return"new";}
  saveReferenceTask(key:string,fingerprint:string,record:ConfirmationTaskRecord,result:ConfirmationTaskOperationEnvelope,audit:ConfirmationTaskOperationAudit){this.tasks.set(record.task_id,structuredClone(record));this.byDraft.set(record.source_task_draft_id,record.task_id);this.byApproval.set(record.source_approval_id,record.task_id);this.persistKeys.set(key,{fingerprint,result,audit});this.counters.reference_task_save_count++;}
  readByTaskDraftId(id:string){const task=this.byDraft.get(id);return task?this.readTask(task):null;}readTask(id:string){const r=this.tasks.get(id);return r?structuredClone(r):null;}readPersistence(key:string){const value=this.persistKeys.get(key);return value?structuredClone(value):null;}
  reserveCancellation(key:string,fingerprint:string,taskId:string){this.counters.cancellation_reservation_count++;const e=this.cancelKeys.get(key);if(e)return e.fingerprint===fingerprint?"replay":"conflict";if(this.cancelledTask.has(taskId))return"duplicate";return"new";}
  cancelReferenceTask(key:string,fingerprint:string,taskId:string,expected:number,now:string,result:ConfirmationTaskOperationEnvelope,audit:ConfirmationTaskOperationAudit){const current=this.tasks.get(taskId);if(!current)return{status:"not_found" as const,record:null};if(current.version!==expected)return{status:"version_conflict" as const,record:structuredClone(current)};if(current.status!=="open")return{status:current.status==="cancelled"?"already_cancelled" as const:"not_open" as const,record:structuredClone(current)};const updated={...current,status:"cancelled" as const,cancellation_state:"cancelled" as const,version:current.version+1,updated_at:now};this.tasks.set(taskId,updated);this.cancelledTask.add(taskId);this.cancelKeys.set(key,{fingerprint,result,audit});this.counters.reference_cancel_count++;return{status:"cancelled" as const,record:structuredClone(updated)};}
  readCancellation(key:string){const value=this.cancelKeys.get(key);return value?structuredClone(value):null;}seed(record:ConfirmationTaskRecord){this.tasks.set(record.task_id,structuredClone(record));this.byDraft.set(record.source_task_draft_id,record.task_id);this.byApproval.set(record.source_approval_id,record.task_id);}
}

const evo={record_kind:"confirmation_task_persistence_quality" as const,automatic_policy_adoption:false as const,automatic_skill_adoption:false as const,automatic_capability_expansion:false as const,automatic_risk_downgrade:false as const,automatic_production_enablement:false as const,automatic_ui_enablement:false as const};
function outcome(input:{schema:ConfirmationTaskOperationEnvelope["schema_version"];requestId:string;operation:ConfirmationTaskOperationEnvelope["operation_kind"];code:ConfirmationTaskPersistenceRejectionCode|null;taskRef:string|null;idempotency:"created"|"replayed"|"rejected";idempotencyKey?:string;correlation:string;causation:string;now:string;draft?:ConfirmationTaskDraft;hash?:string;task?:ConfirmationTaskRecord|null;actor?:string;capability?:string;scope?:string;authority?:"authorized"|"missing"|"mismatch";fingerprint?:string;expected?:number|null;observed?:number|null;businessAttempt?:boolean;externalAttempt?:boolean}):ConfirmationTaskOperationOutcome{
  const resultValue:ConfirmationTaskOperationResult=input.code?"rejected":input.idempotency==="replayed"?"already_processed":"dry_run_ready";
  const result:ConfirmationTaskOperationEnvelope={schema_version:input.schema,request_id:input.requestId,operation_kind:input.operation,result:resultValue,rejection_code:input.code,task_ref:input.taskRef,idempotency_status:input.idempotency,dry_run:true,correlation_id:input.correlation,processed_at:input.now,business_write_performed:false,external_side_effect_performed:false};
  const audit:ConfirmationTaskOperationAudit={request_id:input.requestId,operation_kind:input.operation,task_draft_id:input.draft?.task_draft_id??null,task_draft_snapshot_hash:input.hash??null,task_id:input.task?.task_id??input.taskRef,expected_task_version:input.expected??null,observed_task_version:input.observed??input.task?.version??null,candidate_id:input.draft?.source_candidate_id??null,approval_id:input.draft?.created_from_approval_id??null,request_actor:input.actor??"",capability:input.capability??"",scope:input.scope??"",authority_result:input.authority??"missing",reauthorization_result:input.authority==="authorized"?"authorized":"rejected",idempotency_key_hash:hashFarmOsContract({idempotency_key:input.idempotencyKey??""}),request_fingerprint:input.fingerprint??hashFarmOsContract({invalid:true}),operation_result:resultValue,rejection_code:input.code,task_ref:input.taskRef,dry_run:true,correlation_id:input.correlation,causation_id:input.causation,processed_at:input.now,business_write_attempted:input.businessAttempt===true,business_write_performed:false,external_side_effect_attempted:input.externalAttempt===true,external_side_effect_performed:false,physical_delete_count:0};
  return{result,audit,record:input.task??null,evolution:evo};
}
const authorityTimesValid=(a:{reauthorized_at:string;expires_at:string},requested:string,now:string,authenticatedAt:string)=>[a.reauthorized_at,a.expires_at,authenticatedAt].every(isCanonicalFarmOsIso)&&Date.parse(authenticatedAt)<=Date.parse(a.reauthorized_at)&&Date.parse(authenticatedAt)<=Date.parse(now)&&Date.parse(a.reauthorized_at)<=Date.parse(requested)&&Date.parse(a.reauthorized_at)<=Date.parse(now)&&Date.parse(a.expires_at)>Date.parse(now);
const requestAuthorityMatches=(runtime:ConfirmationTaskPersistenceRuntimeContext,reauth:ConfirmationTaskPersistenceReauthorizationEvidence,authority:{actor_id:string;actor_active:true;capability:string;scope:string;policy_version:string;reauthorized_at:string;expires_at:string})=>
  runtime.actor_active===authority.actor_active&&runtime.target_scope===authority.scope&&runtime.current_policy_version===authority.policy_version&&reauth.actor_id===authority.actor_id&&reauth.actor_status==="active"&&reauth.actor_type==="human"&&reauth.authorization_result==="authorized"&&reauth.temporary_exception_present===false&&reauth.capability===authority.capability&&reauth.scope===authority.scope&&reauth.policy_version===authority.policy_version&&reauth.reauthorized_at===authority.reauthorized_at&&reauth.expires_at===authority.expires_at;
const requestEvidenceValid=(runtime:unknown,reauth:unknown)=>isFarmOsRecord(runtime)&&hasExactFarmOsKeys(runtime,RUNTIME_KEYS)&&isFarmOsRecord(reauth)&&hasExactFarmOsKeys(reauth,REAUTH_KEYS);
const withAuthorityTimeout=<T>(operation:Promise<T>)=>new Promise<T>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("authority_timeout")),100);operation.then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})});

export async function simulateConfirmationTaskPersistence(input:{request:unknown;authority_port:ConfirmationTaskPersistenceAuthorityPort;repository:InMemoryConfirmationTaskReferenceRepository;now:string}):Promise<ConfirmationTaskOperationOutcome>{
  const raw=isFarmOsRecord(input.request)?input.request:{};const base={schema:FARM_OS_CONFIRMATION_TASK_PERSISTENCE_SCHEMA_VERSION,requestId:String(raw.persistence_request_id??"persistence_rejected"),operation:"confirmation_task_persist" as const,taskRef:null,correlation:String(raw.correlation_id??"correlation_rejected"),causation:String(raw.causation_id??""),now:input.now};
  const finalize=(o:ConfirmationTaskOperationOutcome)=>{input.repository.appendAudit(o.audit);return o},fail=(code:ConfirmationTaskPersistenceRejectionCode,extra={})=>finalize(outcome({...base,code,idempotency:"rejected",idempotencyKey:String(raw.idempotency_key??""),businessAttempt:raw.business_write_attempt===true,externalAttempt:raw.external_side_effect_attempt===true,...extra}));
  if(raw.business_write_attempt===true)return fail("business_write_attempt_detected");if(raw.external_side_effect_attempt===true)return fail("external_side_effect_attempt_detected");
  if(!isFarmOsRecord(input.request)||!hasExactFarmOsKeys(input.request,PERSIST_KEYS))return fail("unknown_field");const r=input.request as unknown as ConfirmationTaskPersistenceRequest;
  if(r.schema_version!==FARM_OS_CONFIRMATION_TASK_PERSISTENCE_SCHEMA_VERSION||![r.persistence_request_id,r.source_candidate_id,r.source_approval_id,r.requested_by,r.authority_evidence_ref,r.idempotency_key,r.correlation_id,r.causation_id,r.agent_run_id].every(isFarmOsIdentifier))return fail("unknown_field");if(r.dry_run!==true)return fail("dry_run_required");if(r.task_draft===null||r.task_draft===undefined)return fail("task_draft_missing");if(!requestEvidenceValid(r.runtime_context,r.reauthorization_evidence))return fail(r.reauthorization_evidence?"unknown_field":"reauthorization_missing");if(!parseConfirmationTaskDraft(r.task_draft))return fail(isFarmOsRecord(r.task_draft)&&r.task_draft.status!=="draft"?"task_draft_not_draft":"task_draft_invalid");
  const draft=r.task_draft,scope=scopeOf(draft.target_reference),hash=computeConfirmationTaskDraftSnapshotHash(draft),extra={draft,hash,actor:r.requested_by,capability:"persist_confirmation_task",scope,fingerprint:r.request_fingerprint};
  if(Date.parse(draft.expires_at)<=Date.parse(input.now))return fail("task_draft_expired",extra);if(r.task_draft_snapshot_hash!==hash)return fail("task_draft_hash_mismatch",extra);if(r.source_candidate_id!==draft.source_candidate_id)return fail("candidate_link_mismatch",extra);if(r.source_approval_id!==draft.created_from_approval_id)return fail("approval_link_mismatch",extra);
  if(r.causation_id!==draft.task_draft_id||!isCanonicalFarmOsIso(r.requested_at)||Date.parse(r.requested_at)>Date.parse(input.now))return fail("audit_correlation_mismatch",extra);
  const expectedFingerprint=computeConfirmationTaskPersistenceFingerprint({...r,request_fingerprint:undefined} as never);if(r.request_fingerprint!==expectedFingerprint)return fail("idempotency_conflict",extra);
  let authority;try{authority=await withAuthorityTimeout(input.authority_port.getPersistenceAuthority({authority_evidence_ref:r.authority_evidence_ref,task_draft_id:draft.task_draft_id,actor_id:r.requested_by}))}catch{return fail("authority_missing",extra)}if(!("actor_id"in authority))return fail("authority_missing",extra);
  const {source,...authorityMaterial}=authority;if(!["human_review_ledger","authorization_service","current_membership_projection","current_policy_registry"].includes(source))return fail("authority_mismatch",{...extra,authority:"mismatch"});
  const trusted={actor_id:r.requested_by,actor_active:true as const,capability:"persist_confirmation_task" as const,scope,policy_version:FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION,reauthorized_at:r.reauthorization_evidence.reauthorized_at,expires_at:r.reauthorization_evidence.expires_at,approval_id:draft.created_from_approval_id,candidate_id:draft.source_candidate_id,task_draft_id:draft.task_draft_id};
  if(authority.actor_active!==true||r.runtime_context.actor_active!==true||r.reauthorization_evidence.actor_status!=="active")return fail("actor_inactive",{...extra,authority:"mismatch"});if(authority.capability!=="persist_confirmation_task"||r.reauthorization_evidence.capability!=="persist_confirmation_task")return fail("capability_not_allowed",{...extra,authority:"mismatch"});if(authority.scope!==scope||r.runtime_context.target_scope!==scope||r.reauthorization_evidence.scope!==scope)return fail("scope_mismatch",{...extra,authority:"mismatch"});if(authority.policy_version!==FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION||r.runtime_context.current_policy_version!==FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION||r.reauthorization_evidence.policy_version!==FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION)return fail("policy_version_stale",{...extra,authority:"mismatch"});
  if(hashFarmOsContract(authorityMaterial)!==hashFarmOsContract(trusted)||!requestAuthorityMatches(r.runtime_context,r.reauthorization_evidence,authority))return fail("authority_mismatch",{...extra,authority:"mismatch"});if(!authorityTimesValid(authority,r.requested_at,input.now,r.reauthorization_evidence.authenticated_at))return fail("reauthorization_expired",{...extra,authority:"mismatch"});
  const reservation=input.repository.reservePersistence(r.idempotency_key,r.request_fingerprint,draft.task_draft_id,draft.created_from_approval_id);if(reservation==="conflict")return fail("idempotency_conflict",extra);if(reservation==="duplicate")return fail("duplicate_persistence_rejected",extra);if(reservation==="approval_reuse")return fail("approval_reuse_rejected",extra);
  if(reservation==="replay"){const stored=input.repository.readPersistence(r.idempotency_key)!;const replay=outcome({...base,code:null,idempotency:"replayed",idempotencyKey:r.idempotency_key,taskRef:stored.result.task_ref,...extra,authority:"authorized"});return finalize({...replay,audit:{...stored.audit,operation_result:"already_processed",processed_at:input.now}})}
  const taskId=`task_${hash.slice(7,39)}`,record:ConfirmationTaskRecord={schema_version:FARM_OS_CONFIRMATION_TASK_RECORD_SCHEMA_VERSION,task_id:taskId,source_task_draft_id:draft.task_draft_id,source_candidate_id:draft.source_candidate_id,source_approval_id:draft.created_from_approval_id,task_type:draft.task_type,question:draft.question,reason:draft.reason,confirmation_type:draft.confirmation_type,target_reference:draft.target_reference,requested_by_date:draft.requested_by_date,blocking_hint:draft.blocking_hint,status:"open",created_by_actor:r.requested_by,created_at:input.now,updated_at:input.now,version:1,cancellation_state:"not_cancelled",audit_ref:`audit_${r.persistence_request_id}`};
  const ready=outcome({...base,code:null,idempotency:"created",idempotencyKey:r.idempotency_key,taskRef:taskId,...extra,authority:"authorized",task:record});input.repository.saveReferenceTask(r.idempotency_key,r.request_fingerprint,record,ready.result,ready.audit);return finalize(ready);
}

export async function simulateConfirmationTaskCancellation(input:{request:unknown;authority_port:ConfirmationTaskPersistenceAuthorityPort;repository:InMemoryConfirmationTaskReferenceRepository;now:string}):Promise<ConfirmationTaskOperationOutcome>{
  const raw=isFarmOsRecord(input.request)?input.request:{};const base={schema:FARM_OS_CONFIRMATION_TASK_CANCELLATION_SCHEMA_VERSION,requestId:String(raw.cancellation_request_id??"cancellation_rejected"),operation:"confirmation_task_cancel" as const,taskRef:String(raw.task_id??"")||null,correlation:String(raw.correlation_id??"correlation_rejected"),causation:String(raw.causation_id??""),now:input.now};
  const finalize=(o:ConfirmationTaskOperationOutcome)=>{input.repository.appendAudit(o.audit);return o},fail=(code:ConfirmationTaskPersistenceRejectionCode,extra={})=>finalize(outcome({...base,code,idempotency:"rejected",idempotencyKey:String(raw.idempotency_key??""),businessAttempt:raw.business_write_attempt===true,externalAttempt:raw.external_side_effect_attempt===true,...extra}));if(raw.business_write_attempt===true)return fail("business_write_attempt_detected");if(raw.external_side_effect_attempt===true)return fail("external_side_effect_attempt_detected");
  if(!isFarmOsRecord(input.request)||!hasExactFarmOsKeys(input.request,CANCEL_KEYS))return fail("unknown_field");const r=input.request as unknown as ConfirmationTaskCancellationRequest;if(r.schema_version!==FARM_OS_CONFIRMATION_TASK_CANCELLATION_SCHEMA_VERSION||![r.cancellation_request_id,r.task_id,r.requested_by,r.authority_evidence_ref,r.idempotency_key,r.correlation_id,r.causation_id].every(isFarmOsIdentifier))return fail("unknown_field");if(r.dry_run!==true)return fail("dry_run_required");if(!requestEvidenceValid(r.runtime_context,r.reauthorization_evidence))return fail(r.reauthorization_evidence?"unknown_field":"reauthorization_missing");if(!safeReason(r.reason))return fail("cancellation_reason_invalid");
  const task=input.repository.readTask(r.task_id);if(!task)return fail("task_not_found");const scope=scopeOf(task.target_reference),fingerprint=computeConfirmationTaskCancellationFingerprint(r,scope),extra={task,actor:r.requested_by,capability:"cancel_confirmation_task",scope,fingerprint,expected:r.expected_task_version,observed:task.version};
  if(r.causation_id!==r.task_id||!isCanonicalFarmOsIso(r.requested_at)||Date.parse(r.requested_at)>Date.parse(input.now))return fail("audit_correlation_mismatch",extra);
  let authority;try{authority=await withAuthorityTimeout(input.authority_port.getCancellationAuthority({authority_evidence_ref:r.authority_evidence_ref,task_id:r.task_id,actor_id:r.requested_by}))}catch{return fail("authority_missing",extra)}if(!("actor_id"in authority))return fail("authority_missing",extra);
  const {source,...authorityMaterial}=authority;if(!["authorization_service","current_membership_projection","current_policy_registry"].includes(source))return fail("authority_mismatch",{...extra,authority:"mismatch"});
  const trusted={actor_id:r.requested_by,actor_active:true as const,capability:"cancel_confirmation_task" as const,scope,policy_version:FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION,reauthorized_at:r.reauthorization_evidence.reauthorized_at,expires_at:r.reauthorization_evidence.expires_at,task_id:r.task_id,approval_id:task.source_approval_id,candidate_id:task.source_candidate_id,task_draft_id:task.source_task_draft_id};
  if(authority.actor_active!==true||r.runtime_context.actor_active!==true||r.reauthorization_evidence.actor_status!=="active")return fail("actor_inactive",{...extra,authority:"mismatch"});if(authority.capability!=="cancel_confirmation_task"||r.reauthorization_evidence.capability!=="cancel_confirmation_task")return fail("capability_not_allowed",{...extra,authority:"mismatch"});if(authority.scope!==scope||r.runtime_context.target_scope!==scope||r.reauthorization_evidence.scope!==scope)return fail("scope_mismatch",{...extra,authority:"mismatch"});if(authority.policy_version!==FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION||r.runtime_context.current_policy_version!==FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION||r.reauthorization_evidence.policy_version!==FARM_OS_CONFIRMATION_TASK_PERSISTENCE_POLICY_VERSION)return fail("policy_version_stale",{...extra,authority:"mismatch"});
  if(hashFarmOsContract(authorityMaterial)!==hashFarmOsContract(trusted)||!requestAuthorityMatches(r.runtime_context,r.reauthorization_evidence,authority))return fail("authority_mismatch",{...extra,authority:"mismatch"});if(!authorityTimesValid(authority,r.requested_at,input.now,r.reauthorization_evidence.authenticated_at))return fail("reauthorization_expired",{...extra,authority:"mismatch"});
  const reservation=input.repository.reserveCancellation(r.idempotency_key,fingerprint,r.task_id);if(reservation==="conflict")return fail("idempotency_conflict",extra);if(reservation==="duplicate")return fail("duplicate_cancellation_rejected",extra);if(reservation==="replay"){const stored=input.repository.readCancellation(r.idempotency_key)!;const replay=outcome({...base,code:null,idempotency:"replayed",idempotencyKey:r.idempotency_key,...extra,authority:"authorized",taskRef:stored.result.task_ref});return finalize({...replay,audit:{...stored.audit,operation_result:"already_processed",processed_at:input.now}})}
  if(!Number.isSafeInteger(r.expected_task_version)||r.expected_task_version!==task.version)return fail("version_conflict",extra);if(task.status==="cancelled")return fail("task_already_cancelled",extra);if(task.status!=="open")return fail("task_status_not_cancellable",extra);
  const preview=outcome({...base,code:null,idempotency:"created",idempotencyKey:r.idempotency_key,...extra,authority:"authorized",taskRef:r.task_id});const changed=input.repository.cancelReferenceTask(r.idempotency_key,fingerprint,r.task_id,r.expected_task_version,input.now,preview.result,preview.audit);if(changed.status==="version_conflict")return fail("version_conflict",extra);if(changed.status==="already_cancelled")return fail("task_already_cancelled",extra);if(changed.status!=="cancelled")return fail("task_not_open",extra);return finalize({...preview,record:changed.record,audit:{...preview.audit,observed_task_version:task.version}});
}
