import type { FarmOsRiskLevel, FarmOsRollbackClass } from "./farm_os_risk_taxonomy";
import { isCanonicalFarmOsIso } from "./farm_os_approved_proposal_contract";

const record = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
const exact = (value: Record<string, unknown>, keys: readonly string[]) => Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));
const nonEmpty = (value: unknown): value is string => typeof value === "string" && value.trim().length > 0;
const iso = (value: unknown): value is string => isCanonicalFarmOsIso(value) && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u.test(value);
const positive = (value: unknown): value is number => typeof value === "number" && Number.isInteger(value) && value > 0;

export const FARM_OS_CROP_WORKFORCE_SCHEMA_VERSION = "farmos.crop-workforce-governance.v1" as const;
export const FARM_OS_CONTEXT_TYPES = ["field","crop_cycle","work_record","approved_crop_plan","inventory","resource_usage","supplier_coordination","workforce_member","capability_assignment","sales_constraint"] as const;
export const FARM_OS_SOURCE_SYSTEMS = ["farming_app","sales_commerce"] as const;
export const FARM_OS_FRESHNESS_STATUSES = ["fresh","stale","unavailable","not_connected","failed","forbidden"] as const;
export const FARM_OS_SCOPE_TYPES = ["farm","team","crop","crop_plan","crop_cycle","field","supplier","sales_channel","all"] as const;
export const FARM_OS_CAPABILITY_GROUPS = ["field","management","crop_planning","supplier_amendment","sales_business","permissions_external"] as const;
export const FARM_OS_CAPABILITIES = ["view_own_tasks","record_own_work","view_field_instructions","submit_field_observation","view_confirmed_crop_plan","view_all_staff_progress","edit_work_plan","assign_staff","review_operational_proposal","approve_operational_proposal","view_crop_plan","view_crop_plan_decision_basis","review_crop_plan","approve_crop_plan","view_supplier_coordination","manage_supplier_coordination","approve_amendment_allocation","view_sales_summary","view_sales_detail","view_customer_reference","view_prices","view_costs","view_gross_margin","approve_sales_allocation","manage_permissions","approve_external_execution","approve_sales_change"] as const;
export const FARM_OS_CROP_PROPOSAL_TYPES = ["crop_plan_review_request","crop_plan_sowing_window","crop_plan_variety_selection","crop_plan_field_allocation","crop_plan_transplant_window","crop_plan_amendment_allocation","crop_plan_harvest_window","crop_plan_production_target","crop_plan_sales_constraint","crop_plan_integrated_scenario","supplier_coordination_draft","amendment_delivery_schedule_proposal","amendment_field_allocation_proposal","amendment_quantity_revision_proposal","amendment_conflict_resolution_proposal","workforce_lifecycle_proposal","capability_change_proposal","sales_allocation_proposal"] as const;
export const FARM_OS_LIFECYCLE_EVENTS = ["promotion","transfer","demotion","suspension","exit","executive_transition","advisor_transition","rehire","repeat_internship","capability_grant","capability_reduce","capability_revoke","assignment_start","assignment_end"] as const;

export type FarmOsContextType = (typeof FARM_OS_CONTEXT_TYPES)[number];
export type FarmOsSourceSystem = (typeof FARM_OS_SOURCE_SYSTEMS)[number];
export type FarmOsScopeType = (typeof FARM_OS_SCOPE_TYPES)[number];
export type FarmOsCapabilityId = (typeof FARM_OS_CAPABILITIES)[number];
export type FarmOsCropProposalType = (typeof FARM_OS_CROP_PROPOSAL_TYPES)[number];
const sourceAllowedForContext = (context: FarmOsContextType, source: FarmOsSourceSystem) => context === "sales_constraint" ? source === "sales_commerce" : source === "farming_app";

export type FarmOsTypedContextReference = { schema_version: typeof FARM_OS_CROP_WORKFORCE_SCHEMA_VERSION; context_type: FarmOsContextType; source_system: FarmOsSourceSystem; reference_id: string; reference_version: number; observed_at: string; freshness_status: (typeof FARM_OS_FRESHNESS_STATUSES)[number]; scope: { scope_type: FarmOsScopeType; scope_reference: string | null; valid_from: string; valid_until: string | null }; required_capability: FarmOsCapabilityId };
const contextKeys = ["schema_version","context_type","source_system","reference_id","reference_version","observed_at","freshness_status","scope","required_capability"] as const;
export function parseFarmOsTypedContextReference(value: unknown): FarmOsTypedContextReference | null {
  if (!record(value) || !exact(value, contextKeys) || value.schema_version !== FARM_OS_CROP_WORKFORCE_SCHEMA_VERSION || !FARM_OS_CONTEXT_TYPES.includes(value.context_type as FarmOsContextType) || !FARM_OS_SOURCE_SYSTEMS.includes(value.source_system as FarmOsSourceSystem) || !nonEmpty(value.reference_id) || !positive(value.reference_version) || !iso(value.observed_at) || !FARM_OS_FRESHNESS_STATUSES.includes(value.freshness_status as never) || !FARM_OS_CAPABILITIES.includes(value.required_capability as FarmOsCapabilityId) || !record(value.scope) || !exact(value.scope,["scope_type","scope_reference","valid_from","valid_until"])) return null;
  const scope = value.scope;
  if (!sourceAllowedForContext(value.context_type as FarmOsContextType,value.source_system as FarmOsSourceSystem) || !FARM_OS_SCOPE_TYPES.includes(scope.scope_type as FarmOsScopeType) || !(scope.scope_reference === null || nonEmpty(scope.scope_reference)) || !iso(scope.valid_from) || !(scope.valid_until === null || iso(scope.valid_until)) || (typeof scope.valid_until === "string" && Date.parse(scope.valid_until) <= Date.parse(scope.valid_from))) return null;
  return value as FarmOsTypedContextReference;
}

export type FarmOsProposalGovernance = { proposal_type: FarmOsCropProposalType; target_context: readonly FarmOsContextType[]; required_evidence: readonly string[]; required_capabilities: readonly FarmOsCapabilityId[]; risk_level: Extract<FarmOsRiskLevel,"l1_proposal_write">; allowed_command_class: null; requires_human_review: true; partial_approval_allowed: boolean; expiry_required: true; rollback_class: Extract<FarmOsRollbackClass,"reject_or_supersede">; actual_write_forbidden: true };
const crop = ["crop_plan_review_request","crop_plan_sowing_window","crop_plan_variety_selection","crop_plan_field_allocation","crop_plan_transplant_window","crop_plan_amendment_allocation","crop_plan_harvest_window","crop_plan_production_target","crop_plan_sales_constraint","crop_plan_integrated_scenario"] as const;
export const FARM_OS_CROP_WORKFORCE_PROPOSAL_REGISTRY: Readonly<Record<FarmOsCropProposalType,FarmOsProposalGovernance>> = Object.fromEntries(FARM_OS_CROP_PROPOSAL_TYPES.map((proposal_type) => [proposal_type,{proposal_type,target_context:proposal_type.includes("sales")?["sales_constraint"]:proposal_type.includes("supplier")||proposal_type.includes("amendment")?["supplier_coordination","approved_crop_plan"]:proposal_type.includes("workforce")||proposal_type.includes("capability")?["workforce_member","capability_assignment"]:crop.includes(proposal_type as never)?["approved_crop_plan"]:["sales_constraint"],required_evidence:["typed_context_reference"],required_capabilities:proposal_type.includes("sales")?["approve_sales_allocation"]:proposal_type.includes("supplier")||proposal_type.includes("amendment")?["manage_supplier_coordination"]:proposal_type.includes("workforce")||proposal_type.includes("capability")?["manage_permissions"]:["review_crop_plan"],risk_level:"l1_proposal_write",allowed_command_class:null,requires_human_review:true,partial_approval_allowed:proposal_type!=="crop_plan_integrated_scenario",expiry_required:true,rollback_class:"reject_or_supersede",actual_write_forbidden:true}])) as unknown as Record<FarmOsCropProposalType,FarmOsProposalGovernance>;

export type FarmOsCapabilityDefinition = { capability_id: FarmOsCapabilityId; capability_group: (typeof FARM_OS_CAPABILITY_GROUPS)[number]; risk_level: FarmOsRiskLevel; allowed_subject_types: readonly ["human"]; scope_required: boolean; validity_required: boolean; separation_of_duties_required: boolean; sales_sensitive: boolean; external_execution_related: boolean };
const group = (id: FarmOsCapabilityId): FarmOsCapabilityDefinition["capability_group"] => id.includes("sales")||["view_prices","view_costs","view_gross_margin","view_customer_reference"].includes(id)?"sales_business":id.includes("crop_plan")?"crop_planning":id.includes("supplier")||id.includes("amendment")?"supplier_amendment":id.includes("permission")||id.includes("external")?"permissions_external":id.includes("staff")||id.includes("work_plan")||id.includes("assign")||id.includes("operational")?"management":"field";
export const FARM_OS_CAPABILITY_REGISTRY: Readonly<Record<FarmOsCapabilityId,FarmOsCapabilityDefinition>> = Object.fromEntries(FARM_OS_CAPABILITIES.map((capability_id)=>[capability_id,{capability_id,capability_group:group(capability_id),risk_level:capability_id==="approve_external_execution"||capability_id==="approve_sales_change"?"l3_external_execution":capability_id.startsWith("approve_")||capability_id==="manage_permissions"?"l2_internal_apply":"l0_read_only",allowed_subject_types:["human"],scope_required:true,validity_required:true,separation_of_duties_required:capability_id.startsWith("approve_")||capability_id==="manage_permissions",sales_sensitive:group(capability_id)==="sales_business",external_execution_related:capability_id==="approve_external_execution"||capability_id==="approve_sales_change"}])) as unknown as Record<FarmOsCapabilityId,FarmOsCapabilityDefinition>;

export type FarmOsLifecycleTransition = { event: (typeof FARM_OS_LIFECYCLE_EVENTS)[number]; from_state_category: "external_sot"; to_state_category: "external_sot"; human_approval_required: true; required_capabilities: readonly FarmOsCapabilityId[]; self_action_allowed: false; scope_change_allowed: false; capability_recheck_required: true; session_revocation_required: boolean; audit_required: true; business_write_allowed: false };
export const FARM_OS_LIFECYCLE_TRANSITIONS: readonly FarmOsLifecycleTransition[] = FARM_OS_LIFECYCLE_EVENTS.map((event)=>({event,from_state_category:"external_sot",to_state_category:"external_sot",human_approval_required:true,required_capabilities:["manage_permissions"],self_action_allowed:false,scope_change_allowed:false,capability_recheck_required:true,session_revocation_required:["suspension","exit","executive_transition","capability_revoke"].includes(event),audit_required:true,business_write_allowed:false}));
export const FARM_OS_WORKFORCE_CONCEPTS = ["participation_or_employment_status","business_role","skill_or_certification","system_capability","scope","validity","assignment"] as const;
export const FARM_OS_SUPPLIER_STATES = ["supplier_contact","coordination_draft","proposed_allocation","approved_allocation","scheduled_delivery","actual_delivery","actual_application"] as const;
export const FARM_OS_QUANTITY_STATES = ["proposed_quantity","approved_quantity","scheduled_quantity","delivered_quantity","applied_quantity"] as const;
export const FARM_OS_SOT_BOUNDARIES = { farming_app:["field","crop_cycle","work_record","work_plan","staff_assignment","inventory","resource_usage","approved_crop_plan","workforce_participation","employment_state","business_role_assignment","skill_certification","capability_assignment","actual_supplier_delivery","actual_amendment_application"], farmos_core:["ai_proposal","crop_planning_proposal","workforce_governance_proposal","policy","knowledge","decision_basis","proposal_review_audit","governance_finding","execution_trace"], sales_commerce:["product","order","customer","price","sales_result","shipping_cost","fee","gross_margin","sales_allocation_result"] } as const;
export const farmOsSalesCapabilityAllows = (held: readonly FarmOsCapabilityId[], requested: FarmOsCapabilityId) => held.includes(requested) && FARM_OS_CAPABILITY_REGISTRY[requested].sales_sensitive;
export type FarmOsCapabilityAssignmentCandidate={capability_id:FarmOsCapabilityId;scope:{scope_type:FarmOsScopeType;scope_reference:string|null;valid_from:string;valid_until:string|null};actor_id:string;subject_id:string;event:"capability_grant"|"promotion";subject_state:"active"|"former_member"};
export function validateFarmOsCapabilityAssignmentCandidate(value:unknown):{valid:boolean;blocked_reason:string|null}{if(!record(value)||!exact(value,["capability_id","scope","actor_id","subject_id","event","subject_state"])||!FARM_OS_CAPABILITIES.includes(value.capability_id as FarmOsCapabilityId)||!nonEmpty(value.actor_id)||!nonEmpty(value.subject_id)||!(value.event==="capability_grant"||value.event==="promotion")||!(value.subject_state==="active"||value.subject_state==="former_member")||!record(value.scope)||!exact(value.scope,["scope_type","scope_reference","valid_from","valid_until"]))return{valid:false,blocked_reason:"INVALID_ASSIGNMENT_CANDIDATE"};if(value.actor_id===value.subject_id)return{valid:false,blocked_reason:"SELF_ACTION_FORBIDDEN"};if(value.subject_state==="former_member")return{valid:false,blocked_reason:"FORMER_MEMBER_CAPABILITY_FORBIDDEN"};const s=value.scope;if(!FARM_OS_SCOPE_TYPES.includes(s.scope_type as FarmOsScopeType)||!(s.scope_reference===null||nonEmpty(s.scope_reference))||!iso(s.valid_from)||!(s.valid_until===null||iso(s.valid_until))||(typeof s.valid_until==="string"&&Date.parse(s.valid_until)<=Date.parse(s.valid_from))||(typeof s.valid_until==="string"&&Date.parse(s.valid_until)<=Date.now()))return{valid:false,blocked_reason:"SCOPE_INVALID_OR_EXPIRED"};return{valid:true,blocked_reason:null}}
