import { HERMES_DAILY_FARM_BRIEF_PROPOSAL_REVIEW_LIST_PATH,parseHermesDailyFarmBriefProposalReviewDetailApiResponse,parseHermesDailyFarmBriefProposalReviewListApiResponse,type HermesDailyFarmBriefProposalReviewDetailApiResponse,type HermesDailyFarmBriefProposalReviewListApiResponse } from "../../../scripts/hermes/brief_runtime/hermes_daily_farm_brief_proposal_review_api_contract";
import { serveHermesDailyFarmBriefProposalReviewDetail,serveHermesDailyFarmBriefProposalReviewList } from "../../../scripts/hermes/brief_runtime/hermes_daily_farm_brief_proposal_review_service";
import { hermesDailyFarmBriefProposalReviewServerDependencies } from "./hermes_daily_farm_brief_proposal_review_server_boundary";

export type DailyBriefProposalListUiState={state:"ok";response:Extract<HermesDailyFarmBriefProposalReviewListApiResponse,{result:"ok"}>}|{state:"authentication_required"|"access_forbidden"|"unavailable";response:null};
export type DailyBriefProposalDetailUiState={state:"ok";response:Extract<HermesDailyFarmBriefProposalReviewDetailApiResponse,{result:"ok"}>}|{state:"authentication_required"|"access_forbidden"|"not_found"|"unavailable";response:null};
function forwardedHeaders(value:Headers):Headers{const result=new Headers();for(const name of ["authorization","cookie"]){const item=value.get(name);if(item!==null)result.set(name,item);}return result;}
async function parsedBody(response:Response):Promise<unknown>{try{return JSON.parse(await response.text());}catch{return null;}}
export function createDailyBriefProposalListUiState(status:number,body:unknown):DailyBriefProposalListUiState{if(status===401)return{state:"authentication_required",response:null};if(status===403)return{state:"access_forbidden",response:null};if(status!==200)return{state:"unavailable",response:null};const parsed=parseHermesDailyFarmBriefProposalReviewListApiResponse(body);return parsed?.result==="ok"?{state:"ok",response:parsed}:{state:"unavailable",response:null};}
export function createDailyBriefProposalDetailUiState(status:number,body:unknown):DailyBriefProposalDetailUiState{if(status===401)return{state:"authentication_required",response:null};if(status===403)return{state:"access_forbidden",response:null};if(status===404||status===400)return{state:"not_found",response:null};if(status!==200)return{state:"unavailable",response:null};const parsed=parseHermesDailyFarmBriefProposalReviewDetailApiResponse(body);return parsed?.result==="ok"?{state:"ok",response:parsed}:{state:"unavailable",response:null};}
export async function readDailyBriefProposalListUi(input:{headers:Headers}):Promise<DailyBriefProposalListUiState>{const request=new Request(`http://server${HERMES_DAILY_FARM_BRIEF_PROPOSAL_REVIEW_LIST_PATH}`,{headers:forwardedHeaders(input.headers)});const response=await serveHermesDailyFarmBriefProposalReviewList({request,dependencies:hermesDailyFarmBriefProposalReviewServerDependencies});return createDailyBriefProposalListUiState(response.status,await parsedBody(response));}
export async function readDailyBriefProposalDetailUi(input:{headers:Headers;proposalRef:string}):Promise<DailyBriefProposalDetailUiState>{const request=new Request(`http://server${HERMES_DAILY_FARM_BRIEF_PROPOSAL_REVIEW_LIST_PATH}/${encodeURIComponent(input.proposalRef)}`,{headers:forwardedHeaders(input.headers)});const response=await serveHermesDailyFarmBriefProposalReviewDetail({request,dependencies:hermesDailyFarmBriefProposalReviewServerDependencies});return createDailyBriefProposalDetailUiState(response.status,await parsedBody(response));}
