import type { HermesOperationalReadonlyClientResult } from "../../src/lib/hermes/hermes_operational_readonly_client";
import { integrateHermesDailyFarmBriefRealData } from "./brief_runtime/hermes_daily_farm_brief_integration";

const generatedAt = "2026-07-14T09:00:00.000Z";

const operationalFixture: HermesOperationalReadonlyClientResult = {
  result: "ok",
  checked: "hermes_operational_readonly_client",
  boundary: "day92_hermes_operational_readonly_client",
  inventory: {
    result: "ok",
    source_type: "inventory",
    endpoint_path: "/api/farmos-core/inventory-summary",
    http_method: "GET",
    fetch_performed: false,
    available: true,
    transaction_read_only: true,
    requested_limit: 100,
    http_status: 200,
    response_source: "apparetenkei_inventory_readonly",
    generated_at: "2026-07-14T08:00:00.000Z",
    record_count: 0,
    records: [],
    has_more: false,
    error_code: null,
    write_performed: false,
    restricted_fields_exposed: false,
    credentials_exposed: false,
  },
  work_log: {
    result: "ok",
    source_type: "work_log",
    endpoint_path: "/api/farmos-core/recent-work-logs",
    http_method: "GET",
    fetch_performed: false,
    available: true,
    transaction_read_only: true,
    requested_limit: 100,
    http_status: 200,
    response_source: "apparetenkei_work_logs_readonly",
    generated_at: "2026-07-14T08:00:00.000Z",
    record_count: 2,
    records: [
      {
        id: "preview-work-1",
        startedAt: "2026-07-14T06:00:00.000Z",
        fieldId: null,
        workTypeId: null,
        workTypeName: "harvest",
        durationMinutes: 45,
        targetCrop: "cabbage",
        cropCycleId: null,
        machineId: null,
        implementId: null,
        yieldAmount: null,
        yieldUnit: null,
        appliedMaterials: null,
      },
      {
        id: "preview-work-2",
        startedAt: null,
        fieldId: null,
        workTypeId: null,
        workTypeName: null,
        durationMinutes: null,
        targetCrop: null,
        cropCycleId: null,
        machineId: null,
        implementId: null,
        yieldAmount: null,
        yieldUnit: null,
        appliedMaterials: null,
      },
    ],
    has_more: false,
    error_code: null,
    write_performed: false,
    restricted_fields_exposed: false,
    credentials_exposed: false,
  },
  inventory_source_connected: true,
  work_log_source_connected: true,
  external_fetch_performed: false,
  hermes_context_injection_performed: false,
  suggestion_generation_performed: false,
  proposal_created: false,
  proposal_saved: false,
  proposal_apply_performed: false,
  app_db_write_performed: false,
  core_db_write_performed: false,
  audit_write_performed: false,
  database_write_performed: false,
  credentials_exposed: false,
  arbitrary_endpoint_allowed: false,
  arbitrary_method_allowed: false,
};

const memoryFixture = {
  result: "ok",
  boundary: {
    mode: "hermes_memory_context_read_boundary",
    db_user: "fixture-reader",
    transaction_read_only: true,
    writes_performed: false,
    commands_executed: false,
    hermes_runtime_executed: false,
    llm_runtime_executed: false,
    embeddings_executed: false,
    vector_search_executed: false,
    app_schema_write_allowed: false,
    ai_proposal_write_allowed: false,
    audit_apply_event_write_allowed: false,
  },
  context: {
    scope: "hermes_memory_context_minimum",
    runtime: {
      hermes_runtime_executed: false,
      llm_runtime_executed: false,
      embeddings_executed: false,
      vector_search_executed: false,
    },
    proposal_context: {},
    latest_hermes_notes: [{ id: "note-preview", content: "not printed" }],
    safe_app_context: {
      crop_cycles_summary: [
        { id: "cycle-preview", crop: "not printed", status: "active" },
      ],
      visible_domain_scope: ["crop_cycles_minimum_summary"],
    },
    memory_policy: { read_only: true },
    redaction_policy: { restricted_fields_exposed: false },
    restricted_domain_data_exposed: false,
  },
};

const result = await integrateHermesDailyFarmBriefRealData({
  readOperationalSources: async () => operationalFixture,
  readMemoryContext: async () => memoryFixture,
  now: () => generatedAt,
  timezone: "Asia/Tokyo",
  snapshotIdFactory: () => "snapshot-real-data-preview",
  briefIdFactory: () => "brief-real-data-preview",
  factIdFactory: (index) => `fact-real-data-preview-${index}`,
});

console.log(JSON.stringify(result.safe_preview, null, 2));
