import { randomUUID } from "node:crypto";
import { createClient } from "redis";
import { createHermesJobEnvelope } from "./job_runtime/hermes_job_envelope";
import { createHermesRedisQueueStore, readHermesRedisClientConfig } from "./queue_runtime/hermes_redis_client";
import { createHermesRedisQueueKeys } from "./queue_runtime/hermes_redis_queue_contract";
import { enqueueHermesJob } from "./queue_runtime/hermes_redis_queue";
import { createHermesWorkerAdvertisement } from "./worker_runtime/hermes_worker_protocol";
import { createHermesWorkerRegistryKeys } from "./worker_runtime/hermes_worker_registry_contract";
import { createHermesWorkerRegistryStore, heartbeatHermesWorker, registerHermesWorker } from "./worker_runtime/hermes_worker_registry";
import { createHermesRoutingDecisionSummary } from "./router_runtime/hermes_model_router";
import { createHermesWorkerStartupKeys, createHermesWorkerStartupStore, requestHermesWorkerWake } from "./startup_runtime/hermes_worker_startup_store";
import { createHermesWakeExecutionApproval } from "./wake_runtime/hermes_wake_execution_policy";
import { createHermesWakeExecutionKeys, createHermesWakeExecutionStore } from "./wake_runtime/hermes_wake_execution_store";
import { executeHermesApprovedWake, persistHermesWakeApproval } from "./wake_runtime/hermes_wake_execution_gateway";
import { createHermesWakeConfirmationKeys, createHermesWakeConfirmationStore } from "./confirmation_runtime/hermes_wake_confirmation_store";
import { checkHermesWakeConfirmationOnce, createHermesWakeConfirmation } from "./confirmation_runtime/hermes_wake_confirmation_checker";
import { createHermesRoutingResumeKeys, createHermesRoutingResumeStore } from "./resume_runtime/hermes_routing_resume_store";
import { createHermesCanonicalRoutingStore } from "./resume_runtime/hermes_canonical_routing_decision_store";
import { createCanonicalHermesInitialRouting } from "./resume_runtime/hermes_initial_routing_coordinator";
import { resumeHermesPostWakeRouting } from "./resume_runtime/hermes_routing_resume_coordinator";

async function main(){
  const env={...process.env};if(!env.HERMES_REDIS_URL&&env.REDIS_PASSWORD)env.HERMES_REDIS_URL=`redis://:${encodeURIComponent(env.REDIS_PASSWORD)}@127.0.0.1:6379`;env.HERMES_REDIS_QUEUE_ENABLED="true";
  const config=readHermesRedisClientConfig(env).config;if(!config)throw new Error("routing_resume_smoke_configuration_unavailable");
  const uid=randomUUID(),prefix=`farmos:hermes:test:day105:${uid}`,jobId=`job-${uid}`,requestId=`request-${uid}`,workerId=`rtx-${uid}`;
  const queueKeys=createHermesRedisQueueKeys(prefix),workerKeys=createHermesWorkerRegistryKeys(prefix),startupKeys=createHermesWorkerStartupKeys(prefix),wakeKeys=createHermesWakeExecutionKeys(prefix),confirmationKeys=createHermesWakeConfirmationKeys(prefix),resumeKeys=createHermesRoutingResumeKeys(prefix);
  const raw=createClient({url:config.url});raw.on("error",()=>undefined);await raw.connect();const cleanup=new Set<string>([queueKeys.pending,queueKeys.processing,queueKeys.deadLetter,workerKeys.workers]);
  try {
  let now=new Date(Date.now()-2000).toISOString();
  const queueContext={enabled:true,keys:queueKeys,storeFactory:()=>createHermesRedisQueueStore(config),nowIsoFactory:()=>now};
  const workerContext={enabled:true,keys:workerKeys,storeFactory:()=>createHermesWorkerRegistryStore(config),nowIsoFactory:()=>now};
  const envelope=createHermesJobEnvelope({requestId,payload:{message:"day105 integration fixture",include_readonly_context:false},jobIdFactory:()=>jobId,nowIsoFactory:()=>new Date(Date.now()-5000).toISOString()});
  const enqueued=await enqueueHermesJob(envelope,queueContext);if(!enqueued.ok)throw new Error("integration_enqueue_failed");cleanup.add(queueKeys.job(jobId));cleanup.add(queueKeys.dedupe(jobId));
  const offline=createHermesWorkerAdvertisement({workerId,workerType:"rtx",capabilities:["heavy_reasoning"],health:"healthy",runtimeAvailable:false,draining:false,nowIso:now});
  const registered=await registerHermesWorker(offline,workerContext);if(!registered.ok)throw new Error("integration_worker_register_failed");cleanup.add(workerKeys.worker(workerId));
  const offlineSummary={worker_id:offline.worker_id,worker_type:offline.worker_type,capabilities:offline.capabilities,health:offline.health,readiness:offline.readiness,runtime_available:offline.runtime_available,draining:offline.draining,last_heartbeat_at:offline.last_heartbeat_at,current_job_id:offline.current_job_id,active_job_count:offline.active_job_count,max_concurrency:offline.max_concurrency};
  const routingContext={enabled:true,keys:resumeKeys,storeFactory:()=>createHermesCanonicalRoutingStore(config),nowIsoFactory:()=>now};
  const binding=await createCanonicalHermesInitialRouting({jobId,taskClass:"heavy_reasoning",workers:[offlineSummary],context:routingContext,decisionIdFactory:()=>`decision-${uid}`});if(!binding.ok)throw new Error("integration_binding_failed");cleanup.add(resumeKeys.routingDecision(jobId));cleanup.add(resumeKeys.routingDecisionId(binding.record.decision.decision_id));
  const startupContext={enabled:true,keys:startupKeys,storeFactory:()=>createHermesWorkerStartupStore(config),nowIsoFactory:()=>now};
  const wake=await requestHermesWorkerWake({routingRequirement:binding.record.decision.requirement,routingDecision:createHermesRoutingDecisionSummary(binding.record.decision),workers:[offlineSummary],context:startupContext,wakeRequestIdFactory:()=>`wake-${uid}`});if(!wake.ok)throw new Error("integration_wake_request_failed");const request=wake.wake_request;cleanup.add(startupKeys.request(request.wake_request_id));cleanup.add(startupKeys.active(workerId));cleanup.add(startupKeys.cooldown(workerId));cleanup.add(startupKeys.decision(request.routing_decision_id));
  now=new Date().toISOString();const approval=createHermesWakeExecutionApproval({request,nowIso:now,approvalIdFactory:()=>`approval-${uid}`});
  const executionContext={enabled:true,keys:wakeKeys,storeFactory:()=>createHermesWakeExecutionStore(config)};
  const approvalResult=await persistHermesWakeApproval({wakeRequestId:request.wake_request_id,approval,context:executionContext,nowIso:now});if(!approvalResult.ok)throw new Error("integration_approval_failed");cleanup.add(wakeKeys.approval(request.wake_request_id));
  const executed=await executeHermesApprovedWake({wakeRequestId:request.wake_request_id,context:executionContext,sender:{send:async()=>({bytes_sent:102})},env:{HERMES_RTX_WAKE_ENABLED:"true",HERMES_RTX_WAKE_TARGET_WORKER_ID:workerId,HERMES_RTX_WAKE_MAC:["001122","334455"].join(""),HERMES_RTX_WAKE_BROADCAST:"255.255.255.255",HERMES_RTX_WAKE_PORT:"9"},nowIso:now,executionIdFactory:()=>`execution-${uid}`});if(!executed.ok||executed.status!=="sent")throw new Error("integration_execution_failed");cleanup.add(wakeKeys.execution(request.wake_request_id));cleanup.add(wakeKeys.executionId(executed.execution.execution_id));
  await new Promise(resolve=>setTimeout(resolve,5));now=new Date().toISOString();const heartbeat=await heartbeatHermesWorker(workerId,{health:"healthy",runtimeAvailable:true,draining:false},workerContext);if(!heartbeat.ok)throw new Error("integration_heartbeat_failed");
  const confirmationContext={enabled:true,keys:confirmationKeys,storeFactory:()=>createHermesWakeConfirmationStore(config),nowIsoFactory:()=>now};
  const confirmationCreated=await createHermesWakeConfirmation({wakeRequestId:request.wake_request_id,context:confirmationContext,confirmationIdFactory:()=>`confirmation-${uid}`});if(!confirmationCreated.ok)throw new Error("integration_confirmation_create_failed");cleanup.add(confirmationKeys.confirmation(request.wake_request_id));cleanup.add(confirmationKeys.confirmationId(confirmationCreated.confirmation.confirmation_id));
  const confirmation=await checkHermesWakeConfirmationOnce({wakeRequestId:request.wake_request_id,context:confirmationContext});if(!confirmation.ok||confirmation.confirmation.status!=="worker_ready")throw new Error(`integration_confirmation_not_ready:${confirmation.ok?confirmation.confirmation.status:confirmation.error_code}`);
  const resumeContext={enabled:true,keys:resumeKeys,storeFactory:()=>createHermesRoutingResumeStore(config),nowIsoFactory:()=>now};const idA=`resume-a-${uid}`,idB=`resume-b-${uid}`;cleanup.add(resumeKeys.resume(jobId));cleanup.add(resumeKeys.resumeId(idA));cleanup.add(resumeKeys.resumeId(idB));
  const concurrent=await Promise.all([resumeHermesPostWakeRouting({jobId,context:resumeContext,resumeIdFactory:()=>idA,decisionIdFactory:()=>`resumed-a-${uid}`}),resumeHermesPostWakeRouting({jobId,context:resumeContext,resumeIdFactory:()=>idB,decisionIdFactory:()=>`resumed-b-${uid}`})]);
  const created=concurrent.filter(x=>x.ok&&x.status==="created"),replayed=concurrent.filter(x=>x.ok&&x.status==="already_exists");if(created.length!==1||replayed.length!==1||!concurrent.every(x=>x.ok))throw new Error(`integration_resume_concurrency_failed:${concurrent.map(x=>x.ok?x.status:x.error_code).join(",")}`);const a=concurrent[0],b=concurrent[1];if(!a.ok||!b.ok)throw new Error("integration_resume_failed");const canonicalId=a.resume.resume_id,rawBefore=await raw.get(resumeKeys.resume(jobId)),ttlBefore=await raw.pExpireTime(resumeKeys.resume(jobId));
  now=new Date(Date.now()+100000).toISOString();const replay=await resumeHermesPostWakeRouting({jobId,context:resumeContext});const rawAfter=await raw.get(resumeKeys.resume(jobId)),ttlAfter=await raw.pExpireTime(resumeKeys.resume(jobId));
  const idConsistent=(await raw.get(resumeKeys.resumeId(canonicalId)))===jobId,recordCount=rawBefore?1:0;
  if(!replay.ok||replay.status!=="already_exists"||JSON.stringify(replay.resumed_routing_decision)!==JSON.stringify(a.resumed_routing_decision)||rawBefore!==rawAfter||ttlAfter>ttlBefore)throw new Error("integration_canonical_replay_failed");
  const invalidDecisionId=`decision-invalid-${uid}`,invalidBindingKey=`${prefix}:routing-decision-corrupt:${jobId}`,invalidDecisionKey=resumeKeys.routingDecisionId(invalidDecisionId),invalidBinding=structuredClone(binding.record);invalidBinding.decision.decision_id=invalidDecisionId;(invalidBinding.decision as any).status="selected";cleanup.add(invalidBindingKey);cleanup.add(invalidDecisionKey);const bindingStore=await createHermesCanonicalRoutingStore(config);const invalidInitial=await bindingStore.persistAtomic({jobKey:resumeKeys.job(jobId),recordKey:invalidBindingKey,decisionIdKey:invalidDecisionKey,decisionIdKeyPrefix:`${prefix}:routing-decision-id:`,jobId,requestId,decisionId:invalidDecisionId,serialized:JSON.stringify(invalidBinding),expiresAtMs:Date.parse(envelope.runtime.expires_at),jobExpiresAt:envelope.runtime.expires_at});await bindingStore.disconnect();const invalidInitialAbsent=(await raw.get(invalidBindingKey))===null&&(await raw.get(invalidDecisionKey))===null;
  const invalidResumeId=`resume-invalid-${uid}`,invalidResumeKey=`${prefix}:routing-resume-corrupt:${jobId}`,invalidResumeIdKey=resumeKeys.resumeId(invalidResumeId),invalidResume=structuredClone(a.resume);invalidResume.resume_id=invalidResumeId;invalidResume.resumed_routing_decision.selected_worker!.worker_id=`rtx-other-${uid}`;cleanup.add(invalidResumeKey);cleanup.add(invalidResumeIdKey);const resumeStore=await createHermesRoutingResumeStore(config),sourceExpiry=await raw.pExpireTime(resumeKeys.routingDecision(jobId));const invalidResumeResult=await resumeStore.createAtomic({jobKey:resumeKeys.job(jobId),routingKey:resumeKeys.routingDecision(jobId),routingIdKey:resumeKeys.routingDecisionId(binding.record.decision.decision_id),requestKey:resumeKeys.wakeRequest(request.wake_request_id),executionKey:resumeKeys.wakeExecution(request.wake_request_id),confirmationKey:resumeKeys.wakeConfirmation(request.wake_request_id),workerKey:resumeKeys.worker(workerId),resumeKey:invalidResumeKey,newResumeIdKey:invalidResumeIdKey,resumeIdKeyPrefix:`${prefix}:routing-resume-id:`,serialized:JSON.stringify(invalidResume),expiresAt:invalidResume.expires_at,jobId,requestId,decisionId:binding.record.decision.decision_id,wakeRequestId:request.wake_request_id,executionId:executed.execution.execution_id,confirmationId:confirmation.confirmation.confirmation_id,targetWorkerId:workerId,capability:"heavy_reasoning",expiresAtMs:Math.min(Date.now()+30000,sourceExpiry),newResumeId:invalidResumeId,workerHeartbeatAt:heartbeat.worker.last_heartbeat_at,workerHeartbeatAtMs:Date.parse(heartbeat.worker.last_heartbeat_at),jobExpiresAt:envelope.runtime.expires_at,jobExpiresAtMs:Date.parse(envelope.runtime.expires_at),routingExpiresAt:binding.record.expires_at,routingExpiresAtMs:Date.parse(binding.record.expires_at)});const invalidResumeAbsent=(await raw.get(invalidResumeKey))===null&&(await raw.get(invalidResumeIdKey))===null;
  const ttlDecisionId=`decision-ttl-${uid}`,ttlBindingKey=`${prefix}:routing-decision-ttl:${jobId}`,ttlDecisionKey=resumeKeys.routingDecisionId(ttlDecisionId),ttlBinding=structuredClone(binding.record);ttlBinding.decision.decision_id=ttlDecisionId;cleanup.add(ttlBindingKey);cleanup.add(ttlDecisionKey);await raw.set(ttlBindingKey,JSON.stringify(ttlBinding),{PXAT:Date.parse(ttlBinding.expires_at)});await raw.set(ttlDecisionKey,jobId,{PXAT:Date.parse(ttlBinding.expires_at)});await raw.persist(ttlDecisionKey);const ttlBindingStore=await createHermesCanonicalRoutingStore(config);const routingTtlReplay=await ttlBindingStore.persistAtomic({jobKey:resumeKeys.job(jobId),recordKey:ttlBindingKey,decisionIdKey:ttlDecisionKey,decisionIdKeyPrefix:`${prefix}:routing-decision-id:`,jobId,requestId,decisionId:ttlDecisionId,serialized:JSON.stringify(ttlBinding),expiresAtMs:Date.parse(ttlBinding.expires_at),jobExpiresAt:envelope.runtime.expires_at});await ttlBindingStore.disconnect();
  const ttlResumeId=`resume-ttl-${uid}`,ttlResumeKey=`${prefix}:routing-resume-ttl:${jobId}`,ttlResumeIdKey=resumeKeys.resumeId(ttlResumeId),ttlResume=structuredClone(a.resume),ttlResumeExpiry=Math.min(Date.now()+30000,sourceExpiry);ttlResume.resume_id=ttlResumeId;ttlResume.expires_at=new Date(ttlResumeExpiry).toISOString();cleanup.add(ttlResumeKey);cleanup.add(ttlResumeIdKey);await raw.set(ttlResumeKey,JSON.stringify(ttlResume),{PXAT:ttlResumeExpiry});await raw.set(ttlResumeIdKey,jobId,{PXAT:ttlResumeExpiry+1000});const resumeTtlReplay=await resumeStore.replayAtomic({jobKey:resumeKeys.job(jobId),routingKey:resumeKeys.routingDecision(jobId),routingIdKey:resumeKeys.routingDecisionId(binding.record.decision.decision_id),requestKey:resumeKeys.wakeRequest(request.wake_request_id),executionKey:resumeKeys.wakeExecution(request.wake_request_id),confirmationKey:resumeKeys.wakeConfirmation(request.wake_request_id),resumeKey:ttlResumeKey,resumeIdKeyPrefix:`${prefix}:routing-resume-id:`,jobId,requestId,decisionId:binding.record.decision.decision_id,wakeRequestId:request.wake_request_id,executionId:executed.execution.execution_id,confirmationId:confirmation.confirmation.confirmation_id,targetWorkerId:workerId,capability:"heavy_reasoning",jobExpiresAtMs:Date.parse(envelope.runtime.expires_at),routingExpiresAtMs:Date.parse(binding.record.expires_at)});await resumeStore.disconnect();
  const invalidInitialRejected=invalidInitial.status==="routing_resume_original_decision_invalid",invalidResumeRejected=invalidResumeResult.status==="routing_resume_record_invalid",routingTtlRejected=routingTtlReplay.status==="routing_resume_record_invalid",resumeTtlRejected=resumeTtlReplay.status==="routing_resume_record_invalid";if(!invalidInitialRejected||!invalidInitialAbsent||!invalidResumeRejected||!invalidResumeAbsent||!routingTtlRejected||!resumeTtlRejected)throw new Error("integration_corruption_validation_failed");
  console.log(JSON.stringify({result:"ok",initial_routing_binding_created:binding.status==="created",wake_request_created:wake.status==="requested",wake_execution_sent_with_fake_sender:true,wake_confirmation_ready:true,routing_resume_created:true,manual_raw_routing_seed:false,manual_raw_wake_seed:false,manual_raw_execution_seed:false,manual_raw_confirmation_seed:false,invalid_initial_binding_rejected:invalidInitialRejected,invalid_initial_binding_record_absent:(await raw.get(invalidBindingKey))===null,invalid_initial_binding_id_key_absent:(await raw.get(invalidDecisionKey))===null,invalid_resume_rejected:invalidResumeRejected,invalid_resume_record_absent:(await raw.get(invalidResumeKey))===null,invalid_resume_id_key_absent:(await raw.get(invalidResumeIdKey))===null,routing_decision_id_ttl_corruption_rejected:routingTtlRejected,resume_id_ttl_corruption_rejected:resumeTtlRejected,concurrent_created_count:created.length,concurrent_already_exists_count:replayed.length,concurrent_canonical_id_equal:a.resume.resume_id===b.resume.resume_id,concurrent_record_count:recordCount,concurrent_id_key_consistent:idConsistent,concurrent_ttl_extended:ttlAfter>ttlBefore,canonical_replay_summary_equal:true,queue_write_performed:false,worker_claim_performed:false,model_execution_performed:false,udp_sent:false},null,2));
  } finally {
    if(cleanup.size)await raw.del([...cleanup]);
    if(raw.isOpen)await raw.quit();
    console.log(JSON.stringify({cleanup_performed:true,cleanup_scope:"unique_day105_prefix_known_keys_only",flush_performed:false}));
  }
}
main().catch(e=>{console.error(e instanceof Error?e.message:"routing_resume_smoke_failed");process.exitCode=1});
