import assert from "node:assert/strict";
import { pathToFileURL } from "node:url";
import { serveHermesDailyFarmBriefProposalReviewDetail,serveHermesDailyFarmBriefProposalReviewList,type HermesDailyFarmBriefProposalReviewServiceDependencies } from "./brief_runtime/hermes_daily_farm_brief_proposal_review_service";
import { createHermesDailyFarmBriefProposalSafeReference } from "../../src/lib/hermes/hermes_daily_farm_brief_proposal_review_read_boundary";
import type { HermesDailyFarmBriefProposalReviewReadRepository } from "../../src/lib/hermes/hermes_daily_farm_brief_proposal_review_postgres_repository";

const KEY="sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
export function createDay127ApiTestRow(){return {id:"14711111-88db-41fd-a048-1c37266fd9e1",proposal_type:"work_log_follow_up",title:"作業記録の確認が必要です",body:"対象: Field (redacted identifier)\n確認理由: 作業開始日時の形式を確認してください。",payload_json:{schema_version:"hermes.daily_farm_brief.proposal_inbox_record.v1",boundary:"day126_daily_farm_brief_explicit_save",candidate_id:"proposal_candidate_aaaaaaaaaaaaaaaaaaaaaaaa",proposal_type:"work_log_follow_up",target:{target_kind:"work_log_follow_up",safe_scope:"scope_field_aaaaaaaaaaaaaaaaaaaaaaaa",display_label:"Field (redacted identifier)",work_type_label:"水かけ"},basis:"作業開始日時の形式を確認してください。",before:"作業日を確認できません",after:"作業記録一覧で確認してください",risk_level:"low",source_business_date:"2026-07-17",source_generated_at:"2026-07-17T21:00:00.000Z",source_version:1,expected_source_version:1,created_at:"2026-07-17T21:05:00.000Z",expires_at:"2026-07-19T21:05:00.000Z",requires_human_review:true,duplicate_signature:"sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",idempotency_key:KEY,explicit_save_requested:true,proposal_apply_ready:false,proposal_apply_performed:false,app_db_write_performed:false},source_refs_json:{source:"daily_farm_brief_attention",boundary:"day126_daily_farm_brief_explicit_save",candidate_id:"proposal_candidate_aaaaaaaaaaaaaaaaaaaaaaaa",duplicate_signature:"sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",idempotency_key:KEY,source_business_date:"2026-07-17",source_version:1},model_name:null,agent_name:"hermes",confidence:null,reason:"作業開始日時の形式を確認してください。",risk_level:"low",status:"pending",reviewed_by:null,reviewed_at:null,review_note:null,applied_at:null,applied_by:null,created_at:"2026-07-17T21:05:00.000Z",updated_at:"2026-07-17T21:05:00.000Z"};}
const AUTH={schema_version:"hermes.daily_farm_brief.authentication_result.v1",status:"authenticated",principal_ref:"admin_fixture"};
const ADMIN={schema_version:"hermes.daily_farm_brief.authenticated_actor_context.v1",principal_ref:"admin_fixture",role:"administrator",allowed_scope_keys:[],authorization_verified:true};
const STAFF={...ADMIN,role:"general_staff",allowed_scope_keys:["scope_field_aaaaaaaaaaaaaaaaaaaaaaaa"]};
class Repo implements HermesDailyFarmBriefProposalReviewReadRepository{limit:number|null=null;constructor(public rows:unknown[],public found:unknown|null=createDay127ApiTestRow(),public failure=false){}async listDailyBriefProposalRows(limit:number){this.limit=limit;if(this.failure)throw new Error("raw-sensitive-database-error");return this.rows as ReturnType<typeof createDay127ApiTestRow>[];}async findDailyBriefProposalRowBySafeReference(){if(this.failure)throw new Error("raw-sensitive-database-error");return this.found as ReturnType<typeof createDay127ApiTestRow>|null;}}
function deps(repo:Repo|null,actor:unknown=ADMIN,authentication:unknown=AUTH):HermesDailyFarmBriefProposalReviewServiceDependencies{return{authenticate:async()=>authentication,resolveActorContext:async()=>actor,readRepository:async()=>repo,clock:()=>"2026-07-18T04:00:00.000Z"};}
async function json(response:Response){return JSON.parse(await response.text()) as Record<string,unknown>;}
export async function runDay127ProposalReviewServiceTests(){const row=createDay127ApiTestRow();const ref=createHermesDailyFarmBriefProposalSafeReference(KEY);const repo=new Repo([row]);
  const list=await serveHermesDailyFarmBriefProposalReviewList({request:new Request("http://local/api/hermes/daily-farm-brief/proposals"),dependencies:deps(repo)});assert.equal(list.status,200);assert.equal(repo.limit,100);const listBody=await json(list);assert.equal(listBody.result,"ok");assert(!JSON.stringify(listBody).includes(row.id));assert(!JSON.stringify(listBody).includes("admin_fixture"));
  const empty=await serveHermesDailyFarmBriefProposalReviewList({request:new Request("http://local/api/hermes/daily-farm-brief/proposals"),dependencies:deps(new Repo([]))});assert.equal(empty.status,200);
  const unauth=await serveHermesDailyFarmBriefProposalReviewList({request:new Request("http://local/api/hermes/daily-farm-brief/proposals"),dependencies:deps(repo,ADMIN,{schema_version:"hermes.daily_farm_brief.authentication_result.v1",status:"unauthenticated",principal_ref:null})});assert.equal(unauth.status,401);
  const staff=await serveHermesDailyFarmBriefProposalReviewList({request:new Request("http://local/api/hermes/daily-farm-brief/proposals"),dependencies:deps(repo,STAFF)});assert.equal(staff.status,403);
  const mismatch=await serveHermesDailyFarmBriefProposalReviewList({request:new Request("http://local/api/hermes/daily-farm-brief/proposals"),dependencies:deps(repo,{...ADMIN,principal_ref:"other_admin"})});assert.equal(mismatch.status,403);
  const invalidActor=await serveHermesDailyFarmBriefProposalReviewList({request:new Request("http://local/api/hermes/daily-farm-brief/proposals"),dependencies:deps(repo,{...ADMIN,unknown:true})});assert.equal(invalidActor.status,403);
  assert.equal((await serveHermesDailyFarmBriefProposalReviewList({request:new Request("http://local/api/hermes/daily-farm-brief/proposals",{method:"POST"}),dependencies:deps(repo)})).status,405);
  assert.equal((await serveHermesDailyFarmBriefProposalReviewList({request:new Request("http://local/api/hermes/daily-farm-brief/proposals?limit=1"),dependencies:deps(repo)})).status,400);
  assert.equal((await serveHermesDailyFarmBriefProposalReviewList({request:new Request("http://local/api/hermes/daily-farm-brief/proposals"),dependencies:deps(null)})).status,503);
  const failed=await serveHermesDailyFarmBriefProposalReviewList({request:new Request("http://local/api/hermes/daily-farm-brief/proposals"),dependencies:deps(new Repo([],null,true))});assert.equal(failed.status,503);assert(!(await failed.text()).includes("raw-sensitive"));
  const bad=structuredClone(row);bad.payload_json.schema_version="unknown";assert.equal((await serveHermesDailyFarmBriefProposalReviewList({request:new Request("http://local/api/hermes/daily-farm-brief/proposals"),dependencies:deps(new Repo([bad]))})).status,503);
  const detail=await serveHermesDailyFarmBriefProposalReviewDetail({request:new Request(`http://local/api/hermes/daily-farm-brief/proposals/${ref}`),dependencies:deps(repo)});assert.equal(detail.status,200);const detailBody=await json(detail);assert.equal(detailBody.result,"ok");assert(!JSON.stringify(detailBody).includes(row.id));assert(!JSON.stringify(detailBody).includes(KEY));
  for(const invalid of [row.id,"bad-reference"]){assert.equal((await serveHermesDailyFarmBriefProposalReviewDetail({request:new Request(`http://local/api/hermes/daily-farm-brief/proposals/${invalid}`),dependencies:deps(repo)})).status,400);}
  assert.equal((await serveHermesDailyFarmBriefProposalReviewDetail({request:new Request(`http://local/api/hermes/daily-farm-brief/proposals/${ref}`),dependencies:deps(new Repo([],null))})).status,404);
  assert.equal((await serveHermesDailyFarmBriefProposalReviewDetail({request:new Request(`http://local/api/hermes/daily-farm-brief/proposals/${ref}`),dependencies:deps(repo,ADMIN,{schema_version:"hermes.daily_farm_brief.authentication_result.v1",status:"unauthenticated",principal_ref:null})})).status,401);
  assert.equal((await serveHermesDailyFarmBriefProposalReviewDetail({request:new Request(`http://local/api/hermes/daily-farm-brief/proposals/${ref}`),dependencies:deps(repo,STAFF)})).status,403);
  assert.equal((await serveHermesDailyFarmBriefProposalReviewDetail({request:new Request(`http://local/api/hermes/daily-farm-brief/proposals/${ref}`),dependencies:deps(null)})).status,503);
  assert.equal((await serveHermesDailyFarmBriefProposalReviewDetail({request:new Request(`http://local/api/hermes/daily-farm-brief/proposals/${ref}`),dependencies:deps(new Repo([],null,true))})).status,503);
  const other=structuredClone(row);other.source_refs_json.idempotency_key="sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc";other.payload_json.idempotency_key=other.source_refs_json.idempotency_key;assert.equal((await serveHermesDailyFarmBriefProposalReviewDetail({request:new Request(`http://local/api/hermes/daily-farm-brief/proposals/${ref}`),dependencies:deps(new Repo([],other))})).status,503);
  assert.equal(list.headers.get("cache-control"),"no-store");assert.equal(list.headers.get("content-type"),"application/json; charset=utf-8");
  return {result:"pass",list_status:200,detail_status:200,administrator_allowed:true,general_staff_forbidden:true,repository_limit:repo.limit,raw_identifier_exposed:false,principal_ref_exposed:false,database_write_performed:false,retry_count:0};}
if(import.meta.url===pathToFileURL(process.argv[1]??"").href)console.log(JSON.stringify(await runDay127ProposalReviewServiceTests()));
