import assert from "node:assert/strict";
import { parseFarmOsApprovedProposal,parseFarmOsApprovedProposalJson } from "../../src/lib/hermes/farm_os_approved_proposal_contract";
import { approvedProposalFixture } from "./farm_os_day132_fixture";
const p=approvedProposalFixture();const assertions:Record<string,boolean>={};const check=(name:string,value:boolean)=>{assertions[name]=value;assert.equal(value,true,name);};
check("approved",parseFarmOsApprovedProposal(p).valid);
check("pending_rejected",parseFarmOsApprovedProposal({...p,review_result:"pending"}).blocked_reason==="PROPOSAL_NOT_APPROVED");
check("unknown_proposal",parseFarmOsApprovedProposal({...p,proposal_type:"unknown"}).blocked_reason==="PROPOSAL_TYPE_UNKNOWN");
check("missing_approval",parseFarmOsApprovedProposal({...p,approval_evidence:null}).blocked_reason==="APPROVAL_EVIDENCE_MISSING");
const {approval_evidence:ignoredApproval,...withoutApproval}=p;void ignoredApproval;check("omitted_approval",parseFarmOsApprovedProposal(withoutApproval).blocked_reason==="APPROVAL_EVIDENCE_MISSING");
check("hash_invalid",parseFarmOsApprovedProposal({...p,approval_evidence:{...p.approval_evidence,proposal_hash:`sha256:${"b".repeat(64)}`}}).blocked_reason==="PROPOSAL_HASH_INVALID");
check("unknown_field",parseFarmOsApprovedProposal({...p,unknown:true}).blocked_reason==="UNKNOWN_FIELD");
const raw=JSON.stringify(p);const duplicate=raw.replace('"proposal_id":','"proposal_id":"proposal_duplicate_day132","proposal_id":');
check("raw_valid",parseFarmOsApprovedProposalJson(raw).valid);check("duplicate",parseFarmOsApprovedProposalJson(duplicate).blocked_reason==="DUPLICATE_FIELD");
console.log(JSON.stringify({assertions,assertion_count:Object.keys(assertions).length}));
