import assert from "node:assert/strict";
import { applyConfirmationTaskDraftDryRun, computeConfirmationTaskCandidateSnapshotHash, computeConfirmationTaskRequestFingerprint, FARM_OS_CONFIRMATION_TASK_APPLY_REGISTRY, InMemoryConfirmationTaskApplyStore, parseConfirmationTaskDraft } from "../../src/lib/hermes/farm_os_confirmation_task_apply_contract";
import { DAY136_VALID_FIXTURES } from "./farm_os_day136_fixture";
import { createDay137Request, DAY137_CANDIDATE, DAY137_HERMES_CANDIDATE, DAY137_NOW } from "./farm_os_day137_fixture";

const passed: string[] = [];
const check = (id: string, value: boolean) => { assert.equal(value, true, id); passed.push(id); };
const run = (candidate: unknown, request: unknown, store = new InMemoryConfirmationTaskApplyStore(), authorityRequest = request) => applyConfirmationTaskDraftDryRun({
  candidate, request, store, now: DAY137_NOW,
  authority_port: { getAuthority: async () => {
    const trusted = authorityRequest as ReturnType<typeof createDay137Request>;
    return { approval: trusted.approval_evidence, reauthorization: trusted.reauthorization_evidence, runtime_context: trusted.runtime_context, approval_actor_type: "human", approval_source: "human_review_ledger" };
  } },
});
const code = async (candidate: unknown, request: unknown) => (await run(candidate, request)).result.rejection_code;
const validNative = await run(DAY137_CANDIDATE, createDay137Request());
check("A_native_dry_run_ready", validNative.result.result === "dry_run_ready" && validNative.task_draft?.status === "draft");
const validHermes = await run(DAY137_HERMES_CANDIDATE, createDay137Request(DAY137_HERMES_CANDIDATE));
check("B_hermes_candidate_human_approved", validHermes.result.result === "dry_run_ready");
const replayStore = new InMemoryConfirmationTaskApplyStore(), replayRequest = createDay137Request();
check("C_first_processed", (await run(DAY137_CANDIDATE, replayRequest, replayStore)).result.result === "dry_run_ready");
check("C_same_key_same_fingerprint", (await run(DAY137_CANDIDATE, replayRequest, replayStore)).result.result === "already_processed");
check("D_blocking_hint_true", validNative.task_draft?.blocking_hint === true);
const nonBlockingCandidate = { ...DAY137_CANDIDATE, candidate_id: "candidate-confirmation-task-nonblocking", payload: { ...DAY137_CANDIDATE.payload, blocking: false } };
check("E_blocking_hint_false", (await run(nonBlockingCandidate, createDay137Request(nonBlockingCandidate))).task_draft?.blocking_hint === false);
for (const [id, candidate] of Object.entries({ F: { ...DAY136_VALID_FIXTURES.A, status: "review_ready" }, G: { ...DAY136_VALID_FIXTURES.D, status: "review_ready" }, H: { ...DAY136_VALID_FIXTURES.E, status: "review_ready" } })) check(`${id}_unsupported_kind`, await code(candidate, createDay137Request()) === "unsupported_candidate_kind");
check("I_expired", await code({ ...DAY137_CANDIDATE, expires_at: "2026-07-23T01:00:00.000Z" }, createDay137Request()) === "candidate_expired");
check("J_superseded", await code({ ...DAY137_CANDIDATE, status: "superseded" }, createDay137Request()) === "candidate_superseded");
check("K_rejected", await code({ ...DAY137_CANDIDATE, status: "rejected" }, createDay137Request()) === "candidate_rejected");
check("L_snapshot_mismatch", await code(DAY137_CANDIDATE, { ...createDay137Request(), candidate_snapshot_hash: `sha256:${"0".repeat(64)}` }) === "candidate_hash_mismatch");
check("M_approval_missing", await code(DAY137_CANDIDATE, { ...createDay137Request(), approval_evidence: null }) === "approval_missing");
check("N_not_approved", await code(DAY137_CANDIDATE, { ...createDay137Request(), approval_evidence: { ...createDay137Request().approval_evidence, decision: "rejected" } }) === "approval_not_approved");
check("O_approval_candidate_mismatch", await code(DAY137_CANDIDATE, { ...createDay137Request(), approval_evidence: { ...createDay137Request().approval_evidence, candidate_id: "candidate-other" } }) === "approval_candidate_mismatch");
check("P_approval_hash_mismatch", await code(DAY137_CANDIDATE, { ...createDay137Request(), approval_evidence: { ...createDay137Request().approval_evidence, candidate_snapshot_hash: `sha256:${"1".repeat(64)}` } }) === "approval_hash_mismatch");
check("Q_reviewer_capability", await code(DAY137_CANDIDATE, { ...createDay137Request(), approval_evidence: { ...createDay137Request().approval_evidence, reviewer_capability: "unknown" } }) === "reviewer_capability_invalid");
check("R_self_approval", await code(DAY137_CANDIDATE, { ...createDay137Request(), approval_evidence: { ...createDay137Request().approval_evidence, decided_by: "actor-day137" } }) === "self_approval_not_allowed");
check("S_reauth_missing", await code(DAY137_CANDIDATE, { ...createDay137Request(), reauthorization_evidence: null }) === "reauthorization_missing");
check("T_reauth_expired", await code(DAY137_CANDIDATE, { ...createDay137Request(), reauthorization_evidence: { ...createDay137Request().reauthorization_evidence, expires_at: "2026-07-23T01:59:00.000Z" } }) === "reauthorization_expired");
check("U_actor_inactive", await code(DAY137_CANDIDATE, { ...createDay137Request(), reauthorization_evidence: { ...createDay137Request().reauthorization_evidence, actor_status: "inactive" } }) === "actor_inactive");
check("V_scope_mismatch", await code(DAY137_CANDIDATE, { ...createDay137Request(), reauthorization_evidence: { ...createDay137Request().reauthorization_evidence, scope: "wrong-scope" } }) === "scope_mismatch");
check("W_policy_stale", await code(DAY137_CANDIDATE, { ...createDay137Request(), reauthorization_evidence: { ...createDay137Request().reauthorization_evidence, policy_version: "old" } }) === "policy_version_stale");
check("X_dry_run_false", await code(DAY137_CANDIDATE, { ...createDay137Request(), dry_run: false }) === "dry_run_required");
const conflictStore = new InMemoryConfirmationTaskApplyStore(), first = createDay137Request();
await run(DAY137_CANDIDATE, first, conflictStore);
check("Y_idempotency_conflict", (await run(DAY137_CANDIDATE, { ...first, apply_request_id: "apply-conflict" }, conflictStore)).result.rejection_code === "idempotency_conflict");
const duplicateStore = new InMemoryConfirmationTaskApplyStore(); await run(DAY137_CANDIDATE, first, duplicateStore);
check("Z_duplicate_apply", (await run(DAY137_CANDIDATE, { ...first, idempotency_key: "idempotency-other" }, duplicateStore)).result.rejection_code === "duplicate_apply_rejected");
check("AA_draft_unknown_key", parseConfirmationTaskDraft({ ...validNative.task_draft!, unknown: true }) === null);
check("AB_draft_status", parseConfirmationTaskDraft({ ...validNative.task_draft!, status: "open" }) === null);
check("AC_business_write", await code(DAY137_CANDIDATE, { ...createDay137Request(), business_write_attempt: true }) === "business_write_attempt_detected");
check("AD_external_side_effect", await code(DAY137_CANDIDATE, { ...createDay137Request(), notification_send_requested: true }) === "external_side_effect_attempt_detected");
check("AE_hermes_approval_injection", await code(DAY137_CANDIDATE, { ...createDay137Request(), approval_generated_by: "hermes" }) === "unknown_field");
check("AF_hermes_actor_injection", await code(DAY137_CANDIDATE, { ...createDay137Request(), actor_selected_by: "hermes" }) === "unknown_field");
check("hermes_decided_by_rejected", await code(DAY137_CANDIDATE, { ...createDay137Request(), approval_evidence: { ...createDay137Request().approval_evidence, decided_by: "hermes" } }) === "self_approval_not_allowed");
const forged = { ...createDay137Request(), approval_evidence: { ...createDay137Request().approval_evidence, reason: "Forged but structurally valid." } };
check("authority_mismatch_rejected", (await run(DAY137_CANDIDATE, forged, new InMemoryConfirmationTaskApplyStore(), createDay137Request())).result.rejection_code === "approval_authority_mismatch");
check("audit_trace_mismatch", await code(DAY137_CANDIDATE, { ...createDay137Request(), correlation_id: "correlation-forged" }) === "audit_correlation_mismatch");
check("proposal_ref_unknown_key", await code(DAY137_CANDIDATE, { ...createDay137Request(), proposal_ref: { ...createDay137Request().proposal_ref, unexpected: true } }) === "unknown_field");
check("future_requested_at", await code(DAY137_CANDIDATE, { ...createDay137Request(), requested_at: "2026-07-23T03:00:00.000Z" }) === "reauthorization_expired");
const authorityFailure = await applyConfirmationTaskDraftDryRun({ candidate: DAY137_CANDIDATE, request: createDay137Request(), store: new InMemoryConfirmationTaskApplyStore(), now: DAY137_NOW, authority_port: { getAuthority: async () => { throw new Error("fixture"); } } });
check("authority_failure_audited", authorityFailure.result.rejection_code === "approval_missing" && authorityFailure.audit.apply_result === "rejected");
check("candidate_hash_deterministic", computeConfirmationTaskCandidateSnapshotHash(DAY137_CANDIDATE) === computeConfirmationTaskCandidateSnapshotHash(DAY137_CANDIDATE));
check("payload_hash_changes", computeConfirmationTaskCandidateSnapshotHash({ ...DAY137_CANDIDATE, payload: { ...DAY137_CANDIDATE.payload, question: "Changed?" } }) !== computeConfirmationTaskCandidateSnapshotHash(DAY137_CANDIDATE));
check("fingerprint_digest", computeConfirmationTaskRequestFingerprint(createDay137Request()).startsWith("sha256:"));
check("registry_safe", FARM_OS_CONFIRMATION_TASK_APPLY_REGISTRY.dry_run_only && !FARM_OS_CONFIRMATION_TASK_APPLY_REGISTRY.business_write_allowed && !FARM_OS_CONFIRMATION_TASK_APPLY_REGISTRY.external_side_effect_allowed);
check("audit_correlation", validNative.audit.approval_actor === "reviewer-day137" && validNative.audit.request_actor === "actor-day137" && validNative.audit.correlation_id === DAY137_CANDIDATE.correlation_id);
check("zero_side_effects", !validNative.audit.business_write_attempted && !validNative.audit.business_write_performed && !validNative.audit.external_side_effect_attempted && !validNative.audit.external_side_effect_performed);
check("evolution_no_auto_adoption", !validNative.evolution.automatic_policy_adoption && !validNative.evolution.automatic_skill_adoption && !validNative.evolution.automatic_production_enablement);
console.log(JSON.stringify({ schema_version: "farmos.day137.fixture-report.v1", fixture_count: 32, assertion_count: passed.length, pass_count: passed.length, fail_count: 0, command_generation_count: 0, execution_gateway_production_call_count: 0, business_write_count: 0, external_side_effect_count: 0, assertions: passed }));
