import assert from "node:assert/strict";
import { existsSync,readFileSync } from "node:fs";
import path from "node:path";
import ts from "typescript";
import { FARM_OS_EXECUTION_ADAPTER_REGISTRY } from "../../src/lib/hermes/farm_os_execution_adapter_registry";

const root=process.cwd();
const entries=[
  "src/lib/hermes/farm_os_execution_gateway.ts",
  "src/lib/hermes/farm_os_runtime_reauthorization.ts",
  "src/lib/hermes/farm_os_runtime_governance_gate.ts",
  "src/lib/hermes/farm_os_execution_reservation_port.ts",
  "src/lib/hermes/farm_os_in_memory_execution_reservation_repository.ts",
  "src/lib/hermes/farm_os_fake_execution_adapter.ts",
] as const;
const allowedExternal=new Set(["node:crypto"]);
const forbiddenModule=/(?:postgres|supabase|redis|database|db[_-]?repository|node:fs|node:net|node:http|node:https|child_process|runtime[_-]?tool|proposal[_-]?apply|review[_-]?post|route|migration|secret|real[_-]?adapter)/iu;
const forbiddenCall=/^(?:fetch|axios|connect|query|save|insert|update|delete|remove|call|dispatch|apply|mutate|send|write|writeFile|writeFileSync|appendFile|appendFileSync|spawn|exec|execFile|eval|Function)$/u;
type Findings={forbidden_dependencies:string[];forbidden_calls:string[];dynamic_imports:string[];forbidden_references:string[]};
const findings=():Findings=>({forbidden_dependencies:[],forbidden_calls:[],dynamic_imports:[],forbidden_references:[]});
const resolveLocal=(from:string,specifier:string)=>{const base=path.resolve(path.dirname(from),specifier);return[base,`${base}.ts`,path.join(base,"index.ts")].find(existsSync)??null;};
function inspectAst(file:string,source:string,result:Findings,follow:(file:string)=>void){const ast=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);const inspectModule=(specifier:string)=>{if(specifier.startsWith(".")){const local=resolveLocal(file,specifier);if(!local||forbiddenModule.test(specifier)||forbiddenModule.test(local))result.forbidden_dependencies.push(`${file}:${specifier}`);else follow(local);}else if(!allowedExternal.has(specifier)||forbiddenModule.test(specifier))result.forbidden_dependencies.push(`${file}:${specifier}`);};const visit=(node:ts.Node)=>{if((ts.isImportDeclaration(node)||ts.isExportDeclaration(node))&&node.moduleSpecifier&&ts.isStringLiteral(node.moduleSpecifier))inspectModule(node.moduleSpecifier.text);if(ts.isImportEqualsDeclaration(node)&&ts.isExternalModuleReference(node.moduleReference)&&node.moduleReference.expression&&ts.isStringLiteral(node.moduleReference.expression))inspectModule(node.moduleReference.expression.text);if(ts.isCallExpression(node)){const expression=node.expression,text=expression.getText(ast);if(expression.kind===ts.SyntaxKind.ImportKeyword||text==="require")result.dynamic_imports.push(`${file}:${text}`);const terminal=ts.isPropertyAccessExpression(expression)?expression.name.text:ts.isElementAccessExpression(expression)&&ts.isStringLiteral(expression.argumentExpression)?expression.argumentExpression.text:ts.isIdentifier(expression)?expression.text:"";const safeHash=terminal==="update"&&ts.isPropertyAccessExpression(expression)&&/^createHash\(/u.test(expression.expression.getText(ast));const knownPure=/^(?:executeFarmOsFakeAdapter|executeFarmOsExecutionGateway|executeFarmOsIdempotentGateway|evaluateFarmOsRuntimeGovernance|evaluateFarmOsRuntimeGovernanceGate)$/u.test(terminal);if(forbiddenCall.test(terminal)&&!safeHash&&!knownPure)result.forbidden_calls.push(`${file}:${text}`);}if(ts.isIdentifier(node)&&/^(?:fetch|axios|eval|Function)$/u.test(node.text)){const declaration=(ts.isFunctionDeclaration(node.parent)||ts.isVariableDeclaration(node.parent)||ts.isImportSpecifier(node.parent))&&node.parent.name===node;if(!declaration)result.forbidden_references.push(`${file}:${node.text}`);}ts.forEachChild(node,visit);};visit(ast);}
const visited=new Set<string>(),production=findings();const follow=(file:string)=>{const absolute=path.resolve(file);if(visited.has(absolute))return;visited.add(absolute);inspectAst(absolute,readFileSync(absolute,"utf8"),production,follow);};for(const entry of entries)follow(path.join(root,entry));
const fixtureCases={direct_fetch:"fetch('https://example.invalid')",aliased_fetch:"const request=fetch; request('https://example.invalid')",node_http_import:"import http from 'node:http'",dynamic_import:"void import('./runtime_tool')",child_process:"import {spawn} from 'node:child_process'; spawn('x')",filesystem_write:"import {writeFileSync} from 'node:fs'; writeFileSync('/tmp/x','x')",forbidden_repository_import:"import repo from './postgres_repository'",arbitrary_call:"handler.call(null)",computed_call:"handler['call'](null)",real_adapter_import:"import adapter from './real_execution_adapter'",forbidden_reexport:"export {adapter} from './real_execution_adapter'"};const fixtureDetection:Record<string,boolean>={};for(const [name,source] of Object.entries(fixtureCases)){const result=findings();inspectAst(path.join(root,`scripts/hermes/${name}.ts`),source,result,()=>{});fixtureDetection[name]=Object.values(result).some((items)=>items.length>0);assert.equal(fixtureDetection[name],true,name);}
const noForbidden=Object.values(production).every((items)=>items.length===0),adapters=Object.values(FARM_OS_EXECUTION_ADAPTER_REGISTRY),result={dependency_boundary_valid:noForbidden,recursive_ast_traversal_valid:visited.size>entries.length,reexport_traversal_valid:fixtureDetection.forbidden_reexport,alias_call_detection_valid:fixtureDetection.aliased_fetch,member_call_detection_valid:fixtureDetection.arbitrary_call,computed_call_detection_valid:fixtureDetection.computed_call,fixture_detection_valid:Object.values(fixtureDetection).every(Boolean),fake_adapter_only:adapters.length===1&&adapters.every((adapter)=>adapter.fake_only&&!adapter.business_write_allowed&&!adapter.external_execution_allowed),business_write_path_absent:noForbidden,external_execution_path_absent:noForbidden,proposal_apply_path_absent:noForbidden,db_mutation_path_absent:noForbidden,network_path_absent:noForbidden,filesystem_write_path_absent:noForbidden,real_adapter_path_absent:noForbidden,inspected_files:[...visited].map((file)=>path.relative(root,file)).sort(),fixture_detection:fixtureDetection,...production};console.log(JSON.stringify(result));for(const [name,value] of Object.entries(result).filter(([,value])=>typeof value==="boolean"))assert.equal(value,true,name);
