import assert from "node:assert/strict";
import { buildFarmOsApprovedCommand,parseFarmOsApprovedCommand,parseFarmOsCommandBuildRequest,type FarmOsCommandRejectionCode } from "../../src/lib/hermes/farm_os_approved_command_contract";
import { parseFarmOsApprovedProposal } from "../../src/lib/hermes/farm_os_approved_proposal_contract";
import { approvedProposalFixture,commandBuildRequestFixture } from "./farm_os_day132_fixture";
type Case={test_case_id:string;passed:boolean;expected:string;actual:string;assertion_count:number};const cases:Case[]=[];const counters={command_build_count:0,command_rejected_count:0,command_validation_count:0,gateway_call_count:0,internal_execution_count:0,external_execution_count:0,business_write_count:0,proposal_apply_count:0};
const record=(id:string,expected:string,actual:string,checks:boolean[])=>{for(const condition of checks)assert.equal(condition,true,id);cases.push({test_case_id:id,passed:checks.every(Boolean),expected,actual,assertion_count:checks.length});};
const build=(proposal:unknown,request:unknown)=>{counters.command_validation_count+=1;const result=buildFarmOsApprovedCommand({approved_proposal:proposal,build_request:request});if(result.result==="success")counters.command_build_count+=1;else counters.command_rejected_count+=1;counters.gateway_call_count+=result.gateway_call_count;counters.internal_execution_count+=result.internal_execution_count;counters.external_execution_count+=result.external_execution_count;counters.business_write_count+=result.business_write_count;counters.proposal_apply_count+=result.proposal_apply_count;return result;};
const code=(result:ReturnType<typeof buildFarmOsApprovedCommand>):FarmOsCommandRejectionCode|null=>result.result==="rejected"?result.rejection.code:null;const p=approvedProposalFixture(),r=commandBuildRequestFixture();
const a=parseFarmOsApprovedProposal(p);counters.command_validation_count+=1;record("A","approved_proposal",a.valid?"approved_proposal":a.blocked_reason,[a.valid]);
const b=build(p,r);record("B","approved_command",b.result==="success"?"approved_command":code(b)!,[b.result==="success"]);assert.equal(b.result,"success");
const c=build({...p,proposal_type:"unknown"},r);record("C","PROPOSAL_TYPE_UNKNOWN",code(c)!,[code(c)==="PROPOSAL_TYPE_UNKNOWN"]);
const d=build({...p,approval_evidence:null},r);record("D","APPROVAL_EVIDENCE_MISSING",code(d)!,[code(d)==="APPROVAL_EVIDENCE_MISSING"]);
const e=build(p,{...r,capabilities:["build_approved_command"]});record("E","REQUIRED_CAPABILITY_MISSING",code(e)!,[code(e)==="REQUIRED_CAPABILITY_MISSING"]);
const f=build({...p,risk_level:"l3_external_execution"},r);record("F","RISK_LEVEL_MISMATCH",code(f)!,[code(f)==="RISK_LEVEL_MISMATCH"]);
const duplicate=build(p,{...r,known_command_hashes:[b.command.idempotency.command_hash]});record("G","DUPLICATE_COMMAND",code(duplicate)!,[code(duplicate)==="DUPLICATE_COMMAND",build(p,r).command?.command_id===b.command.command_id]);
const h=build(p,{...r,unknown:true});record("H","UNKNOWN_FIELD",code(h)!,[code(h)==="UNKNOWN_FIELD"]);
const i=build(p,{...r,correlation_id:"correlation_wrong_day132"});record("I","TRACE_INVALID",code(i)!,[code(i)==="TRACE_INVALID"]);
const j=build(p,{...r,command_class:"unknown"});record("J","COMMAND_CLASS_UNKNOWN",code(j)!,[code(j)==="COMMAND_CLASS_UNKNOWN"]);
assert.equal(parseFarmOsApprovedCommand(b.command).valid,true);assert.equal(parseFarmOsCommandBuildRequest({...r,execution_target:"arbitrary_target"}).blocked_reason,"COMMAND_TARGET_NOT_ALLOWED");
for(const value of [counters.gateway_call_count,counters.internal_execution_count,counters.external_execution_count,counters.business_write_count,counters.proposal_apply_count])assert.equal(value,0);
console.log(JSON.stringify({schema_version:"farmos.day132.fixture.report.v1",cases,fixture_count:cases.length,fixture_pass_count:cases.filter((item)=>item.passed).length,fixture_fail_count:cases.filter((item)=>!item.passed).length,test_observed_counters:counters}));
