import assert from "node:assert/strict";
import { createHermesJobEnvelope } from "./job_runtime/hermes_job_envelope";
import type { HermesQueuedJobRecord } from "./queue_runtime/hermes_redis_queue_contract";
import { createHermesRoutingRequirement,routeHermesJob } from "./router_runtime/hermes_model_router";
import type { HermesRoutingDecision } from "./router_runtime/hermes_model_router_contract";
import { createHermesWorkerAdvertisement } from "./worker_runtime/hermes_worker_protocol";
import type { HermesWorkerRegistryRecord } from "./worker_runtime/hermes_worker_registry_contract";
import type { HermesWorkerWakeRequest } from "./startup_runtime/hermes_worker_startup_contract";
import type { HermesWakeExecutionRecord } from "./wake_runtime/hermes_wake_execution_contract";
import { createHermesWakeConfirmationRecord,createHermesWakeConfirmationRequirement,evaluateHermesWakeConfirmation } from "./confirmation_runtime/hermes_wake_confirmation_policy";
import { HERMES_ROUTING_RESUME_POLICY,parseHermesCanonicalRoutingDecision,parseHermesRoutingResumeRecord } from "./resume_runtime/hermes_routing_resume_policy";
import { resumeHermesPostWakeRouting } from "./resume_runtime/hermes_routing_resume_coordinator";
import { createHermesRoutingResumeKeys,type HermesRoutingResumeStore } from "./resume_runtime/hermes_routing_resume_store";
import { createCanonicalHermesInitialRouting } from "./resume_runtime/hermes_initial_routing_coordinator";
import type { HermesCanonicalRoutingStore } from "./resume_runtime/hermes_canonical_routing_decision_store";

const NOW="2026-07-15T01:00:10.000Z",JOB="job-resume-unit",REQUEST="request-resume-unit",WAKE="wake-resume-unit",WORKER="rtx-resume-unit";
const keys=createHermesRoutingResumeKeys("farmos:hermes:test:day105-unit");
class FakeStore implements HermesRoutingResumeStore{values=new Map<string,string>();expiries=new Map<string,number>();async get(k:string){return this.values.get(k)??null}async getExpiryTime(k:string){return this.expiries.get(k)??-2}async replayAtomic(i:any){const old=this.values.get(i.resumeKey);if(!old)return{status:"not_found",record:null};const c=parseHermesRoutingResumeRecord(old),idKey=c?`${i.resumeIdKeyPrefix}${c.resume_id}`:"";if(!c||this.values.get(idKey)!==c.job_id)return{status:"routing_resume_record_invalid",record:null};for(const [field,value]of [["job_id",i.jobId],["request_id",i.requestId],["original_routing_decision_id",i.decisionId],["wake_request_id",i.wakeRequestId],["wake_execution_id",i.executionId],["wake_confirmation_id",i.confirmationId],["target_worker_id",i.targetWorkerId],["required_capability",i.capability]])if((c as any)[field]!==value)return{status:"routing_resume_conflict",record:null};return{status:"already_exists",record:old}}async createAtomic(i:any){const old=this.values.get(i.resumeKey),next=JSON.parse(i.serialized);if(old){const c=parseHermesRoutingResumeRecord(old),idKey=c?`${i.resumeIdKeyPrefix}${c.resume_id}`:"";if(!c||this.values.get(idKey)!==c.job_id)return{status:"routing_resume_record_invalid",record:null};for(const f of["job_id","request_id","original_routing_decision_id","wake_request_id","wake_execution_id","wake_confirmation_id","target_worker_id","required_capability"]){if((c as any)[f]!==next[f])return{status:"routing_resume_conflict",record:null}}return{status:"already_exists",record:old}}const validated=parseHermesRoutingResumeRecord(i.serialized);if(!validated)return{status:"routing_resume_record_invalid",record:null};if(next.resume_id!==i.newResumeId||i.newResumeIdKey!==`${i.resumeIdKeyPrefix}${i.newResumeId}`||this.values.has(i.newResumeIdKey))return{status:"routing_resume_record_invalid",record:null};this.values.set(i.resumeKey,i.serialized);this.values.set(i.newResumeIdKey,i.jobId);this.expiries.set(i.resumeKey,i.expiresAtMs);this.expiries.set(i.newResumeIdKey,i.expiresAtMs);return{status:"created",record:i.serialized}}async deleteKeys(){}async disconnect(){}}
class FakeCanonicalStore implements HermesCanonicalRoutingStore{values=new Map<string,string>();expiries=new Map<string,number>();async get(k:string){return this.values.get(k)??null}async persistAtomic(i:any){const old=this.values.get(i.recordKey);if(old)return{status:"already_exists",record:old};const parsed=parseHermesCanonicalRoutingDecision(i.serialized);if(!parsed||parsed.job_id!==i.jobId||parsed.request_id!==i.requestId||parsed.decision.decision_id!==i.decisionId)return{status:"routing_resume_original_decision_invalid",record:null};this.values.set(i.recordKey,i.serialized);this.values.set(i.decisionIdKey,i.jobId);this.expiries.set(i.recordKey,i.expiresAtMs);this.expiries.set(i.decisionIdKey,i.expiresAtMs);return{status:"created",record:i.serialized}}async disconnect(){}}

function fixtures(over:{jobStatus?:string;decisionStatus?:string;requestStatus?:string;executionStatus?:string;confirmationStatus?:string;workerHeartbeat?:string;workerHealth?:"healthy"|"degraded"|"unhealthy"|"unknown";workerReady?:"ready"|"not_ready"|"draining"|"offline";runtime?:boolean;draining?:boolean;capacity?:boolean;capability?:"heavy_reasoning"|"gpu_inference";target?:string}={}){
  const jobEnvelope=createHermesJobEnvelope({requestId:REQUEST,payload:{message:"resume boundary fixture",include_readonly_context:false},jobIdFactory:()=>JOB,nowIsoFactory:()=>"2026-07-15T00:58:00.000Z"});(jobEnvelope.runtime as any).status=over.jobStatus??"queued";
  const job:HermesQueuedJobRecord={schema_version:"hermes.queue.v1",job:jobEnvelope,queue:{status:"queued",retry_count:0,max_retry_count:1,enqueued_at:"2026-07-15T00:58:00.000Z",dequeued_at:null,completed_at:null,last_error_code:null},safety:{db_write_performed:false,business_db_write_performed:false,proposal_write_performed:false,worker_execution_performed:false,model_execution_performed:false,fail_closed:true}};
  const requirement=createHermesRoutingRequirement({taskClass:"heavy_reasoning"});const offline=createHermesWorkerAdvertisement({workerId:WORKER,workerType:"rtx",capabilities:["heavy_reasoning"],health:"healthy",runtimeAvailable:false,draining:false,nowIso:"2026-07-15T00:59:00.000Z"});const original=routeHermesJob({requirement,workers:[{worker_id:offline.worker_id,worker_type:offline.worker_type,capabilities:offline.capabilities,health:offline.health,readiness:"not_ready",runtime_available:false,draining:false,last_heartbeat_at:offline.last_heartbeat_at,current_job_id:null,active_job_count:0,max_concurrency:1}],nowIso:"2026-07-15T00:59:00.000Z",decisionIdFactory:()=>"decision-resume-unit"});if(over.decisionStatus){(original as any).status=over.decisionStatus;(original as any).selected_worker=over.decisionStatus==="selected"?{worker_id:WORKER,worker_type:"rtx",matched_capability:"heavy_reasoning",active_job_count:0,max_concurrency:1}:null}
  const routing={schema_version:"hermes.router.decision.record.v1",job_id:JOB,request_id:REQUEST,expires_at:jobEnvelope.runtime.expires_at,decision:original};const target=over.target??WORKER;
  const request:HermesWorkerWakeRequest={schema_version:"hermes.worker.wake.request.v1",wake_request_id:WAKE,worker_type:"rtx",target_worker_id:target,routing_decision_id:original.decision_id,required_capability:"heavy_reasoning",reason_code:"required_worker_offline",requested_at:"2026-07-15T00:56:00.000Z",expires_at:"2026-07-15T01:01:00.000Z",cooldown_until:"2026-07-15T01:06:00.000Z",status:(over.requestStatus??"acknowledged") as any,requested_by:"server_policy",safety:{wol_packet_sent:false,ssh_connection_performed:false,gpu_detection_performed:false,worker_execution_performed:false,model_execution_performed:false,secret_stored:false,db_write_performed:false,fail_closed:true}};
  const execution:HermesWakeExecutionRecord={schema_version:"hermes.wake.execution.v1",execution_id:"execution-resume-unit",wake_request_id:WAKE,approval_id:"approval-resume-unit",routing_decision_id:original.decision_id,target_worker_id:target,transport:"udp_wol",status:(over.executionStatus??"sent") as any,reserved_at:"2026-07-15T00:59:59.000Z",completed_at:"2026-07-15T01:00:00.000Z",error_code:null,bytes_sent:102,safety:{network_target_stored:false,mac_address_stored:false,broadcast_address_stored:false,credentials_stored:false,ssh_connection_performed:false,remote_command_performed:false,gpu_detection_performed:false,model_execution_performed:false,db_write_performed:false,fail_closed:true}};if(execution.status==="failed"){execution.error_code="wake_signal_failed";execution.bytes_sent=null}
  const confirmationBase=createHermesWakeConfirmationRecord({requirement:createHermesWakeConfirmationRequirement({request:{...request,status:"acknowledged"},execution:{...execution,status:"sent",error_code:null,bytes_sent:102},nowIso:NOW}),nowIso:NOW,confirmationIdFactory:()=>"confirmation-resume-unit"});const current=createHermesWorkerAdvertisement({workerId:target,workerType:"rtx",capabilities:[over.capability??"heavy_reasoning"],health:over.workerHealth??"healthy",runtimeAvailable:over.runtime??true,draining:over.draining??false,nowIso:over.workerHeartbeat??"2026-07-15T01:00:09.000Z",currentJobId:over.capacity?"job-other":null,activeJobCount:over.capacity?1:0,maxConcurrency:1});current.readiness=over.workerReady??current.readiness;let confirmation=evaluateHermesWakeConfirmation({confirmation:confirmationBase,worker:createHermesWorkerAdvertisement({workerId:target,workerType:"rtx",capabilities:["heavy_reasoning"],health:"healthy",runtimeAvailable:true,draining:false,nowIso:"2026-07-15T01:00:09.000Z"}),nowIso:NOW}).record!;if(over.confirmationStatus)(confirmation as any).status=over.confirmationStatus;
  const registry:HermesWorkerRegistryRecord={schema_version:"hermes.worker.registry.v1",worker:current,registry:{registered:true,heartbeat_count:1,last_registered_at:current.registered_at,last_updated_at:current.last_heartbeat_at},safety:{redis_write_performed:true,db_write_performed:false,worker_execution_performed:false,model_execution_performed:false,fail_closed:true}};return{job,routing,request,execution,confirmation,registry};
}
function seed(store:FakeStore,f=fixtures()){store.values.set(keys.job(JOB),JSON.stringify(f.job));store.values.set(keys.routingDecision(JOB),JSON.stringify(f.routing));store.values.set(keys.wakeDecision(f.routing.decision.decision_id),JSON.stringify(f.request));store.values.set(keys.wakeRequest(WAKE),JSON.stringify(f.request));store.values.set(keys.wakeExecution(WAKE),JSON.stringify(f.execution));store.values.set(keys.wakeConfirmation(WAKE),JSON.stringify(f.confirmation));store.values.set(keys.worker(f.confirmation.target_worker_id),JSON.stringify(f.registry));for(const k of store.values.keys())store.expiries.set(k,Date.parse("2026-07-15T01:01:00.000Z"));return f}
const context=(s:FakeStore)=>({enabled:true,keys,storeFactory:async()=>s,nowIsoFactory:()=>NOW});
async function testWriteBeforeValidationAbsence(){const f=fixtures();for(const mutate of[(x:any)=>{x.decision.status="selected";x.decision.selected_worker={worker_id:WORKER}},(x:any)=>{x.decision.fallback_used=true},(x:any)=>{x.decision.safety.queue_write_performed=true}]){const corrupt=structuredClone(f.routing);mutate(corrupt);const s=new FakeCanonicalStore(),recordKey=`${keys.prefix}:routing-corrupt-${Math.random()}`,idKey=keys.routingDecisionId(corrupt.decision.decision_id);s.values.set(keys.job(JOB),JSON.stringify(f.job));const result=await s.persistAtomic({jobKey:keys.job(JOB),recordKey,decisionIdKey:idKey,decisionIdKeyPrefix:`${keys.prefix}:routing-decision-id:`,jobId:JOB,requestId:REQUEST,decisionId:corrupt.decision.decision_id,serialized:JSON.stringify(corrupt),expiresAtMs:Date.parse(corrupt.expires_at),jobExpiresAt:f.job.job.runtime.expires_at});assert.equal(result.status,"routing_resume_original_decision_invalid");assert.equal(s.values.has(recordKey),false);assert.equal(s.values.has(idKey),false)}const s=new FakeStore();seed(s,f);const created=await resumeHermesPostWakeRouting({jobId:JOB,context:context(s),resumeIdFactory:()=>"resume-validation",decisionIdFactory:()=>"decision-validation"});if(!created.ok)throw new Error("resume validation fixture failed");s.values.delete(keys.resume(JOB));s.values.delete(keys.resumeId(created.resume.resume_id));for(const mutate of[(x:any)=>{x.resumed_routing_decision.selected_worker.worker_id="rtx-other"},(x:any)=>{x.resumed_routing_decision.required_capability="gpu_inference"},(x:any)=>{x.queue_write_performed=true}]){const corrupt=structuredClone(created.resume),resumeKey=`${keys.prefix}:resume-corrupt-${Math.random()}`,idKey=keys.resumeId(corrupt.resume_id);mutate(corrupt);const result=await s.createAtomic({resumeKey,newResumeIdKey:idKey,resumeIdKeyPrefix:`${keys.prefix}:routing-resume-id:`,serialized:JSON.stringify(corrupt),newResumeId:corrupt.resume_id,jobId:JOB,expiresAtMs:Date.parse(corrupt.expires_at)} as any);assert.equal(result.status,"routing_resume_record_invalid");assert.equal(s.values.has(resumeKey),false);assert.equal(s.values.has(idKey),false)}}
async function main(){assert.equal(HERMES_ROUTING_RESUME_POLICY.schema_version,"hermes.routing.resume.policy.v1");assert.equal(HERMES_ROUTING_RESUME_POLICY.allowed_original_routing_status,"no_ready_worker");assert.equal(HERMES_ROUTING_RESUME_POLICY.required_confirmation_status,"worker_ready");assert.equal(HERMES_ROUTING_RESUME_POLICY.require_current_worker_revalidation,true);assert.equal(HERMES_ROUTING_RESUME_POLICY.safety.automatic_queue_write_allowed,false);assert.equal(HERMES_ROUTING_RESUME_POLICY.safety.automatic_worker_claim_allowed,false);assert.equal(HERMES_ROUTING_RESUME_POLICY.safety.automatic_model_execution_allowed,false);assert.equal(HERMES_ROUTING_RESUME_POLICY.safety.client_worker_override_allowed,false);
  await testWriteBeforeValidationAbsence();
  const bindingWorker={worker_id:WORKER,worker_type:"rtx" as const,capabilities:["heavy_reasoning" as const],health:"healthy" as const,readiness:"not_ready" as const,runtime_available:false,draining:false,last_heartbeat_at:"2026-07-15T00:58:59.000Z",current_job_id:null,active_job_count:0,max_concurrency:1};
  const bindingStore=new FakeCanonicalStore(),bindingFixture=fixtures();bindingStore.values.set(keys.job(JOB),JSON.stringify(bindingFixture.job));const bindingContext={enabled:true,keys,storeFactory:async()=>bindingStore,nowIsoFactory:()=>"2026-07-15T00:59:00.000Z"};const binding=await createCanonicalHermesInitialRouting({jobId:JOB,taskClass:"heavy_reasoning",workers:[bindingWorker],context:bindingContext,decisionIdFactory:()=>"decision-binding-unit"});assert.equal(binding.ok&&binding.status,"created");const bindingRaw=bindingStore.values.get(keys.routingDecision(JOB)),bindingTtl=bindingStore.expiries.get(keys.routingDecision(JOB));const bindingReplay=await createCanonicalHermesInitialRouting({jobId:JOB,taskClass:"heavy_reasoning",workers:[bindingWorker],context:bindingContext,decisionIdFactory:()=>"decision-binding-other"});assert.equal(bindingReplay.ok&&bindingReplay.status,"already_exists");assert.equal(bindingStore.values.get(keys.routingDecision(JOB)),bindingRaw);assert.equal(bindingStore.expiries.get(keys.routingDecision(JOB)),bindingTtl);const bindingConcurrentStore=new FakeCanonicalStore();bindingConcurrentStore.values.set(keys.job(JOB),JSON.stringify(bindingFixture.job));const bc={...bindingContext,storeFactory:async()=>bindingConcurrentStore};const bindings=await Promise.all([createCanonicalHermesInitialRouting({jobId:JOB,taskClass:"heavy_reasoning",workers:[bindingWorker],context:bc,decisionIdFactory:()=>"decision-binding-a"}),createCanonicalHermesInitialRouting({jobId:JOB,taskClass:"heavy_reasoning",workers:[bindingWorker],context:bc,decisionIdFactory:()=>"decision-binding-b"})]);assert.equal(bindings.filter(x=>x.ok&&x.status==="created").length,1);assert.equal(bindings.filter(x=>x.ok&&x.status==="already_exists").length,1);
  const store=new FakeStore();seed(store);const first=await resumeHermesPostWakeRouting({jobId:JOB,context:context(store),resumeIdFactory:()=>"resume-unit",decisionIdFactory:()=>"decision-resumed-unit"});assert.equal(first.ok&&first.status,"created");if(!first.ok)throw new Error("valid resume failed");assert.equal(first.resume.status,"selected");assert.equal(first.resume.selected_worker_id,WORKER);assert.equal(first.queue_write_performed,false);assert.equal(first.worker_claim_performed,false);assert.equal(first.model_execution_performed,false);const raw=await store.get(keys.resume(JOB)),ttl=await store.getExpiryTime(keys.resume(JOB));const replay=await resumeHermesPostWakeRouting({jobId:JOB,context:context(store),resumeIdFactory:()=>"resume-other",decisionIdFactory:()=>"decision-other"});assert.equal(replay.ok&&replay.status,"already_exists");if(!replay.ok)throw new Error("replay failed");assert.equal(replay.resume.resume_id,"resume-unit");assert.equal(await store.get(keys.resume(JOB)),raw);assert.equal(await store.getExpiryTime(keys.resume(JOB)),ttl);
  assert.deepEqual(replay.resumed_routing_decision,first.resumed_routing_decision);const changedRegistry=fixtures({capacity:true}).registry;store.values.set(keys.worker(WORKER),JSON.stringify(changedRegistry));const replayFull=await resumeHermesPostWakeRouting({jobId:JOB,context:context(store)});assert.equal(replayFull.ok&&replayFull.status,"already_exists");store.values.delete(keys.worker(WORKER));const replayMissing=await resumeHermesPostWakeRouting({jobId:JOB,context:context(store)});assert.equal(replayMissing.ok&&replayMissing.status,"already_exists");
  for(const f of[fixtures({jobStatus:"running"}),fixtures({jobStatus:"succeeded"}),fixtures({jobStatus:"cancelled"}),fixtures({decisionStatus:"selected"}),fixtures({decisionStatus:"no_capacity"}),fixtures({requestStatus:"requested"}),fixtures({executionStatus:"failed"}),fixtures({confirmationStatus:"waiting_for_heartbeat"}),fixtures({workerHeartbeat:"2026-07-15T00:59:20.000Z"}),fixtures({workerHeartbeat:"2026-07-15T01:00:11.000Z"}),fixtures({workerHealth:"unhealthy"}),fixtures({workerHealth:"degraded"}),fixtures({workerReady:"not_ready"}),fixtures({runtime:false}),fixtures({draining:true}),fixtures({capability:"gpu_inference"}),fixtures({capacity:true})]){const s=new FakeStore();seed(s,f);const x=await resumeHermesPostWakeRouting({jobId:JOB,context:context(s)});assert.equal(x.ok,false)}
  const expiredStore=new FakeStore(),expired=seed(expiredStore);expired.job.job.runtime.expires_at="2026-07-15T01:00:00.000Z";expiredStore.values.set(keys.job(JOB),JSON.stringify(expired.job));const expiredResult=await resumeHermesPostWakeRouting({jobId:JOB,context:context(expiredStore)});assert.equal(expiredResult.ok,false);if(expiredResult.ok)throw new Error("expired job accepted");assert.equal(expiredResult.error_code,"routing_resume_job_expired");
  const staleBoundaryStore=new FakeStore();seed(staleBoundaryStore,fixtures({workerHeartbeat:"2026-07-15T00:59:25.000Z"}));const staleBoundary=await resumeHermesPostWakeRouting({jobId:JOB,context:context(staleBoundaryStore)});assert.equal(staleBoundary.ok,false);if(staleBoundary.ok)throw new Error("45-second heartbeat accepted");assert.equal(staleBoundary.error_code,"routing_resume_worker_stale");
  const immortalJobStore=new FakeStore();seed(immortalJobStore);immortalJobStore.expiries.set(keys.job(JOB),-1);const immortalJob=await resumeHermesPostWakeRouting({jobId:JOB,context:context(immortalJobStore)});assert.equal(immortalJob.ok,false);if(immortalJob.ok)throw new Error("immortal job key accepted");assert.equal(immortalJob.error_code,"routing_resume_expired");
  const immortalRoutingStore=new FakeStore();seed(immortalRoutingStore);immortalRoutingStore.expiries.set(keys.routingDecision(JOB),-1);const immortalRouting=await resumeHermesPostWakeRouting({jobId:JOB,context:context(immortalRoutingStore)});assert.equal(immortalRouting.ok,false);if(immortalRouting.ok)throw new Error("immortal routing key accepted");assert.equal(immortalRouting.error_code,"routing_resume_expired");
  const missingWorkerStore=new FakeStore(),missingWorker=seed(missingWorkerStore);missingWorkerStore.values.delete(keys.worker(missingWorker.confirmation.target_worker_id));const missingResult=await resumeHermesPostWakeRouting({jobId:JOB,context:context(missingWorkerStore)});assert.equal(missingResult.ok,false);
  const targetMismatchStore=new FakeStore(),targetMismatch=seed(targetMismatchStore);targetMismatch.execution.target_worker_id="rtx-other";targetMismatchStore.values.set(keys.wakeExecution(WAKE),JSON.stringify(targetMismatch.execution));const targetMismatchResult=await resumeHermesPostWakeRouting({jobId:JOB,context:context(targetMismatchStore)});assert.equal(targetMismatchResult.ok,false);
  const capabilityMismatchStore=new FakeStore(),capabilityMismatch=seed(capabilityMismatchStore);capabilityMismatch.confirmation.required_capability="gpu_inference";capabilityMismatchStore.values.set(keys.wakeConfirmation(WAKE),JSON.stringify(capabilityMismatch.confirmation));const capabilityMismatchResult=await resumeHermesPostWakeRouting({jobId:JOB,context:context(capabilityMismatchStore)});assert.equal(capabilityMismatchResult.ok,false);
  const confirmationCapacityStore=new FakeStore(),confirmationCapacity=seed(confirmationCapacityStore);confirmationCapacity.confirmation.worker_accepting_jobs=false;confirmationCapacityStore.values.set(keys.wakeConfirmation(WAKE),JSON.stringify(confirmationCapacity.confirmation));const confirmationCapacityResult=await resumeHermesPostWakeRouting({jobId:JOB,context:context(confirmationCapacityStore)});assert.equal(confirmationCapacityResult.ok,false);
  const concurrentStore=new FakeStore();seed(concurrentStore);const concurrent=await Promise.all([resumeHermesPostWakeRouting({jobId:JOB,context:context(concurrentStore),resumeIdFactory:()=>"resume-a",decisionIdFactory:()=>"decision-a"}),resumeHermesPostWakeRouting({jobId:JOB,context:context(concurrentStore),resumeIdFactory:()=>"resume-b",decisionIdFactory:()=>"decision-b"})]);assert.equal(concurrent.filter(x=>x.ok&&x.status==="created").length,1);assert.equal(concurrent.filter(x=>x.ok&&x.status==="already_exists").length,1);assert.ok(concurrent.every(x=>x.ok));if(!concurrent[0].ok||!concurrent[1].ok)throw new Error("concurrent failed");assert.equal(concurrent[0].resume.resume_id,concurrent[1].resume.resume_id);assert.equal([...concurrentStore.values.keys()].filter(k=>k.startsWith(`${keys.prefix}:routing-resume-id:`)).length,1);
  const changedRouter=(i:Parameters<typeof routeHermesJob>[0]):HermesRoutingDecision=>{const d=routeHermesJob(i);return{...d,selected_worker:d.selected_worker?{...d.selected_worker,worker_id:"rtx-other"}:null}};const changedStore=new FakeStore();seed(changedStore);const changed=await resumeHermesPostWakeRouting({jobId:JOB,context:context(changedStore),router:changedRouter});assert.equal(changed.ok,false);if(changed.ok)throw new Error("target change accepted");assert.equal(changed.error_code,"routing_resume_target_changed");
  const noSelectionRouter=(i:Parameters<typeof routeHermesJob>[0])=>routeHermesJob({...i,workers:[]});const noSelectionStore=new FakeStore();seed(noSelectionStore);const noSelection=await resumeHermesPostWakeRouting({jobId:JOB,context:context(noSelectionStore),router:noSelectionRouter});assert.equal(noSelection.ok,false);if(noSelection.ok)throw new Error("router no-selection accepted");assert.equal(noSelection.error_code,"routing_resume_router_not_selected");
  console.log(JSON.stringify({result:"ok",checked:"hermes_routing_resume_boundary",valid_resume:"ok",job_rejection:"ok",original_routing_rejection:"ok",wake_chain:"ok",worker_revalidation:"ok",router_reuse:"ok",sequential_replay:"ok",concurrent_idempotency:"ok",queue_write_performed:false,worker_claim_performed:false,model_execution_performed:false,udp_sent:false,ssh_performed:false,gpu_detection_performed:false,db_write_performed:false,api_route_added:false},null,2));}
main().catch(e=>{console.error(e);process.exitCode=1});
