import assert from "node:assert/strict";
import { buildFarmOsApprovedCommand,parseFarmOsApprovedCommand,parseFarmOsCommandBuildRequestJson } from "../../src/lib/hermes/farm_os_approved_command_contract";
import { FARM_OS_COMMAND_REGISTRY } from "../../src/lib/hermes/farm_os_command_registry";
import type { FarmOsExecutionGatewayRequest,FarmOsExecutionGatewayResult } from "../../src/lib/hermes/farm_os_execution_gateway_contract";
import { approvedProposalFixture,commandBuildRequestFixture } from "./farm_os_day132_fixture";
const p=approvedProposalFixture(),r=commandBuildRequestFixture();const assertions:Record<string,boolean>={};const check=(name:string,value:boolean)=>{assertions[name]=value;assert.equal(value,true,name);};
const built=buildFarmOsApprovedCommand({approved_proposal:p,build_request:r});check("built",built.result==="success");assert.equal(built.result,"success");
check("parsed",parseFarmOsApprovedCommand(built.command).valid);check("deterministic",buildFarmOsApprovedCommand({approved_proposal:p,build_request:r}).result==="success"&&buildFarmOsApprovedCommand({approved_proposal:p,build_request:r}).command?.command_id===built.command.command_id);
check("registry_complete",Object.values(FARM_OS_COMMAND_REGISTRY).every((entry)=>entry.executable_in_day132===false&&entry.allowed_target_systems.length===1&&entry.allowed_output_classes.length===1));
check("typed_payload",built.command.execution_payload.schema_version===FARM_OS_COMMAND_REGISTRY.approved_internal_command.payload_schema);
const gatewayRequest:FarmOsExecutionGatewayRequest={schema_version:"farmos.execution.gateway.request.v1",request_id:"gateway_request_fixture",approved_command:built.command,requested_at:"2026-07-21T08:02:00.000Z",request_actor:"execution_gateway",correlation_id:p.trace.correlation_id};
const gatewayResult:FarmOsExecutionGatewayResult={schema_version:"farmos.execution.gateway.result.v1",request_id:gatewayRequest.request_id,command_id:built.command.command_id,result:"blocked",error:"gateway_not_implemented",gateway_version:"not_implemented_day132",audit:{recorded_at:"2026-07-21T08:02:00.000Z"},trace:{correlation_id:p.trace.correlation_id}};
check("gateway_contract_only",gatewayResult.result==="blocked");
const raw=JSON.stringify(r);const duplicate=raw.replace('"command_class":','"command_class":"approved_external_command","command_class":');
check("build_request_duplicate",parseFarmOsCommandBuildRequestJson(duplicate).blocked_reason==="DUPLICATE_FIELD");
console.log(JSON.stringify({assertions,assertion_count:Object.keys(assertions).length}));
