import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import ts from "typescript";

const root=process.cwd(),entry=path.join(root,"src/lib/hermes/farm_os_crop_planning_workforce_governance.ts");
const forbidden=/postgres|supabase|redis|database|repository|migration|node:fs|node:net|node:http|node:https|child_process|runtime_tool|proposal_apply|review_post|real_adapter|secret/iu;
type Finding={dependency:string[];call:string[];dynamic:string[]};const empty=():Finding=>({dependency:[],call:[],dynamic:[]});
const local=(from:string,s:string)=>{const base=path.resolve(path.dirname(from),s);return [base,`${base}.ts`,path.join(base,"index.ts")].find(existsSync)??null;};
const inspect=(file:string,source:string,out:Finding,follow:(file:string)=>void)=>{const ast=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true);const visit=(n:ts.Node)=>{if((ts.isImportDeclaration(n)||ts.isExportDeclaration(n))&&n.moduleSpecifier&&ts.isStringLiteral(n.moduleSpecifier)){const s=n.moduleSpecifier.text;if(s.startsWith(".")){const target=local(file,s);if(!target)out.dependency.push(`${file}:${s}`);else follow(target)}else if(forbidden.test(s)||s!=="node:crypto")out.dependency.push(`${file}:${s}`)}if(ts.isIdentifier(n)&&/^(fetch|axios|eval|Function|require|writeFile|writeFileSync)$/.test(n.text))out.call.push(`${file}:${n.text}`);if(ts.isCallExpression(n)){const x=n.expression,t=x.getText(ast),terminal=ts.isPropertyAccessExpression(x)?x.name.text:ts.isElementAccessExpression(x)&&ts.isStringLiteral(x.argumentExpression)?x.argumentExpression.text:"";if(x.kind===ts.SyntaxKind.ImportKeyword){out.dynamic.push(`${file}:${t}`)}if(terminal==="call"||terminal==="apply")out.call.push(`${file}:${t}`)}ts.forEachChild(n,visit)};visit(ast)};
const visited=new Set<string>(),production=empty();const follow=(file:string)=>{const absolute=path.resolve(file);if(visited.has(absolute))return;visited.add(absolute);inspect(absolute,readFileSync(absolute,"utf8"),production,follow)};follow(entry);
const fixtures={direct_import:"import x from 'node:http'",reexport:"export {x} from './real_adapter'",direct_fetch:"fetch('x')",fetch_alias:"const f=fetch; f('x')",dynamic_import:"void import('./runtime_tool')",property_call:"handler.call(null)",computed_call:"handler['call'](null)",filesystem_write:"import {writeFileSync} from 'node:fs'; writeFileSync('x','x')",child_process:"import {spawn} from 'node:child_process'; spawn('x')",repository:"import x from './postgres_repository'",real_adapter:"import x from './real_adapter'",secret_loader:"import x from './secret_loader'"};
const detected=Object.fromEntries(Object.entries(fixtures).map(([id,source])=>{const result=empty();inspect(path.join(root,`fixture-${id}.ts`),source,result,()=>{});return[id,Object.values(result).some(x=>x.length>0)]}));for(const [id,value] of Object.entries(detected))assert.equal(value,true,id);for(const value of Object.values(production))assert.equal(value.length,0);const result={dependency_boundary_valid:true,recursive_ast_traversal_valid:visited.size>1,reexport_traversal_valid:detected.reexport,alias_call_detection_valid:detected.fetch_alias,alias_detection_scope:"fixture_proof_only",member_call_detection_valid:detected.property_call,computed_call_detection_valid:detected.computed_call,fixture_detection_valid:Object.values(detected).every(Boolean),inspected_files:[...visited].map(x=>path.relative(root,x)).sort(),fixture_detection:detected,forbidden_dependencies:production.dependency,forbidden_calls:production.call,dynamic_imports:production.dynamic};console.log(JSON.stringify(result));for(const [k,v] of Object.entries(result).filter(([,v])=>typeof v==="boolean"))assert.equal(v,true,k);
