import assert from "node:assert/strict";
import { DAY134_REVIEW_FINDING_IDS,DAY134_TEST_SUITE_VERSION,decideDay134Gate,parseDay134ReviewArtifact,type Day134BuildEvidence,type Day134ReviewArtifact } from "./farm_os_day134_evidence";
const tree="sha256:tree",commit="commit",evaluated_at="2026-07-21T00:10:00.000Z";
const executed={targeted_test_exit_code:0,day133_regression_exit_code:0,day132_regression_exit_code:0,day131_regression_exit_code:0,day130_5_regression_exit_code:0,typecheck_exit_code:0,dependency_boundary_exit_code:0,report_integrity_exit_code:0};
const build:Day134BuildEvidence={schema_version:"farmos.day134.build-evidence.v1",reviewed_tree_hash:tree,source_commit:commit,test_suite_version:DAY134_TEST_SUITE_VERSION,command:"pnpm run build",exit_code:0,generated_at:"2026-07-21T00:00:00.000Z"};
const review:Day134ReviewArtifact={schema_version:"farmos.day134.review-artifact.v1",review_id:"review_day134",reviewer_id:"independent_reviewer",review_method:"independent_read_only_review",reviewed_tree_hash:tree,source_commit:commit,test_suite_version:DAY134_TEST_SUITE_VERSION,generated_at:"2026-07-21T00:01:00.000Z",findings:DAY134_REVIEW_FINDING_IDS.map((finding_id)=>({finding_id,severity:finding_id.includes("P1")?"P1" as const:"P2" as const,status:"resolved" as const,evidence_refs:["test"]}))};
const decide=(value:Partial<Parameters<typeof decideDay134Gate>[0]>={})=>decideDay134Gate({tree_hash:tree,source_commit:commit,evaluated_at,executed,machine_checks_valid:true,build,review,...value});
assert.equal(decide().formal_decision,"go");assert.equal(decide({build:null}).formal_decision,"hold");assert.equal(decide({review:null}).formal_decision,"hold");assert.equal(decide({machine_checks_valid:false}).formal_decision,"hold");assert.equal(decide({executed:{...executed,day133_regression_exit_code:null}}).formal_decision,"hold");assert.equal(decide({review:{...review,reviewed_tree_hash:"stale"}}).formal_decision,"hold");assert.equal(decide({review:{...review,generated_at:"2026-07-20T00:00:00.000Z"}}).formal_decision,"hold");assert.equal(decide({build:{...build,generated_at:"2026-07-21T00:05:00.000Z"}}).formal_decision,"hold");assert.equal(decide({review:{...review,findings:[...review.findings,{finding_id:"DAY134-P2-NEW-FINDING",severity:"P2",status:"open",evidence_refs:["review"]}]}}).formal_decision,"hold");assert.equal(parseDay134ReviewArtifact({...review,findings:[]}),null);process.env.DAY134_P1_COUNT="0";assert.equal(decide({build:null,review:null}).formal_decision,"hold");
console.log(JSON.stringify({report_integrity_valid:true,environment_flags_ignored:true,stale_evidence_rejected:true,evidence_order_validated:true,known_findings_required:true,new_open_findings_block:true,all_evidence_go:true}));
