import assert from "node:assert/strict";
import { pathToFileURL } from "node:url";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { DailyFarmBriefProposalList,formatDailyBriefProposalDate } from "../../src/components/hermes/DailyFarmBriefProposalList";
import { DailyFarmBriefProposalDetail } from "../../src/components/hermes/DailyFarmBriefProposalDetail";
import { createDailyBriefProposalDetailUiState,createDailyBriefProposalListUiState } from "../../src/lib/hermes/hermes_daily_farm_brief_proposal_review_ui_client";
import { createHermesDailyFarmBriefProposalReviewDetailApiResponse,createHermesDailyFarmBriefProposalReviewListApiResponse } from "./brief_runtime/hermes_daily_farm_brief_proposal_review_api_contract";
import { createHermesDailyFarmBriefProposalDetail,createHermesDailyFarmBriefProposalListItem } from "../../src/lib/hermes/hermes_daily_farm_brief_proposal_review_read_boundary";
import { createDay127ApiTestRow } from "./test_hermes_daily_farm_brief_proposal_review_service";

export async function runDay127ProposalReviewUiProjection(){const row=createDay127ApiTestRow();const requestedAt="2026-07-18T04:00:00.000Z";const item=createHermesDailyFarmBriefProposalListItem({row,requestedAt});const detail=createHermesDailyFarmBriefProposalDetail({row,requestedAt});assert(item&&detail);const expired={...item,expiry_state:"expired" as const};const listState=createDailyBriefProposalListUiState(200,createHermesDailyFarmBriefProposalReviewListApiResponse({result:"ok",proposals:[expired]}));const detailState=createDailyBriefProposalDetailUiState(200,createHermesDailyFarmBriefProposalReviewDetailApiResponse({result:"ok",proposal:detail}));assert.equal(listState.state,"ok");assert.equal(detailState.state,"ok");const listHtml=renderToStaticMarkup(createElement(DailyFarmBriefProposalList,{state:listState}));const detailHtml=renderToStaticMarkup(createElement(DailyFarmBriefProposalDetail,{state:detailState,reviewControlsEnabled:false}));for(const expected of [item.title,item.summary,"確認待ち","期限切れ","管理者の確認が必要","営農データには反映されていません"])assert(listHtml.includes(expected));for(const expected of [detail.title,detail.reason,detail.target_display,detail.work_type_label,detail.basis,detail.before,detail.after,"適用操作は利用できません","営農データには反映されていません"])assert(detailHtml.includes(expected));assert(formatDailyBriefProposalDate("2026-07-17T21:05:00.000Z").includes("2026/07/18"));assert(formatDailyBriefProposalDate("invalid")==="日時を確認できません");for(const html of [listHtml,detailHtml]){for(const forbidden of [row.id,row.payload_json.candidate_id,row.payload_json.idempotency_key,"day127-read-e2e-admin","payload_json","source_refs_json"])assert(!html.includes(forbidden));assert(!/<button|<form/iu.test(html));}assert.equal(createDailyBriefProposalListUiState(200,{malformed:true}).state,"unavailable");assert.equal(createDailyBriefProposalDetailUiState(404,null).state,"not_found");return{result:"pass",list_rendered:true,detail_rendered:true,jst_date_rendered:true,expired_rendered:true,boolean_localized:true,raw_identifier_exposed:false,raw_payload_exposed:false,mutation_control_present:false,malformed_response_safe:true};}
if(import.meta.url===pathToFileURL(process.argv[1]??"").href)console.log(JSON.stringify(await runDay127ProposalReviewUiProjection()));
