import assert from "node:assert/strict";
import { FarmOsNativeRuntimeAdapter } from "../../src/lib/hermes/farm_os_native_runtime_adapter";
import { NousHermesObservationAdapter } from "../../src/lib/hermes/nous_hermes_observation_adapter";
import { evaluateFarmOsAgentPolicy } from "../../src/lib/hermes/farm_os_agent_policy_matrix";
import { FARM_OS_RISK_POLICIES, resolveRiskPolicy, validatePolicyOverrideAttempt, validateTemporaryException } from "../../src/lib/hermes/farm_os_risk_taxonomy";
import type { FarmAgentRuntimeRequest } from "../../src/lib/hermes/farm_agent_runtime_port";

type FixtureResult = { test_case_id: string; input: unknown; classification: string; allowed: boolean; blocked_reason: string | null; risk_level: string; approval_requirement: string; required_capabilities: readonly string[]; rollback_class: string; agent_direct_execution_allowed: false; external_execution: boolean; assertion_count: number };
const results: FixtureResult[] = [];
function fixture(id: string, input: unknown, classification: string, policy: typeof FARM_OS_RISK_POLICIES[keyof typeof FARM_OS_RISK_POLICIES], allowed: boolean, blockedReason: string | null, checks: Array<[string, boolean]>): void {
  let assertionCount = 0; for (const [name, condition] of checks) { assertionCount += 1; assert.equal(condition, true, `${id}:${name}`); }
  results.push({ test_case_id: id, input, classification, allowed, blocked_reason: blockedReason, risk_level: policy.risk_level, approval_requirement: policy.approval_requirement, required_capabilities: policy.required_capabilities, rollback_class: policy.rollback_class, agent_direct_execution_allowed: policy.agent_direct_execution_allowed, external_execution: policy.external_execution, assertion_count: assertionCount });
}
const l0 = FARM_OS_RISK_POLICIES.l0_read_only, l1 = FARM_OS_RISK_POLICIES.l1_proposal_write, l2 = FARM_OS_RISK_POLICIES.l2_internal_apply, l3 = FARM_OS_RISK_POLICIES.l3_external_execution;
const a = evaluateFarmOsAgentPolicy({ actor: "nous_hermes_observer", action: "produce_observation", risk_level: "l0_read_only" });
fixture("A", { actor: "nous_hermes_observer", action: "produce_observation" }, "read_only_output", l0, a.allowed, a.blocked_reason, [["allowed", a.allowed], ["readonly", !l0.external_execution], ["direct", !l0.agent_direct_execution_allowed]]);
const b = resolveRiskPolicy("work_log_follow_up")!; const bObserver = evaluateFarmOsAgentPolicy({ actor: "nous_hermes_observer", action: "persist_proposal", risk_level: "l1_proposal_write" });
fixture("B", { proposal_type: "work_log_follow_up" }, "proposal_write_policy", l1, true, null, [["risk", b.risk_level === "l1_proposal_write"], ["review", b.approval_requirement === "human_review"], ["observer_denied", !bObserver.allowed], ["formal_false", b.formal_persistence_allowed === false]]);
fixture("C", { risk_level: "l2_internal_apply" }, "internal_apply_policy", l2, true, null, [["approval", l2.approval_requirement === "privileged_approval"], ["reauth", l2.reauthorization_required], ["internal", !l2.external_execution]]);
fixture("D", { risk_level: "l3_external_execution" }, "external_execution_policy", l3, true, null, [["approval", l3.approval_requirement === "final_confirmation_and_reauthentication"], ["external", l3.external_execution], ["direct", !l3.agent_direct_execution_allowed]]);
fixture("E", { proposal_type: "unknown" }, "blocked_unknown", l1, false, "unknown_proposal_type", [["unknown", resolveRiskPolicy("unknown") === null]]);
const f = evaluateFarmOsAgentPolicy({ actor: "nous_hermes_observer", action: "perform_internal_apply", risk_level: "l2_internal_apply" });
fixture("F", { actor: "nous_hermes_observer", action: "perform_internal_apply" }, "blocked_actor_action", l2, f.allowed, f.blocked_reason, [["denied", !f.allowed], ["reason", f.blocked_reason === "actor_action_not_allowed"]]);
const gInput = { source_policy_class: "user_preference", target_policy_class: "operational_policy", requested_risk_change: { from: "l1_proposal_write", to: "l0_read_only" }, requested_capability_additions: [], requested_approval_change: { from: "human_review", to: "none" }, requested_direct_execution_change: false }; const g = validatePolicyOverrideAttempt(gInput);
fixture("G", gInput, "blocked_policy_override", l1, g.valid, g.blocked_reason, [["blocked", !g.valid], ["reason", g.blocked_reason === "policy_override_not_allowed"]]);
const hInput = { issuer: "fixture", reason: "fixture", scope: "fixture", valid_from: "2026-07-21T00:00:00Z", valid_until: "2026-07-21T01:00:00Z", audit_reference: "fixture", revoke_condition: "fixture", post_review_required: true, approval_bypass_requested: true, risk_downgrade_requested: false, capability_additions: [], agent_direct_execution_requested: false, arbitrary_url_requested: false, secret_access_requested: false, invariant_override_requested: false }; const h = validateTemporaryException(hInput);
fixture("H", hInput, "blocked_temporary_exception", l1, h.valid, h.blocked_reason, [["blocked", !h.valid], ["reason", h.blocked_reason === "invalid_temporary_exception"], ["timestamp", validateTemporaryException({ ...hInput, approval_bypass_requested: false, valid_until: "invalid" }).blocked_reason === "invalid_timestamp"]]);
const i = evaluateFarmOsAgentPolicy({ actor: "nous_hermes_observer", action: "create_policy_candidate", risk_level: "l1_proposal_write" });
fixture("I", { actor: "nous_hermes_observer", action: "create_policy_candidate" }, "policy_candidate", l1, i.allowed, i.blocked_reason, [["allowed", i.allowed], ["adopt_denied", !evaluateFarmOsAgentPolicy({ actor: "nous_hermes_observer", action: "adopt_policy", risk_level: "l1_proposal_write" }).allowed], ["review", l1.approval_requirement === "human_review"]]);
const j = evaluateFarmOsAgentPolicy({ actor: "nous_hermes_observer", action: "create_evolution_candidate", risk_level: "l1_proposal_write" });
fixture("J", { actor: "nous_hermes_observer", action: "create_evolution_candidate" }, "evolution_candidate", l1, j.allowed, j.blocked_reason, [["allowed", j.allowed], ["accept_denied", !evaluateFarmOsAgentPolicy({ actor: "nous_hermes_observer", action: "accept_evolution_candidate", risk_level: "l1_proposal_write" }).allowed], ["direct", !l1.agent_direct_execution_allowed]]);

const counters = { provider_call_count: 0, delegate_call_count: 0, business_write_attempt_count: 0, review_decision_attempt_count: 0, proposal_apply_attempt_count: 0, execution_command_attempt_count: 0, external_execution_attempt_count: 0 };
const attemptAfterPolicy = (evaluation: ReturnType<typeof evaluateFarmOsAgentPolicy>, key: "business_write_attempt_count" | "review_decision_attempt_count" | "proposal_apply_attempt_count" | "execution_command_attempt_count" | "external_execution_attempt_count") => { if (evaluation.allowed) counters[key] += 1; };
for (const key of ["business_write_attempt_count", "review_decision_attempt_count", "proposal_apply_attempt_count", "execution_command_attempt_count", "external_execution_attempt_count"] as const) attemptAfterPolicy(f, key);
const request: FarmAgentRuntimeRequest = { schema_version: "farmos.agent.runtime.v1", request_id: "day131-blocked", runtime_profile: "operator", task_type: "architecture_finding", input_text: "fixture", readonly_context: [], allowed_capabilities: ["read_fixture_context"], timeout_ms: 1000, correlation_id: "fixture" };
const providerBlocked = await new NousHermesObservationAdapter(async () => { counters.provider_call_count += 1; return {}; }).execute(request);
assert.equal(providerBlocked.result_state, "blocked"); assert.equal(counters.provider_call_count, 0);
const delegateBlocked = await new FarmOsNativeRuntimeAdapter(async () => { counters.delegate_call_count += 1; return {}; }).execute({ ...request, runtime_profile: "operator", task_type: "architecture_finding" });
assert.equal(delegateBlocked.result_state, "blocked"); assert.equal(counters.delegate_call_count, 0);
console.log(JSON.stringify({ cases: results, test_observed_provider_call_count: counters.provider_call_count, test_observed_delegate_call_count: counters.delegate_call_count, test_observed_business_write_attempt_count: counters.business_write_attempt_count, test_observed_review_decision_attempt_count: counters.review_decision_attempt_count, test_observed_proposal_apply_attempt_count: counters.proposal_apply_attempt_count, test_observed_execution_command_attempt_count: counters.execution_command_attempt_count, test_observed_external_execution_attempt_count: counters.external_execution_attempt_count }));
