import assert from "node:assert/strict";
import { DAY132_REVIEW_FINDING_IDS,DAY132_TEST_SUITE_VERSION,decideDay132Gate,parseDay132ReviewArtifact,type Day132BuildEvidence,type Day132ReviewArtifact } from "./farm_os_day132_evidence";
const tree="sha256:tree",commit="commit";
const executed={targeted_test_exit_code:0,day131_regression_exit_code:0,day130_5_regression_exit_code:0,typecheck_exit_code:0,dependency_boundary_exit_code:0,report_integrity_exit_code:0};
const build:Day132BuildEvidence={schema_version:"farmos.day132.build-evidence.v1",reviewed_tree_hash:tree,source_commit:commit,test_suite_version:DAY132_TEST_SUITE_VERSION,command:"pnpm run build",exit_code:0,generated_at:"2026-07-21T00:00:00.000Z"};
const severities:Record<(typeof DAY132_REVIEW_FINDING_IDS)[number],"P1"|"P2">={"DAY132-P1-L3-REAUTHENTICATION":"P1","DAY132-P1-PROPOSAL-HASH-SCOPE":"P1","DAY132-P2-SIDE-EFFECT-EVIDENCE":"P2","DAY132-P2-FORMAL-DECISION-EVIDENCE":"P2"};
const review:Day132ReviewArtifact={schema_version:"farmos.day132.review-artifact.v1",review_id:"review_day132_independent",reviewer_id:"independent_reviewer",review_method:"independent_read_only_review",reviewed_tree_hash:tree,source_commit:commit,test_suite_version:DAY132_TEST_SUITE_VERSION,generated_at:"2026-07-21T00:00:00.000Z",findings:DAY132_REVIEW_FINDING_IDS.map((finding_id)=>({finding_id,severity:severities[finding_id],status:"resolved",evidence_refs:["targeted-test"]}))};
const decide=(overrides:Partial<Parameters<typeof decideDay132Gate>[0]>={})=>decideDay132Gate({tree_hash:tree,source_commit:commit,executed,machine_checks_valid:true,build,review,...overrides});
assert.equal(decide().formal_decision,"go");
assert.equal(decide({build:null}).formal_decision,"hold");
assert.equal(decide({build:{...build,reviewed_tree_hash:"stale"}}).formal_decision,"hold");
assert.equal(decide({executed:{...executed,day131_regression_exit_code:null}}).formal_decision,"hold");
assert.equal(decide({executed:{...executed,typecheck_exit_code:1}}).formal_decision,"hold");
assert.equal(decide({review:{...review,reviewed_tree_hash:"stale"}}).formal_decision,"hold");
assert.equal(decide({review:{...review,findings:review.findings.map((item,index)=>index===0?{...item,status:"open" as const}:item)}}).formal_decision,"hold");
assert.equal(decide({review:{...review,findings:[...review.findings,{finding_id:"DAY132-P2-NEW-FINDING",severity:"P2",status:"open",evidence_refs:["independent-review"]}]}}).formal_decision,"hold");
assert.equal(decide({machine_checks_valid:false}).formal_decision,"hold");
assert.equal(parseDay132ReviewArtifact({...review,findings:[]}),null);
assert.equal(parseDay132ReviewArtifact({...review,findings:review.findings.slice(1)}),null);
process.env.DAY132_P1_COUNT="0";process.env.DAY132_ISOLATED_BUILD_VALID="true";
assert.equal(decideDay132Gate({tree_hash:tree,source_commit:commit,executed:{...executed,targeted_test_exit_code:null},machine_checks_valid:false,build:null,review:null}).formal_decision,"hold");
console.log(JSON.stringify({report_integrity_valid:true,environment_flags_ignored:true,stale_review_rejected:true,tree_hash_mismatch_rejected:true,regression_missing_rejected:true,typecheck_missing_rejected:true,build_evidence_missing_rejected:true,open_findings_rejected:true,known_findings_required:true,machine_checks_required:true,all_evidence_go:true}));
