import assert from "node:assert/strict";
import { buildLowRiskCandidate, createLowRiskCandidateAuditEvidence, FARM_OS_LOW_RISK_CANDIDATE_REGISTRY, FARM_OS_LOW_RISK_CANDIDATE_STATUSES, parseFarmOsLowRiskSafeReference, toLowRiskEvolutionEvidence, validateHermesLowRiskCandidate } from "../../src/lib/hermes/farm_os_low_risk_candidate_contract";
import { DAY136_INVALID_FIXTURES, DAY136_VALID_FIXTURES } from "./farm_os_day136_fixture";

const now = new Date("2026-07-23T01:00:00.000Z");
const passed: string[] = [];
const check = (id: string, condition: boolean) => { assert.equal(condition, true, id); passed.push(id); };
for (const [id, fixture] of Object.entries(DAY136_VALID_FIXTURES)) check(`valid_${id}`, validateHermesLowRiskCandidate(fixture, now).valid);
for (const [id, fixture] of Object.entries(DAY136_INVALID_FIXTURES)) check(`invalid_${id}`, !validateHermesLowRiskCandidate(fixture, now).valid);
const rejection = (fixture: unknown) => { const result = validateHermesLowRiskCandidate(fixture, now); return "rejection_code" in result ? result.rejection_code : null; };
check("business_write_code", rejection(DAY136_INVALID_FIXTURES.J) === "business_write_intent_detected");
check("execution_code", rejection(DAY136_INVALID_FIXTURES.K) === "execution_intent_detected");
check("url_code", rejection(DAY136_INVALID_FIXTURES.L) === "arbitrary_url_rejected");
check("secret_code", rejection(DAY136_INVALID_FIXTURES.M) === "secret_like_value_rejected");
check("sql_write_rejected", rejection({ ...DAY136_VALID_FIXTURES.A, summary: "UPDATE crops SET approved=true" }) === "business_write_intent_detected");
check("japanese_write_rejected", rejection({ ...DAY136_VALID_FIXTURES.A, summary: "在庫数量を更新してください" }) === "business_write_intent_detected");
check("verb_first_apply_rejected", rejection({ ...DAY136_VALID_FIXTURES.A, summary: "Apply crop plan immediately." }) === "business_write_intent_detected");
check("verb_first_approve_rejected", rejection({ ...DAY136_VALID_FIXTURES.A, summary: "Approve crop plan immediately." }) === "business_write_intent_detected");
check("shell_execution_rejected", rejection({ ...DAY136_VALID_FIXTURES.A, summary: "rm -rf unsafe-path" }) === "execution_intent_detected");
check("secretary_not_secret", validateHermesLowRiskCandidate({ ...DAY136_VALID_FIXTURES.A, summary: "The secretary prepared this review candidate." }, now).valid);
check("unknown_key_rejection", !validateHermesLowRiskCandidate(DAY136_INVALID_FIXTURES.I, now).valid);
check("payload_discriminator", !validateHermesLowRiskCandidate(DAY136_INVALID_FIXTURES.R, now).valid);
check("risk_mapping", Object.values(FARM_OS_LOW_RISK_CANDIDATE_REGISTRY).every((x) => x.risk_level === "l1_proposal_write"));
check("registry_mapping", Object.values(FARM_OS_LOW_RISK_CANDIDATE_REGISTRY).every((x) => x.approval_required && !x.command_conversion_allowed && !x.business_write_allowed && !x.external_side_effect_allowed));
check("status_excludes_approval", !FARM_OS_LOW_RISK_CANDIDATE_STATUSES.some((x) => ["approved", "executing", "executed", "applied", "succeeded", "compensated"].includes(x)));
check("safe_reference", parseFarmOsLowRiskSafeReference(DAY136_VALID_FIXTURES.E.payload.crop_plan_ref, "crop_plan") !== null);
check("arbitrary_source_rejected", parseFarmOsLowRiskSafeReference({ ...DAY136_VALID_FIXTURES.E.payload.crop_plan_ref, source_system: "client_target" }) === null);
const fallback = buildLowRiskCandidate({ hermes_output: DAY136_INVALID_FIXTURES.I, native_candidate: () => DAY136_VALID_FIXTURES.A, now });
check("hermes_invalid_native_fallback", fallback.outcome === "review_ready" && fallback.native_fallback_used && fallback.audit.upstream_rejection_code === "unknown_payload_field");
const fallbackFailure = buildLowRiskCandidate({ hermes_output: DAY136_INVALID_FIXTURES.I, native_candidate: () => { throw new Error("fixture"); }, now });
check("native_fallback_failure", fallbackFailure.outcome === "rejected" && fallbackFailure.rejection_code === "native_fallback_failed" && fallbackFailure.audit?.rejection_code === "native_fallback_failed" && fallbackFailure.audit.upstream_rejection_code === "unknown_payload_field");
const mismatch = buildLowRiskCandidate({ hermes_output: DAY136_INVALID_FIXTURES.I, native_candidate: () => ({ ...DAY136_VALID_FIXTURES.A, correlation_id: "different-correlation" }), now });
check("fallback_correlation_mismatch", mismatch.outcome === "rejected" && mismatch.rejection_code === "native_fallback_failed");
const result = validateHermesLowRiskCandidate(DAY136_VALID_FIXTURES.F, now);
const audit = createLowRiskCandidateAuditEvidence(DAY136_VALID_FIXTURES.F, result, false)!;
check("audit_correlation", audit.correlation_id === DAY136_VALID_FIXTURES.F.correlation_id && audit.agent_run_id === DAY136_VALID_FIXTURES.F.agent_run_id);
check("business_write_zero", !audit.business_write_attempted && !audit.business_write_performed);
check("execution_zero", !audit.execution_attempted && !audit.execution_performed);
const evolution = toLowRiskEvolutionEvidence(audit);
check("evolution_candidate_only", !evolution.automatic_policy_adoption && !evolution.automatic_skill_adoption);
console.log(JSON.stringify({ schema_version: "farmos.day136.fixture-report.v1", fixture_count: Object.keys(DAY136_VALID_FIXTURES).length + Object.keys(DAY136_INVALID_FIXTURES).length + 2, assertion_count: passed.length, pass_count: passed.length, fail_count: 0, command_generation_count: 0, execution_gateway_call_count: 0, business_write_count: 0, external_side_effect_count: 0, assertions: passed }));
