import assert from "node:assert/strict";
import { executeFarmOsExecutionGateway,parseFarmOsExecutionGatewayRequest,parseFarmOsExecutionGatewayRequestJson } from "../../src/lib/hermes/farm_os_execution_gateway";
import { FARM_OS_COMMAND_TRANSITION_TABLE,transitionFarmOsCommand,type FarmOsCommandStateRecord } from "../../src/lib/hermes/farm_os_execution_gateway_state_machine";
import { resolveFarmOsExecutionAdapter } from "../../src/lib/hermes/farm_os_execution_adapter_registry";
import { FarmOsInMemoryExecutionReservationRepository } from "../../src/lib/hermes/farm_os_in_memory_execution_reservation_repository";
import { day133ApprovedCommandFixture,day133ExternalApprovedCommandFixture,day133GatewayRequestFixture } from "./farm_os_day133_fixture";
type Case={test_case_id:string;passed:boolean;expected:string;actual:string;assertion_count:number};const cases:Case[]=[];const counters={gateway_request_validation_count:0,gateway_request_accepted_count:0,gateway_request_rejected_count:0,state_transition_count:0,adapter_resolution_count:0,fake_adapter_call_count:0,fake_adapter_success_count:0,fake_adapter_failure_count:0,compensation_required_count:0,compensated_count:0};
const record=(id:string,expected:string,actual:string,...conditions:boolean[])=>{conditions.forEach((condition)=>assert.equal(condition,true,id));cases.push({test_case_id:id,passed:conditions.every(Boolean),expected,actual,assertion_count:conditions.length});};
const command=day133ApprovedCommandFixture(),request=day133GatewayRequestFixture(command);
const run=async(mode:"fake_success"|"fake_failure"|"fake_compensation_required",source:unknown=request,repository=new FarmOsInMemoryExecutionReservationRepository())=>{counters.gateway_request_validation_count+=1;counters.adapter_resolution_count+=1;const result=await executeFarmOsExecutionGateway({request:source,expected_version:0,reservation_port:repository,fake_mode:mode});const gateway=result.gateway_result;if(result.result==="executed"||result.result==="replayed")counters.gateway_request_accepted_count+=1;else counters.gateway_request_rejected_count+=1;if(result.fake_adapter_called){counters.fake_adapter_call_count+=1;gateway?.result==="succeeded"?counters.fake_adapter_success_count+=1:counters.fake_adapter_failure_count+=1;}counters.state_transition_count+=gateway?Math.max(0,gateway.state_records.length-1):0;if(gateway?.result==="compensation_required")counters.compensation_required_count+=1;return result;};
async function main(){
  record("A","valid_approved_command",parseFarmOsExecutionGatewayRequest(request).valid?"valid_approved_command":"invalid",parseFarmOsExecutionGatewayRequest(request).valid);record("B","valid_gateway_request",parseFarmOsExecutionGatewayRequest(request).valid?"valid_gateway_request":"invalid",parseFarmOsExecutionGatewayRequest(request).valid);
  const initial:FarmOsCommandStateRecord={command_id:command.command_id,gateway_request_id:request.gateway_request_id,state:"requested",state_version:1,previous_state:null,transition_event:null,transitioned_at:request.requested_at,gateway_version:"farmos-execution-gateway-day133.v1",adapter_id:null,adapter_result_reference:null,trace:{proposal_id:command.proposal_reference.proposal_id,approval_id:command.proposal_reference.approval_id,request_id:command.trace.request_id,correlation_id:command.trace.correlation_id,source_event_hash:command.trace.source_event_hash,proposal_hash:command.proposal_reference.proposal_hash,command_hash:command.idempotency.command_hash},audit:{transition_recorded:true,business_write_performed:false}};
  const approved=transitionFarmOsCommand({record:initial,to:"approved",event:"request_validated",expected_state_version:1,command_class:command.command_class,risk_level:command.risk_level,transitioned_at:request.requested_at});record("C","approved",approved.valid?approved.record.state:"invalid",approved.valid&&approved.record.state==="approved");const executing=approved.valid?transitionFarmOsCommand({record:approved.record,to:"executing",event:"execution_started",expected_state_version:2,command_class:command.command_class,risk_level:command.risk_level,transitioned_at:request.requested_at}):null;record("D","executing",executing?.valid?executing.record.state:"invalid",executing?.valid===true&&executing.record.state==="executing");
  const success=await run("fake_success");record("E","succeeded",success.gateway_result?.result??"blocked",success.result==="executed"&&success.gateway_result.result==="succeeded"&&success.reservation.reservation_state==="completed");const failure=await run("fake_failure",{...request,gateway_request_id:"gateway_request_failure_day133"});record("F","failed",failure.rejection??"allowed",failure.result==="blocked"&&failure.rejection==="RETRY_NOT_ALLOWED"&&failure.reservation?.reservation_state==="failed");const compensation=await run("fake_compensation_required",{...request,gateway_request_id:"gateway_request_compensation_day133"});record("G","compensation_required",compensation.rejection??"allowed",compensation.result==="blocked"&&compensation.rejection==="RETRY_REQUIRES_REVIEW");
  const compensationRecord=compensation.reservation?.final_result?.state_records.at(-1);const compensated=compensationRecord?transitionFarmOsCommand({record:compensationRecord,to:"compensated",event:"compensation_completed",expected_state_version:compensationRecord.state_version,command_class:command.command_class,risk_level:command.risk_level,transitioned_at:new Date().toISOString()}):null;if(compensated?.valid)counters.compensated_count+=1;record("H","compensated",compensated?.valid?compensated.record.state:"invalid",compensated?.valid===true&&compensated.record.state==="compensated");
  const invalid=transitionFarmOsCommand({record:initial,to:"succeeded",event:"adapter_succeeded",expected_state_version:1,command_class:command.command_class,risk_level:command.risk_level,transitioned_at:new Date().toISOString()});record("I","INVALID_STATE_TRANSITION",invalid.valid?"allowed":invalid.blocked_reason,!invalid.valid&&invalid.blocked_reason==="INVALID_STATE_TRANSITION");const wrongHash=parseFarmOsExecutionGatewayRequest({...request,expected_command_hash:`sha256:${"f".repeat(64)}`});record("J","COMMAND_HASH_MISMATCH",wrongHash.valid?"allowed":wrongHash.blocked_reason,!wrongHash.valid&&wrongHash.blocked_reason==="COMMAND_HASH_MISMATCH");
  const unknownAdapter=resolveFarmOsExecutionAdapter({command_class:command.command_class,execution_target:"unknown_target",payload_schema:command.execution_payload.schema_version,risk_level:command.risk_level});record("K","ADAPTER_NOT_ALLOWED",unknownAdapter?"allowed":"ADAPTER_NOT_ALLOWED",unknownAdapter===null);const shared=new FarmOsInMemoryExecutionReservationRepository(),first=await run("fake_success",request,shared),duplicate=await run("fake_success",request,shared);record("L","safe_replay",duplicate.result,first.result==="executed"&&duplicate.result==="replayed"&&!duplicate.fake_adapter_called);
  const external=day133ExternalApprovedCommandFixture(),staleEvidence={...external.approval_evidence.reauthentication_evidence!,reauthenticated_at:"2026-07-21T00:00:00.000Z",final_confirmation_at:"2026-07-21T00:00:30.000Z"},staleCommand={...external,approval_evidence:{...external.approval_evidence,reauthentication_evidence:staleEvidence}},expired=parseFarmOsExecutionGatewayRequest(day133GatewayRequestFixture(staleCommand));record("K2","REAUTHENTICATION_EXPIRED",expired.valid?"allowed":expired.blocked_reason,!expired.valid&&expired.blocked_reason==="REAUTHENTICATION_EXPIRED");
  const correlation=parseFarmOsExecutionGatewayRequest({...request,correlation_id:"correlation_mismatch_day133"});record("M","CORRELATION_MISMATCH",correlation.valid?"allowed":correlation.blocked_reason,!correlation.valid&&correlation.blocked_reason==="CORRELATION_MISMATCH");const unknown=parseFarmOsExecutionGatewayRequest({...request,unknown:true});record("N","UNKNOWN_FIELD",unknown.valid?"allowed":unknown.blocked_reason,!unknown.valid&&unknown.blocked_reason==="UNKNOWN_FIELD");const raw=JSON.stringify(request).replace('"gateway_request_id":','"gateway_request_id":"gateway_request_duplicate_day133","gateway_request_id":');const duplicateField=parseFarmOsExecutionGatewayRequestJson(raw);record("O","DUPLICATE_FIELD",duplicateField.valid?"allowed":duplicateField.blocked_reason,!duplicateField.valid&&duplicateField.blocked_reason==="DUPLICATE_FIELD");const malformed=await run("fake_success",{approved_command:{}});record("P","structured_blocked",malformed.rejection??"allowed",malformed.result==="blocked"&&malformed.rejection!==null);
  const trace=success.gateway_result?.trace;record("trace_continuity","complete",trace?.command_hash===command.idempotency.command_hash?"complete":"invalid",trace?.proposal_hash===command.proposal_reference.proposal_hash,trace?.command_hash===command.idempotency.command_hash);record("result_separation","separated",success.gateway_result?.audit.execution_is_business_fact===false?"separated":"mixed",success.gateway_result?.audit.execution_is_business_fact===false,success.gateway_result?.adapter_result?.business_write_performed===false);record("transition_table","complete",String(FARM_OS_COMMAND_TRANSITION_TABLE.length),FARM_OS_COMMAND_TRANSITION_TABLE.length===6,FARM_OS_COMMAND_TRANSITION_TABLE.every((entry)=>entry.business_write_allowed===false));
  const machine_assertions={gateway_contract_valid:cases.find((item)=>item.test_case_id==="B")?.passed===true,gateway_request_validator_valid:["B","J","M","N","O","P"].every((id)=>cases.find((item)=>item.test_case_id===id)?.passed),approved_command_revalidation_valid:["A","J","K2"].every((id)=>cases.find((item)=>item.test_case_id===id)?.passed),state_machine_valid:["C","D","E","F","G","H","I"].every((id)=>cases.find((item)=>item.test_case_id===id)?.passed),transition_table_complete:cases.find((item)=>item.test_case_id==="transition_table")?.passed===true,fake_adapter_valid:["E","F","G"].every((id)=>cases.find((item)=>item.test_case_id===id)?.passed),adapter_registry_valid:cases.find((item)=>item.test_case_id==="K")?.passed===true,agent_execution_result_separated:cases.find((item)=>item.test_case_id==="result_separation")?.passed===true,trace_continuity_valid:cases.find((item)=>item.test_case_id==="trace_continuity")?.passed===true,l3_reauthorization_rechecked:cases.find((item)=>item.test_case_id==="K2")?.passed===true,duplicate_detection_fixture_valid:cases.find((item)=>item.test_case_id==="L")?.passed===true};
  console.log(JSON.stringify({schema_version:"farmos.day133.fixture.report.v1",cases,fixture_count:cases.length,fixture_pass_count:cases.filter((item)=>item.passed).length,fixture_fail_count:cases.filter((item)=>!item.passed).length,machine_assertions,test_observed_counters:counters}));
}
await main();
