import { parseHermesWorkerWakeRequest } from "../startup_runtime/hermes_worker_startup_store";
import { parseExecution } from "../wake_runtime/hermes_wake_execution_store";
import { parseHermesWakeConfirmationRecord,parseHermesConfirmationWorkerRecord,HERMES_WAKE_CONFIRMATION_POLICY } from "../confirmation_runtime/hermes_wake_confirmation_policy";
import { routeHermesJob } from "../router_runtime/hermes_model_router";
import type { HermesRoutingWorkerSummary } from "../router_runtime/hermes_model_router_contract";
import { HERMES_WORKER_HEARTBEAT_TIMEOUT_MS,type HermesWorkerAdvertisement } from "../worker_runtime/hermes_worker_protocol";
import type { HermesRoutingResumeResult } from "./hermes_routing_resume_contract";
import { HERMES_ROUTING_RESUME_POLICY,createHermesRoutingResumeRecord,createHermesRoutingResumeRequirement,createHermesRoutingResumeSummary,parseHermesCanonicalRoutingDecision,parseHermesResumeQueuedJob,parseHermesRoutingResumeRecord } from "./hermes_routing_resume_policy";
import { createHermesRoutingResumeKeys,type HermesRoutingResumeContext,type HermesRoutingResumeStore } from "./hermes_routing_resume_store";

const fail=(code:string):HermesRoutingResumeResult=>({ok:false,status:code==="routing_resume_disabled"?"disabled":code==="routing_resume_store_unavailable"?"not_ready":"failed",error_code:code,resume_write_performed:false,queue_write_performed:false,worker_claim_performed:false,model_execution_performed:false,fail_closed:true});
const workerSummary=(w:HermesWorkerAdvertisement):HermesRoutingWorkerSummary=>({worker_id:w.worker_id,worker_type:w.worker_type,capabilities:w.capabilities,health:w.health,readiness:w.readiness,runtime_available:w.runtime_available,draining:w.draining,last_heartbeat_at:w.last_heartbeat_at,current_job_id:w.current_job_id,active_job_count:w.active_job_count,max_concurrency:w.max_concurrency});
class StoreFailure extends Error{}
const call=async<T>(p:Promise<T>)=>{try{return await p}catch{throw new StoreFailure()}};

export async function resumeHermesPostWakeRouting(input:{jobId:string;context:HermesRoutingResumeContext;resumeIdFactory?:()=>string;decisionIdFactory?:()=>string;router?:typeof routeHermesJob}):Promise<HermesRoutingResumeResult>{if(!input.context.enabled)return fail("routing_resume_disabled");let s:HermesRoutingResumeStore|undefined;try{s=await input.context.storeFactory();const k=input.context.keys??createHermesRoutingResumeKeys(),now=(input.context.nowIsoFactory??(()=>new Date().toISOString()))(),nowMs=Date.parse(now);
  const jobRaw=await call(s.get(k.job(input.jobId)));if(!jobRaw)return fail("routing_resume_job_not_found");const job=parseHermesResumeQueuedJob(jobRaw);if(!job||job.job.runtime.job_id!==input.jobId)return fail("routing_resume_job_invalid");if(job.job.runtime.status!=="queued")return fail("routing_resume_job_status_not_allowed");if(nowMs>=Date.parse(job.job.runtime.expires_at))return fail("routing_resume_job_expired");
  const routingRaw=await call(s.get(k.routingDecision(input.jobId)));if(!routingRaw)return fail("routing_resume_original_decision_not_found");const routing=parseHermesCanonicalRoutingDecision(routingRaw);if(!routing)return fail("routing_resume_original_decision_invalid");if(routing.job_id!==input.jobId||routing.request_id!==job.job.runtime.request_id)return fail("routing_resume_relationship_mismatch");if(nowMs>=Date.parse(routing.expires_at))return fail("routing_resume_expired");
  const wakeIndexRaw=await call(s.get(k.wakeDecision(routing.decision.decision_id))),wakeIndex=wakeIndexRaw?parseHermesWorkerWakeRequest(wakeIndexRaw):null;if(!wakeIndex||wakeIndex.routing_decision_id!==routing.decision.decision_id)return fail("routing_resume_wake_request_invalid");const requestRaw=await call(s.get(k.wakeRequest(wakeIndex.wake_request_id))),request=requestRaw?parseHermesWorkerWakeRequest(requestRaw):null;if(!request||request.wake_request_id!==wakeIndex.wake_request_id||request.routing_decision_id!==wakeIndex.routing_decision_id||request.target_worker_id!==wakeIndex.target_worker_id||request.required_capability!==wakeIndex.required_capability||request.status!=="acknowledged"||request.target_worker_id===null)return fail("routing_resume_wake_request_invalid");
  const executionRaw=await call(s.get(k.wakeExecution(request.wake_request_id))),execution=executionRaw?parseExecution(executionRaw):null;if(!execution||execution.status!=="sent"||execution.bytes_sent!==102)return fail("routing_resume_wake_execution_invalid");const confirmationRaw=await call(s.get(k.wakeConfirmation(request.wake_request_id))),confirmation=confirmationRaw?parseHermesWakeConfirmationRecord(confirmationRaw):null;if(!confirmation)return fail("routing_resume_confirmation_invalid");if(confirmation.status!=="worker_ready"||!confirmation.worker_boot_confirmed||!confirmation.worker_accepting_jobs)return fail("routing_resume_confirmation_not_ready");
  if(request.routing_decision_id!==routing.decision.decision_id||execution.routing_decision_id!==routing.decision.decision_id||execution.wake_request_id!==request.wake_request_id||confirmation.wake_request_id!==request.wake_request_id||confirmation.execution_id!==execution.execution_id||request.target_worker_id!==execution.target_worker_id||request.target_worker_id!==confirmation.target_worker_id||request.required_capability!==confirmation.required_capability||request.required_capability!==routing.decision.requirement.required_capability)return fail("routing_resume_relationship_mismatch");
  const relation={jobId:input.jobId,requestId:job.job.runtime.request_id,decisionId:routing.decision.decision_id,wakeRequestId:request.wake_request_id,executionId:execution.execution_id,confirmationId:confirmation.confirmation_id,targetWorkerId:confirmation.target_worker_id,capability:confirmation.required_capability};
  const replay=await call(s.replayAtomic({...relation,jobKey:k.job(input.jobId),routingKey:k.routingDecision(input.jobId),routingIdKey:k.routingDecisionId(routing.decision.decision_id),requestKey:k.wakeRequest(request.wake_request_id),executionKey:k.wakeExecution(request.wake_request_id),confirmationKey:k.wakeConfirmation(request.wake_request_id),resumeKey:k.resume(input.jobId),resumeIdKeyPrefix:`${k.prefix}:routing-resume-id:`,jobExpiresAtMs:Date.parse(job.job.runtime.expires_at),routingExpiresAtMs:Date.parse(routing.expires_at)}));if(replay.status!=="not_found"){if(replay.status!=="already_exists")return fail(replay.status);const canonical=replay.record?parseHermesRoutingResumeRecord(replay.record):null;if(!canonical)return fail("routing_resume_record_invalid");return{ok:true,status:"already_exists",resume:canonical,resumed_routing_decision:canonical.resumed_routing_decision,resume_write_performed:false,queue_write_performed:false,worker_claim_performed:false,model_execution_performed:false}}
  const workerRaw=await call(s.get(k.worker(confirmation.target_worker_id)));if(!workerRaw)return fail("routing_resume_worker_not_found");const registry=parseHermesConfirmationWorkerRecord(workerRaw);if(!registry)return fail("routing_resume_worker_invalid");const w=registry.worker,hb=Date.parse(w.last_heartbeat_at);if(w.worker_id!==confirmation.target_worker_id)return fail("routing_resume_relationship_mismatch");if(hb>nowMs)return fail("routing_resume_worker_invalid");if(nowMs-hb>=HERMES_WORKER_HEARTBEAT_TIMEOUT_MS)return fail("routing_resume_worker_stale");if(w.health!=="healthy")return fail("routing_resume_worker_unhealthy");if(w.draining)return fail("routing_resume_worker_draining");if(w.readiness!=="ready")return fail("routing_resume_worker_not_ready");if(!w.runtime_available)return fail("routing_resume_runtime_unavailable");if(!w.capabilities.includes(request.required_capability))return fail("routing_resume_capability_unavailable");if(w.active_job_count>=w.max_concurrency)return fail("routing_resume_capacity_unavailable");
  let resumed;try{resumed=(input.router??routeHermesJob)({requirement:routing.decision.requirement,workers:[workerSummary(w)],nowIso:now,decisionIdFactory:input.decisionIdFactory})}catch{return fail("routing_resume_router_not_selected")}if(resumed.status!=="selected"||!resumed.selected_worker)return fail("routing_resume_router_not_selected");if(resumed.selected_worker.worker_id!==confirmation.target_worker_id)return fail("routing_resume_target_changed");
  const expiries=await call(Promise.all([k.job(input.jobId),k.routingDecision(input.jobId),k.wakeRequest(request.wake_request_id),k.wakeExecution(request.wake_request_id),k.wakeConfirmation(request.wake_request_id)].map(x=>s!.getExpiryTime(x))));if(expiries.some(x=>x<=0))return fail("routing_resume_expired");const relatedExpiry=Math.min(Date.parse(confirmation.deadline_at)+HERMES_WAKE_CONFIRMATION_POLICY.record_retention_ms,...expiries);
  let requirement,record;try{requirement=createHermesRoutingResumeRequirement({job,routing,request,execution,confirmation,nowIso:now,relatedExpiryMs:relatedExpiry,resumeIdFactory:input.resumeIdFactory});record=createHermesRoutingResumeRecord({requirement,decision:resumed})}catch(e){return fail(e instanceof Error&&["routing_resume_expired","routing_resume_record_invalid"].includes(e.message)?e.message:"routing_resume_record_invalid")}
  const atomic=await call(s.createAtomic({...relation,jobKey:k.job(input.jobId),routingKey:k.routingDecision(input.jobId),routingIdKey:k.routingDecisionId(routing.decision.decision_id),requestKey:k.wakeRequest(request.wake_request_id),executionKey:k.wakeExecution(request.wake_request_id),confirmationKey:k.wakeConfirmation(request.wake_request_id),workerKey:k.worker(confirmation.target_worker_id),resumeKey:k.resume(input.jobId),newResumeIdKey:k.resumeId(record.resume_id),resumeIdKeyPrefix:`${k.prefix}:routing-resume-id:`,serialized:JSON.stringify(record),expiresAt:record.expires_at,expiresAtMs:Date.parse(record.expires_at),newResumeId:record.resume_id,workerHeartbeatAt:w.last_heartbeat_at,workerHeartbeatAtMs:hb,jobExpiresAt:job.job.runtime.expires_at,jobExpiresAtMs:Date.parse(job.job.runtime.expires_at),routingExpiresAt:routing.expires_at,routingExpiresAtMs:Date.parse(routing.expires_at)}));if(atomic.status!=="created"&&atomic.status!=="already_exists")return fail(atomic.status);const canonical=atomic.record?parseHermesRoutingResumeRecord(atomic.record):null;if(!canonical)return fail("routing_resume_record_invalid");return{ok:true,status:atomic.status,resume:canonical,resumed_routing_decision:canonical.resumed_routing_decision,resume_write_performed:atomic.status==="created",queue_write_performed:false,worker_claim_performed:false,model_execution_performed:false};
 }catch(e){return fail(e instanceof StoreFailure?"routing_resume_store_unavailable":"routing_resume_record_invalid")}finally{await s?.disconnect().catch(()=>undefined)}}

export async function getHermesRoutingResumeStatus(jobId:string,context:HermesRoutingResumeContext){if(!context.enabled)return fail("routing_resume_disabled");let s;try{s=await context.storeFactory();const raw=await s.get((context.keys??createHermesRoutingResumeKeys()).resume(jobId));if(!raw)return{ok:true as const,status:"not_found"as const,resume:null};const r=parseHermesRoutingResumeRecord(raw);if(!r)return fail("routing_resume_record_invalid");return{ok:true as const,status:"found"as const,resume:createHermesRoutingResumeSummary(r)}}catch{return fail("routing_resume_store_unavailable")}finally{await s?.disconnect().catch(()=>undefined)}}
