import { createClient, type RedisClientType } from "redis";
import type { HermesRedisClientConfig } from "../queue_runtime/hermes_redis_client";
import type { HermesRoutingResumeKeys } from "./hermes_routing_resume_contract";

const safe=(v:string)=>{if(!/^[0-9a-z]+(?:-[0-9a-z]+)*$/iu.test(v))throw new Error("routing_resume_key_invalid");return v};
export function createHermesRoutingResumeKeys(prefix="farmos:hermes"):HermesRoutingResumeKeys {if(!/^[0-9a-z:-]+$/iu.test(prefix))throw new Error("routing_resume_prefix_invalid");return{prefix,
  job:id=>`${prefix}:job:${safe(id)}`,routingDecision:id=>`${prefix}:routing-decision:${safe(id)}`,routingDecisionId:id=>`${prefix}:routing-decision-id:${safe(id)}`,wakeDecision:id=>`${prefix}:wake-decision:${safe(id)}`,
  wakeRequest:id=>`${prefix}:wake-request:${safe(id)}`,wakeExecution:id=>`${prefix}:wake-execution:${safe(id)}`,wakeConfirmation:id=>`${prefix}:wake-confirmation:${safe(id)}`,
  worker:id=>`${prefix}:worker:${safe(id)}`,resume:id=>`${prefix}:routing-resume:${safe(id)}`,resumeId:id=>`${prefix}:routing-resume-id:${safe(id)}`}};
type Relationship={jobId:string;requestId:string;decisionId:string;wakeRequestId:string;executionId:string;confirmationId:string;targetWorkerId:string;capability:string};type AtomicResult={status:string;record:string|null};
export type HermesRoutingResumeStore={get:(key:string)=>Promise<string|null>;getExpiryTime:(key:string)=>Promise<number>;
  replayAtomic:(i:Relationship&{jobKey:string;routingKey:string;routingIdKey:string;requestKey:string;executionKey:string;confirmationKey:string;resumeKey:string;resumeIdKeyPrefix:string;jobExpiresAtMs:number;routingExpiresAtMs:number})=>Promise<AtomicResult>;
  createAtomic:(i:Relationship&{jobKey:string;routingKey:string;routingIdKey:string;requestKey:string;executionKey:string;confirmationKey:string;workerKey:string;resumeKey:string;newResumeIdKey:string;resumeIdKeyPrefix:string;serialized:string;expiresAt:string;expiresAtMs:number;newResumeId:string;workerHeartbeatAt:string;workerHeartbeatAtMs:number;jobExpiresAt:string;jobExpiresAtMs:number;routingExpiresAt:string;routingExpiresAtMs:number})=>Promise<AtomicResult>;
  deleteKeys:(keys:string[])=>Promise<void>;disconnect:()=>Promise<void>};
export type HermesRoutingResumeContext={enabled:boolean;storeFactory:()=>Promise<HermesRoutingResumeStore>;keys?:HermesRoutingResumeKeys;nowIsoFactory?:()=>string};

const HELPERS=`
local function iso(v) if type(v)~='string' then return false end;local y,m,d,h,n,s=string.match(v,'^(%d%d%d%d)%-(%d%d)%-(%d%d)T(%d%d):(%d%d):(%d%d)%.%d%d%dZ$');y=tonumber(y);m=tonumber(m);d=tonumber(d);h=tonumber(h);n=tonumber(n);s=tonumber(s);if not y or m<1 or m>12 or h>23 or n>59 or s>59 then return false end;local days={31,28,31,30,31,30,31,31,30,31,30,31};if m==2 and (y%400==0 or (y%4==0 and y%100~=0)) then days[2]=29 end;return d>=1 and d<=days[m] end
local function integer(v) return type(v)=='number' and v>=0 and v==math.floor(v) end
local function heavy(v) return v=='heavy_reasoning' or v=='large_context' or v=='gpu_inference' end
local function routing(d)
 if type(d)~='table' or d['schema_version']~='hermes.router.decision.v1' or d['decision_id']~=ARGV[3] or d['status']~='no_ready_worker' or d['selected_worker']~=cjson.null or d['fallback_used']~=false or not iso(d['decided_at']) or not integer(d['considered_worker_count']) or not integer(d['eligible_worker_count']) then return false end
 local q=d['requirement'];local s=d['safety'];return type(q)=='table' and q['task_class']==ARGV[8] and q['required_capability']==ARGV[8] and heavy(q['required_capability']) and q['preferred_worker_type']=='rtx' and q['allow_fallback']==false and type(s)=='table' and s['worker_claim_performed']==false and s['queue_write_performed']==false and s['model_execution_performed']==false and s['db_write_performed']==false and s['fail_closed']==true
end
local function resume_record(x)
 if type(x)~='table' or x['schema_version']~='hermes.routing.resume.v1' or type(x['resume_id'])~='string' or x['job_id']~=ARGV[1] or x['request_id']~=ARGV[2] or x['original_routing_decision_id']~=ARGV[3] or x['wake_request_id']~=ARGV[4] or x['wake_execution_id']~=ARGV[5] or x['wake_confirmation_id']~=ARGV[6] or x['target_worker_id']~=ARGV[7] or x['selected_worker_id']~=ARGV[7] or x['required_capability']~=ARGV[8] or x['status']~='selected' or x['reason_code']~='routing_resume_selected' or not iso(x['created_at']) or x['completed_at']~=x['created_at'] or not iso(x['expires_at']) or x['worker_boot_confirmed']~=true or x['worker_accepting_jobs']~=true or x['queue_write_performed']~=false or x['worker_claim_performed']~=false or x['model_execution_performed']~=false then return false end
 local d=x['resumed_routing_decision'];if type(d)~='table' or d['decision_id']~=x['resumed_routing_decision_id'] or d['status']~='selected' or type(d['selected_worker'])~='table' or d['selected_worker']['worker_id']~=ARGV[7] or d['task_class']~=ARGV[8] or d['required_capability']~=ARGV[8] or d['fallback_used']~=false or not iso(d['decided_at']) then return false end
 local s=x['safety'];return type(s)=='table' and s['network_target_stored']==false and s['credentials_stored']==false and s['remote_connection_performed']==false and s['db_write_performed']==false and s['fail_closed']==true
end
`;
const COMMON=HELPERS+`
local jj=redis.call('GET',KEYS[1]);local dj=redis.call('GET',KEYS[2]);local rj=redis.call('GET',KEYS[4]);local ej=redis.call('GET',KEYS[5]);local cj=redis.call('GET',KEYS[6])
if not jj then return {'routing_resume_job_not_found',''} end;if not dj then return {'routing_resume_original_decision_not_found',''} end;if not rj then return {'routing_resume_wake_request_invalid',''} end;if not ej then return {'routing_resume_wake_execution_invalid',''} end;if not cj then return {'routing_resume_confirmation_invalid',''} end
local jok,j=pcall(cjson.decode,jj);local dok,d=pcall(cjson.decode,dj);local rok,r=pcall(cjson.decode,rj);local eok,e=pcall(cjson.decode,ej);local cok,c=pcall(cjson.decode,cj)
if not jok or j['schema_version']~='hermes.queue.v1' or j['job']['schema_version']~='hermes.job.v1' or j['job']['runtime']['job_id']~=ARGV[1] or j['job']['runtime']['request_id']~=ARGV[2] or j['job']['runtime']['status']~='queued' or j['queue']['status']~='queued' or not iso(j['job']['runtime']['expires_at']) then return {'routing_resume_job_invalid',''} end
if not dok or d['schema_version']~='hermes.router.decision.record.v1' or d['job_id']~=ARGV[1] or d['request_id']~=ARGV[2] or d['expires_at']~=j['job']['runtime']['expires_at'] or not iso(d['expires_at']) or not routing(d['decision']) then return {'routing_resume_original_decision_invalid',''} end
local rs=r and r['safety'];if not rok or r['schema_version']~='hermes.worker.wake.request.v1' or r['worker_type']~='rtx' or r['wake_request_id']~=ARGV[4] or r['routing_decision_id']~=ARGV[3] or r['target_worker_id']~=ARGV[7] or r['required_capability']~=ARGV[8] or r['status']~='acknowledged' or r['requested_by']~='server_policy' or type(rs)~='table' or rs['wol_packet_sent']~=false or rs['ssh_connection_performed']~=false or rs['gpu_detection_performed']~=false or rs['worker_execution_performed']~=false or rs['model_execution_performed']~=false or rs['secret_stored']~=false or rs['db_write_performed']~=false or rs['fail_closed']~=true then return {'routing_resume_wake_request_invalid',''} end
local es=e and e['safety'];if not eok or e['schema_version']~='hermes.wake.execution.v1' or e['execution_id']~=ARGV[5] or e['wake_request_id']~=ARGV[4] or e['routing_decision_id']~=ARGV[3] or e['target_worker_id']~=ARGV[7] or e['transport']~='udp_wol' or e['status']~='sent' or tonumber(e['bytes_sent'])~=102 or not iso(e['completed_at']) or e['error_code']~=cjson.null or type(es)~='table' or es['network_target_stored']~=false or es['mac_address_stored']~=false or es['broadcast_address_stored']~=false or es['credentials_stored']~=false or es['ssh_connection_performed']~=false or es['remote_command_performed']~=false or es['gpu_detection_performed']~=false or es['model_execution_performed']~=false or es['db_write_performed']~=false or es['fail_closed']~=true then return {'routing_resume_wake_execution_invalid',''} end
local cs=c and c['safety'];if not cok or c['schema_version']~='hermes.wake.confirmation.v1' or c['confirmation_id']~=ARGV[6] or c['wake_request_id']~=ARGV[4] or c['execution_id']~=ARGV[5] or c['target_worker_id']~=ARGV[7] or c['required_capability']~=ARGV[8] or c['status']~='worker_ready' or c['worker_boot_confirmed']~=true or c['worker_accepting_jobs']~=true or not iso(c['completed_at']) or type(cs)~='table' or cs['ssh_connection_performed']~=false or cs['remote_command_performed']~=false or cs['gpu_detection_performed']~=false or cs['model_execution_performed']~=false or cs['queue_write_performed']~=false or cs['job_retry_performed']~=false or cs['db_write_performed']~=false or cs['fail_closed']~=true then return {'routing_resume_confirmation_invalid',''} end
local tm=redis.call('TIME');local nowms=tonumber(tm[1])*1000+math.floor(tonumber(tm[2])/1000);for i=1,6 do local x=redis.call('PEXPIRETIME',KEYS[i]);if x==-2 then return {'routing_resume_record_invalid',''} end;if x==-1 or x<=nowms then return {'routing_resume_expired',''} end end
if redis.call('GET',KEYS[3])~=ARGV[1] or redis.call('PEXPIRETIME',KEYS[3])~=redis.call('PEXPIRETIME',KEYS[2]) then return {'routing_resume_record_invalid',''} end
if tonumber(ARGV[9])<=nowms or tonumber(ARGV[10])<=nowms then return {'routing_resume_expired',''} end
`;
const REPLAY=COMMON+`
local existing=redis.call('GET',KEYS[7]);if not existing then return {'not_found',''} end;local ok,x=pcall(cjson.decode,existing);if not ok or not resume_record(x) then return {'routing_resume_record_invalid',''} end
local rx=redis.call('PEXPIRETIME',KEYS[7]);local idkey=ARGV[11]..x['resume_id'];local ix=redis.call('PEXPIRETIME',idkey);if redis.call('GET',idkey)~=ARGV[1] or rx==-1 or rx<=nowms or ix~=rx then return {'routing_resume_record_invalid',''} end
return {'already_exists',existing}`;
const CREATE=COMMON+`
local existing=redis.call('GET',KEYS[8]);if existing then local ok,x=pcall(cjson.decode,existing);if not ok or not resume_record(x) then return {'routing_resume_record_invalid',''} end;local rx=redis.call('PEXPIRETIME',KEYS[8]);local idkey=ARGV[11]..x['resume_id'];if redis.call('GET',idkey)~=ARGV[1] or redis.call('PEXPIRETIME',idkey)~=rx then return {'routing_resume_record_invalid',''} end;return {'already_exists',existing} end
local wj=redis.call('GET',KEYS[7]);if not wj then return {'routing_resume_worker_not_found',''} end;local wok,w=pcall(cjson.decode,wj);if not wok or w['schema_version']~='hermes.worker.registry.v1' or w['worker']['worker_id']~=ARGV[7] or w['worker']['worker_type']~='rtx' or w['worker']['health']~='healthy' or w['worker']['readiness']~='ready' or w['worker']['runtime_available']~=true or w['worker']['draining']~=false or w['worker']['last_heartbeat_at']~=ARGV[15] or tonumber(w['worker']['active_job_count'])>=tonumber(w['worker']['max_concurrency']) then return {'routing_resume_worker_invalid',''} end
local hb=tonumber(ARGV[16]);if not hb or hb>nowms or nowms-hb>=45000 then return {'routing_resume_worker_stale',''} end;local capable=false;for _,cap in ipairs(w['worker']['capabilities']) do if cap==ARGV[8] then capable=true end end;if not capable then return {'routing_resume_capability_unavailable',''} end
if j['job']['runtime']['expires_at']~=ARGV[17] or tonumber(ARGV[18])<=nowms or d['expires_at']~=ARGV[19] or tonumber(ARGV[20])<=nowms then return {'routing_resume_expired',''} end
local nok,n=pcall(cjson.decode,ARGV[12]);local expiry=tonumber(ARGV[13]);if not nok or not resume_record(n) or n['resume_id']~=ARGV[14] or n['expires_at']~=ARGV[21] or expiry<=nowms or KEYS[9]~=ARGV[11]..ARGV[14] or redis.call('EXISTS',KEYS[9])~=0 then return {'routing_resume_record_invalid',''} end
for i=1,6 do if expiry>redis.call('PEXPIRETIME',KEYS[i]) then return {'routing_resume_expired',''} end end
redis.call('SET',KEYS[8],ARGV[12],'PXAT',ARGV[13]);redis.call('SET',KEYS[9],ARGV[1],'PXAT',ARGV[13]);return {'created',ARGV[12]}`;
const timeout=<T>(p:Promise<T>,ms:number)=>new Promise<T>((resolve,reject)=>{const t=setTimeout(()=>reject(new Error("routing_resume_store_timeout")),ms);p.then(v=>{clearTimeout(t);resolve(v)},e=>{clearTimeout(t);reject(e)})});
export async function createHermesRoutingResumeStore(config:HermesRedisClientConfig):Promise<HermesRoutingResumeStore>{const client:RedisClientType=createClient({url:config.url,socket:{connectTimeout:config.connectTimeoutMs}});client.on("error",()=>undefined);await timeout(client.connect(),config.connectTimeoutMs);const cmd=<T>(p:Promise<T>)=>timeout(p,config.commandTimeoutMs);const rel=(i:Relationship)=>[i.jobId,i.requestId,i.decisionId,i.wakeRequestId,i.executionId,i.confirmationId,i.targetWorkerId,i.capability];return{get:k=>cmd(client.get(k)),getExpiryTime:k=>cmd(client.pExpireTime(k)),async replayAtomic(i){const x=await cmd(client.eval(REPLAY,{keys:[i.jobKey,i.routingKey,i.routingIdKey,i.requestKey,i.executionKey,i.confirmationKey,i.resumeKey],arguments:[...rel(i),String(i.jobExpiresAtMs),String(i.routingExpiresAtMs),i.resumeIdKeyPrefix]}))as unknown[];return{status:String(x[0]),record:String(x[1]??"")||null}},async createAtomic(i){const x=await cmd(client.eval(CREATE,{keys:[i.jobKey,i.routingKey,i.routingIdKey,i.requestKey,i.executionKey,i.confirmationKey,i.workerKey,i.resumeKey,i.newResumeIdKey],arguments:[...rel(i),String(i.jobExpiresAtMs),String(i.routingExpiresAtMs),i.resumeIdKeyPrefix,i.serialized,String(i.expiresAtMs),i.newResumeId,i.workerHeartbeatAt,String(i.workerHeartbeatAtMs),i.jobExpiresAt,String(i.jobExpiresAtMs),i.routingExpiresAt,String(i.routingExpiresAtMs),i.expiresAt]}))as unknown[];return{status:String(x[0]),record:String(x[1]??"")||null}},async deleteKeys(keys){if(keys.length)await cmd(client.del(keys))},async disconnect(){if(client.isOpen)await client.quit()}}}
